### ISSUE TITLE
TypeError: handler is not a function only when deployed to firebase but not when serve

### ISSUE THREAD

**Issue by jojonarte** [vercel/next.js#10227]
# Examples bug report

## Error: > handler is not a function
- Downloaded the sample using the instructions in the description and ensuring everything works
- Integrated custom `express` server to handle redirection see https://github.com/jojonarte/with-express-firebasehosting-next
- Tested the application okay with `npm run serve` everything in the application works
- Tested with `npm run deploy`, deployment was successful however opening the hosting URL results in `Error: could not handle the request` and in firebase functions log `TypeError: handler is not a function
    at cloudFunction (/srv/node_modules/firebase-functions/lib/providers/https.js:57:9)
    at /worker/worker.js:783:7
    at /worker/worker.js:766:11
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://github.com/jojonarte/with-express-firebasehosting-next
2. follow manual download instructions
3. follow firebase setup instructions
4. `npm install`
5. `npm run serve` should make the app work
5. `npm run deploy`
6. view the URL

## should build and upload to hosting and firebase functions and error shouldn't show just like in `npm run serve`

I expected it should build and deploy the cloud function and hosting properly to firebase just like how it works using `npm run serve`

## System information

- OS: macOS
- Version of Next.js: "^9.1.7"

**Comment by thevvv36** [comment]
hey can i contribute a take this issue

**Comment by jojonarte** [comment]
sure

**Comment by shivgodi7** [comment]
Hello folks !
Any fix available for this issue ? Thanks !

**Comment by balazsorban44** [comment]
@thevvv36 do you still have interest in helping out on this?

**Comment by aayank13** [comment]
Can I work on this issue?

**Comment by jackunion** [comment]
@jojonarte any updates on this?
Based on my quick google search this looks like an issue with how firebase functions are set up and not with nextjs. Are you 100% sure this is a nextjs issue? Any way to test this without having to set up the firebase project?

**Comment by Codenuclei** [comment]
@ijjk hey i guess you forgot to close this issue. kindly reminder to close this issue reason remains along the thread. ; )
