### ISSUE TITLE
_next/image 404 on next build && next export

### ISSUE THREAD

**Issue by jericopulvera** [vercel/next.js#18356]
# Bug report

## Describe the bug

Images are 404 on next build && next export. Works properly next build && next start

## To Reproduce

1. npx create-next-app --example image-component image-app
2. cd image-app
3. npx next build && npx next export && cd out && npx serve
4. visit localhost:5000

## Screenshots

![image](https://user-images.githubusercontent.com/23246308/97381906-08e9c100-1905-11eb-95cc-a0855c433c19.png)

## System information

- OS: macOS Mojave
- Version of Next.js: [e.g. 10.0.0]
- Version of Node.js: [e.g. 12.18.4]

**Comment by melvin2016** [comment]
<img width="1440" alt="Screenshot 2020-10-28 at 3 24 35 PM" src="https://user-images.githubusercontent.com/22199666/97420749-b7a3f680-1931-11eb-8edb-6754589134f4.png">
Same for me too.

OS: macOS Mojave
Version of Next.js: v10
Version of Node.js: v12.17.0

**Comment by muhaimincs** [comment]
same for me. On localhost it's ok but not on Netlify

**Comment by mclngl** [comment]
> Instead of optimizing images at build time, Next.js 10 optimizes images on-demand, as users request them. Unlike static site generators and static-only solutions, your build times aren't increased, whether shipping 10 images or 10 million images.

I guess it probably requires the node server.

Also `/_next/image?url=%2Fimages%2Fpicture.png&w=1200&q=75` this is what the endpoint looks like so it makes sense.

Passing the unoptimized props should fix that, but at the expense of losing most of the benefits (no srcset added).

**Comment by nickroberts** [comment]
The image component would have to have some sort of static generation mode, where it would function like [gatsby-image](https://www.gatsbyjs.com/plugins/gatsby-image/), and generate the optimized image on build time.

I think if you are using some sort of external service, such as Imgix, this shouldn't be an issue for built times, as it should be able to just generate the urls needed, and doesn't need to actually generate the images themselves.

I haven't used it, but I think the [react-imgix](https://github.com/imgix/react-imgix) component does this today.

**Comment by Timer** [comment]
I believe the solution here is to fail `next export` unless if you configure a 3rd party image optimizer service (can't use the default one as it requires `next start`).

**Comment by sethlarkin** [comment]
I am having this problem as well trying to deploy on Netlify. Could anyone explain why this doesn't show up after exporting and running `next start` locally?

**Comment by marlonmarcello** [comment]
@Timer that should be listed on the documentation as well. I had the same realization as everybody here, I thought that the image would just work.

**Comment by nahtnam** [comment]
I tried to use `next-on-netlify` and that doesn't seem to work either. Maybe the serverless handlers that are outputted also don't have the processor?

**Comment by Jaynam07** [comment]
Any solution to this?

**Comment by eloquentmack** [comment]
@Jaynam07: I ended up not using `next/image`, but instead using `next-optimized-images`. I didn't find any other solution right now, I'm hoping it will be supported at some point (or at least Netlify adds support to `next-on-netlify`).

**Comment by Timer** [comment]
We'll need to add something like this:
```ts
  if (!options.buildExport) {
    const isDefaultImageLoader =
      !nextConfig.images.loader || nextConfig.images.loader === 'default'
    if (isDefaultImageLoader) {
      Log.error(
        "next export cannot be used with Next.js' default image loader, as it relies on `next start`."
      )
      // stop export ...
    }
  }
```

However, it's tricky because we cannot error for projects that don't use `next/image` at all—this would be a breaking change.

**Comment by maxwellpopescu** [comment]
So I take it the Next Image component will generate the correct URLs/srcsets from Cloud providers [which have their own loader](https://nextjs.org/docs/basic-features/image-optimization#loader). In which case, next export and next/image will be fine.

For those of us serving from a CMS which does not have its own loader in Next/Image, can we expect them to be added in the future? Many CMS CDNs also have on-the-fly image optimization.

As it stands, Cloudinary/Imgix/Akamai loaders are baked into the component, but it wouldn't really be feasible to add loaders for all the other providers like that.

**Comment by elitan** [comment]
> We'll need to add something like this to `packages/next/export/index.ts`:
> 
> ```ts
>   if (!options.buildExport) {
>     const isDefaultImageLoader =
>       !nextConfig.images.loader || nextConfig.images.loader === 'default'
>     if (isDefaultImageLoader) {
>       Log.error(
>         "next export cannot be used with Next.js' default image loader, as it relies on `next start`."
>       )
>       // stop export ...
>     }
>   }
> ```
> 
> However, it's tricky because we cannot error for projects that don't use `next/image` at all—this would be a breaking change.

That will show an error during `next export` I presume, but what about actually generate the images during the `next export` (and not just for `next start`)?

**Comment by zackdotcomputer** [comment]
Yeah - ideally this would both be a noisy failure and also not-completely-broken... I think it's a good idea to both:

1. Generate a warning/error on export (since you are going to lose a bunch of the features like automatic resizing and translation into webp). This will let the developer know they're probably making a mistake.

2. But also fix the static export so that the component generates a functional `<img>` tag instead of the broken one it now outputs.

**Comment by ceodigvijay** [comment]
> > We'll need to add something like this to `packages/next/export/index.ts`:
> > ```ts
> >   if (!options.buildExport) {
> >     const isDefaultImageLoader =
> >       !nextConfig.images.loader || nextConfig.images.loader === 'default'
> >     if (isDefaultImageLoader) {
> >       Log.error(
> >         "next export cannot be used with Next.js' default image loader, as it relies on `next start`."
> >       )
> >       // stop export ...
> >     }
> >   }
> > ```
> > 
> > 
> > However, it's tricky because we cannot error for projects that don't use `next/image` at all—this would be a breaking change.
> 
> That will show an error during `next export` I presume, but what about actually generate the images during the `next export` (and not just for `next start`)?

This will slow the build process, but a great idea. Better to implement with a separate option in the config file to optimize images during export.

**Comment by krystof-k** [comment]
Well, so no plans to support build-time generation of optimized images so that `next export` works properly?

**Comment by maxwaiyaki** [comment]
Is there a solution so far??

**Comment by krystof-k** [comment]
I switched to canary version of [next-optimized-images](https://github.com/cyrilwanner/next-optimized-images). Working all right so far.

**Comment by melvin2016** [comment]
> I switched to canary version of [next-optimized-images](https://github.com/cyrilwanner/next-optimized-images). Working all right so far.

It's showing me an error of MaxEventListeners

**Comment by jlarmstrongiv** [comment]
Can this issue be re-opened?  An optional build-time generation of optimized images would be the best solution for me.

**Comment by timneutkens** [comment]
> Can this issue be re-opened? An optional build-time generation of optimized images would be the best solution for me.

There's an open feature request on https://github.com/vercel/next.js/discussions so no need to keep this open.

**Comment by flaviut** [comment]
The discussion is at https://github.com/vercel/next.js/discussions/19065, specifically.

The maintainers are [using 👍s on the discussion to gauge interest](https://github.com/vercel/next.js/discussions/19065#discussioncomment-139615). Please 👍 it if you've run into this.

**Comment by lokesh14v** [comment]
Do images work after the next build is taken
am still facing these 404 issues 

<img width="1142" alt="Screenshot 2020-12-28 at 1 10 19 PM" src="https://user-images.githubusercontent.com/26504161/103262214-220dfd00-499c-11eb-9e99-f8008c792449.png">

**Comment by lokesh14v** [comment]
> > Can this issue be re-opened? An optional build-time generation of optimized images would be the best solution for me.
> 
> There's an open feature request on https://github.com/vercel/next.js/discussions so no need to keep this open.

Do images work after the next build is taken
am still facing these 404 issues 

<img width="1142" alt="Screenshot 2020-12-28 at 1 10 19 PM" src="https://user-images.githubusercontent.com/26504161/103262214-220dfd00-499c-11eb-9e99-f8008c792449.png">

**Comment by barayuda** [comment]
any update about this bug?

Just got an error when tried next/image in NextJS 10
I updated my next.config.js like this
`module.exports = {
  target: "serverless",
  images: {
    domains: ["images.ctfassets.net"],
  },
};
`
I tried to deploy NextJS+Contentful to Netlify and got these errors
```
11:36:57 AM: > next export
11:36:57 AM: info  - using build directory: /opt/build/repo/.next
11:36:57 AM: info  - Copying "static build" directory
11:36:58 AM: info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
11:36:58 AM: Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
Possible solutions:
11:36:58 AM:   - Use `next start`, which starts the Image Optimization API.
11:36:58 AM:   - Use Vercel to deploy, which supports Image Optimization.
11:36:58 AM:   - Configure a third-party loader in `next.config.js`.
11:36:58 AM: Read more: https://err.sh/next.js/export-image-api
11:36:58 AM:     at exportApp (/opt/build/repo/node_modules/next/dist/export/index.js:14:712)
11:36:58 AM: npm ERR! code ELIFECYCLE
11:36:58 AM: npm ERR! errno 1
```

Is there `next/image` loader for Netlify?
Cause, the possibility of fixing mention here https://err.sh/next.js/export-image-api we need to use a loader to optimize external images

**Comment by Chamnol007** [comment]
Please check your image src if you are using `basePath`.
I got the same problem, when changing from `<img />` to `<Next/Image>`

**Comment by sahanatroam** [comment]
having the same issue now on latest Next.js version. the image keep saying 404.

<img width="442" alt="Screen Shot 2021-02-10 at 09 56 47" src="https://user-images.githubusercontent.com/29851224/107427451-4ad20680-6b86-11eb-8ed8-c35c8dde84b9.png">

**Comment by leerob** [comment]
One thing that's important to clarify here: `next/image` _does_ work with `next export` if you're specifying a custom loader. This makes sense, because you're not using a server when you export a static site – so you're deferring image optimization to somewhere else that has a sever.

As mentioned above, there's an open issue for running image optimization at build time. Just wanted to clarify the discussion here 😄

**Comment by Sir-Chasington** [comment]
> having the same issue now on latest Next.js version. the image keep saying 404.
> 
> 


Did you ever find a solution, or is there one? I am having the same issue on Heroku

**Comment by ameernormie** [comment]
I stopped using `next/image` and simply switched to `next-optimized-images`.

**Comment by inezabonte** [comment]
Guess I'll use the same approch.

**Comment by paufar** [comment]
Is there a reason why nested folder in the public folder result in a 404? i have left a separate question but got no reply
https://github.com/vercel/next.js/discussions/24041

**Comment by jedireza** [comment]
> > having the same issue now on latest Next.js version. the image keep saying 404.
> 
> Did you ever find a solution, or is there one? I am having the same issue on Heroku

I just ran into this on Heroku and noticed my logs had something like:

```
Module did not self-register: '/app/.heroku/heroku-nodejs-plugin/heroku-nodejs-plugin.node'.
```

See: https://github.com/heroku/heroku-buildpack-nodejs/issues/727

After I disabled `Enhanced Language Metrics` and restarted the dynos things started working again.

Hope this helps.

**Comment by inezabonte** [comment]
I deployed my app on Vercel and it works fine there. But again it depends on the use case since we have different needs. If you don't mind switching platforms you can try Vercel. If it's not possible for you then `next-optimized-images` is another solution.

**Comment by owaishanif786** [comment]
using next-optimzed-images in next.config.js but still error 
```
module.exports = withPlugins([
  [
    optimizedImages,
    {
      // these are the default values so you don't have to provide them if they are good enough for your use-case.
      // but you can overwrite them here with any valid value you want.
      inlineImageLimit: 8192,
      imagesFolder: 'images',
      imagesName: '[name]-[hash].[ext]',
      handleImages: ['jpeg', 'png', 'svg', 'webp', 'gif'],
      removeOriginalExtension: false,
      optimizeImages: true,
      optimizeImagesInDev: false,
      mozjpeg: {
        quality: 80,
      },
      optipng: {
        optimizationLevel: 3,
      },
      pngquant: false,
      gifsicle: {
        interlaced: true,
        optimizationLevel: 3,
      },
      svgo: {
        // enable/disable svgo plugins here
      },
      webp: {
        preset: 'default',
        quality: 75,
      },
    },
  ],
])
```

**Comment by SSylvain1989** [comment]
I don't understand why you don't say it in the **big print documentation**, "**_be careful next image doesn't work with next export, i18n doesn't work with next export_**" all this work for nothing, such a waste of time

[here next documentation about image optimisation](https://vercel.com/docs/next.js/image-optimization) i don't understand @leerob you say next/image work with a loader , but here , that say we don't need one if we hosting on vercel directly 

> A Source Image is the original, unaltered image determined by the src prop.

> When the src prop is an internal path (an image in the current deployment), the file contents are hashed to determine the Source Image.
> 
> When the src prop is an external URL (an image hosted elsewhere), the URL is used to determine the Source Image.
> 
> A single Source Image can be transformed into many Optimized Images. Take the following for example:

```
Usage: <Image src="/hero.png" width="700" height="745" />
Source Image: /hero.png
Optimized Image: /_next/image?url=%2Fhero.png&w=750&q=75
Optimized Image: /_next/image?url=%2Fhero.png&w=828&q=75
Optimized Image: /_next/image?url=%2Fhero.png&w=1080&q=75
```

so if i use a loader or not , all my image in public file will pop up without any configuration . 
i don't understand what is the probleme here ...

**Comment by eliobricenov** [comment]
> using next-optimzed-images in next.config.js but still error
> 
> ```
> module.exports = withPlugins([
>   [
>     optimizedImages,
>     {
>       // these are the default values so you don't have to provide them if they are good enough for your use-case.
>       // but you can overwrite them here with any valid value you want.
>       inlineImageLimit: 8192,
>       imagesFolder: 'images',
>       imagesName: '[name]-[hash].[ext]',
>       handleImages: ['jpeg', 'png', 'svg', 'webp', 'gif'],
>       removeOriginalExtension: false,
>       optimizeImages: true,
>       optimizeImagesInDev: false,
>       mozjpeg: {
>         quality: 80,
>       },
>       optipng: {
>         optimizationLevel: 3,
>       },
>       pngquant: false,
>       gifsicle: {
>         interlaced: true,
>         optimizationLevel: 3,
>       },
>       svgo: {
>         // enable/disable svgo plugins here
>       },
>       webp: {
>         preset: 'default',
>         quality: 75,
>       },
>     },
>   ],
> ])
> ```
> 
> info - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
> Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
> Possible solutions:
> - Use `next start` to run a server, which includes the Image Optimization API.
> - Use any provider which supports Image Optimization (like Vercel).
> - Configure a third-party loader in `next.config.js`.
> - Use the `loader` prop for `next/image`.
> Read more: https://nextjs.org/docs/messages/export-image-api

+1 

Still have the error.

**Comment by JYeop** [comment]
Anyone has resolved this issue? Still have this error after export.

**Comment by inezabonte** [comment]
@JYeop I switched to vercel for the hosting. Solved the issue for me

**Comment by chemicalkosek** [comment]
> using next-optimzed-images in next.config.js but still error

After a quick look it seems you misinterpreted your solution.
Adding `next-optimized-images` will not make `next/image` work on `next export` without third party loaders.
`next-optimized-images` is not a loader, it's a different image solution than `next/image`.

If you want do `next export` you can swap out all `next/image` components (`<Image />`)  with `next-optimized-images` ones.
All define a loader like imgix or cloudinary.
Or deploy to Vercel.

**Comment by nvh95** [comment]
This is how I made `next/image` works with `next export`. The idea is to wrap `next/image` into `components/Image.js` and provide it a custom loader.
```diff
// next.config.js
module.exports = {
  reactStrictMode: true,
+  images: {
+   loader: "custom",
+ },
};

```

```js
// components/Image.js
import NextImage from "next/image";

const customLoader = ({ src, width, quality }) => {
  return src
}

export default function Image(props) {
  return (
    <NextImage
      {...props}
      loader={customLoader}
    />
  );
}
```

```diff
// pages/index.js
- import Image from 'next/image'
+ import Image from 'components/Image'

export default function Home() {
  return (
    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  )
}

```
