### ISSUE TITLE
next/image on node 16 give SIGSEGV

### ISSUE THREAD

**Issue by artecoop** [vercel/next.js#24421]
### What version of Next.js are you using?

10.1.3

### What version of Node.js are you using?

16.0.0

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

macOS 11.2.3

### How are you deploying your application?

next dev

### Describe the Bug

Mac Mini M1, Node 16 next start crashes hitting next/images
Already nuked node_modules and locks after updating node version

```
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /Users/vfornito/DEV/gvdp/vdp/.env.development
info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
(node:2822) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/vfornito/DEV/gvdp/node_modules/next/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

To work :)

### To Reproduce

Use a simple next/image on a next.js project. Either using js or TS does not change the behavior

**Comment by apollonian** [comment]
Could something else be the cause of this? Image works fine for me on node v16.0.0 (Intel/macOS)!

**Comment by artecoop** [comment]
Node V16 introduced the support for Apple silicon, could be this the cause?

**Comment by davidossahdez** [comment]
I'm experiencing this problem too. Just tested in a fresh installed macOS and a simple Next JS project. It crashes using either Node LTS or 16.0.0. My dev script works fine until you scroll into view any next/image component, so maybe the bug its related with the lazy loading?

I can confirm it only happens in my dev environment, pushing to production works completely fine for me. I'm using a MacBook Air M1 and deploying to Vercel, if that helps.

**Comment by lavgup** [comment]
Updated to Node v16 via Homebrew on my M1 Mac Mini and faced the same issue. Was able to start up the dev environment but going to a page with `next/image` crashed the server. Downgrading to Node v15.14.0 fixed the issue (plus got rid of many warnings due to lack of support for v16).

**Comment by RuiGuilherme** [comment]
[Postcss has issue about this and lasted version of postcss fix this issue.](https://github.com/postcss/postcss/issues/1455#issuecomment-826016865)

You can try go to **node_modules/next** and run **yarn add postcss**. But I think this can break NextJS.

**Comment by 16abhimasani** [comment]
Also seeing this error (crashes application); fresh install of node on M1 goes to v16. Adding postcss latest version manually to top level does not fix issue.

**Comment by 16abhimasani** [comment]
when can we expect this bug fix to be released (seeing next @ 10.1.3 still)? just saw that you merged in the change

**Comment by 16abhimasani** [comment]
Just upgraded to next@10.2.0 and actually still getting SIGSEGV error when next/image is on page. @artecoop can you confirm that this is either working or fixed for you? I am curious if I need to downgrade from node v16

**Comment by davidossahdez** [comment]
I'm still getting it, although less often. Using Node v16 with `next@10.2.0` and `postcss@8.2.13`. I don't know what I'm doing wrong but I get the same problem with Node LTS. Tried using `nvm use --lts`

**Comment by artecoop** [comment]
Nothing changed here, apart from a slight delay instead of instantaneously crash.

**Comment by njdullea** [comment]
Using `next@10.1.0` and node `15.9.0` resolved this issue for me.

**Comment by artecoop** [comment]
@njdullea because Node 15.x is compiled for intel and runs under rosetta.

BTW this morning I've updated to the freshly released node 16.1.0 without any luck.

**Comment by artecoop** [comment]
@timneutkens you should reopen this issue, is not resolved at all

**Comment by Yagogc** [comment]
Yep, I still have the same issue. I tried all the workarounds offered here but nothing worked...

**Comment by zuccs** [comment]
FWIW mine crashes on a PNG, but not an SVG, using next-image.

**Comment by jca41** [comment]
Same issue, M1 with node 16.1.0. Back to Rosetta 😄

**Comment by trm217** [comment]
Same for me, I can no longe start a next.js application with Node 16 on Apple M1

**Comment by artecoop** [comment]
> I have the same problem and I tried with `node@16.1.0` and `yarn@1.22.10`. So I tried with `npm@7.11.2` and it works again. Have to stop using `yarn` for a while.

Nope, does not work for me
`[1]    2541 segmentation fault  npm run dev`

**Comment by trm217** [comment]
@artecoop Have attempted to debug what causes the sigsev error on your system?

**Comment by artecoop** [comment]
@trm217 honestly no, I hoped for a quick solution from the Vercel team :laughing:
I'm always working on small projects so for me refactoring back and forth from img to next/image isn't a problem during the cycle development - production. And since I deploy to Vercel and it does not have problem, I'm good for now.
I have very little spare time, but I'll try to give some to at least find a direction for a solution

**Comment by artecoop** [comment]
I've tried to at least have an initial development environment based on canary code of next. I can't even finish install: gyp for node-sass fails.
This could be some sort of hint for the team, maybe gyp fails somewhere during optimization dependencies

**Comment by artecoop** [comment]
Tried this morning with freshly released node 16.2.0 and nothing changed

**Comment by timneutkens** [comment]
This seems related to Node.js 16 being the first version compiled for M1 ARM. As a temporary workaround you can use the steps provided here: https://github.com/nvm-sh/nvm#macos-troubleshooting

```
nvm uninstall 16
arch -x86_64 zsh
nvm install 16
exit
```

Then you'll have the x64 version of Node installed instead of the ARM version.

**Comment by karlhorky** [comment]
Maybe a good time to re-introduce `sharp` as an alternative Image loader as @rauchg mentioned: https://twitter.com/rauchg/status/1376654853963845638

Then it would also allow a way out of the performance decreases too: https://github.com/vercel/next.js/issues/23637

**Comment by ItzaMi** [comment]
So, I was following the NextJS tutorial and just came across this issue. I had this `error` on two occasions, both when I added a new dependency.
At first I thought it was something related with `npm` so I deleted `node_modules` and used `yarn` and it solved the issue but now that doesn't work.

I'm sure this isn't helpful at all but it's my input.

Using:
**NextJS** 10.2.3
**Node** 16.2.0
**macOS** 11.2.3
**Device** MacBook Pro (13-inch, M1, 2020)

**Comment by ViktorYermak** [comment]
I confirm. Downgrading from **v16.3.0** to LTS version node **v14.17.0** solved the issue.

System:
MacOS Big Sur 11.4
Apple M1

node -v
v14.17.0

node -p "process.arch"
arm64

**Comment by fers4t** [comment]
Next 10.2.3 does not working with NodeJS v15.14.0 too. I'll give a chance 14.17.0.

**Comment by RajceP** [comment]
Seems to be working with Next.js 11!

**Comment by verekia** [comment]
Crashing in Next `11.0.0` as well :)

Apple M1
MacOS: `11.2.3 (20D91)`
Node: `v16.1.0`
`arm64`

**Comment by artecoop** [comment]
Can confirm that is still crashing with next 11.0.0

**Comment by deybyr647** [comment]
I'm still getting "SIGSEGV" crashes, even with NextJS `v11` :/

Can't wait for the team to find a fix though :)

Macbook Air (M1, 2020)
MacOS: `11.4 (20F71)`
Node: `v16.2.0 arm64`

**Comment by trm217** [comment]
> 
> 
> I'm still getting "SIGSEGV" crashes, even with NextJS `v11` :/
> 
> Can't wait for the team to find a fix though :)
> 
> Macbook Air (M1, 2020)
> MacOS: `11.4 (20F71)`
> Node: `v16.3.0 arm64`

I am almost certain that the problem has to do with the image optimization library. I highly doubt that it has anything to do with Nextjs it's self.

**Comment by artecoop** [comment]
@trm217 yes, the problem seems to be with squoosh library, not the `next/image` component itself.

**Comment by deybyr647** [comment]
@trm217  @artecoop 
> I am almost certain that the problem has to do with the image optimization library. I highly doubt that it has anything to do with Nextjs it's self.

Yeah, that would make sense. I decided to run `next dev` through npm instead of yarn, and after the 2nd run, every image on my project loaded just fine. Weird...

**Comment by trm217** [comment]
I managed to reproduce the segmentation fault using Nod 16 (ARM build) and squoosh inside a simple Node script.
I'll create an issue on the squoosh repository and link this issue.

**Comment by kamil1800Battery** [comment]
I am working on a next site using image components which causes my server to crash on render

 running node 12 installed using homebrew
 m1 silicon mac 
 
 upon render instantly met with this error 
 
 
![Screen Shot 2021-06-18 at 10 33 53 AM](https://user-images.githubusercontent.com/80780220/122597902-eab20c00-d020-11eb-989b-06dd33680080.png)

**Comment by saeed-jalilian** [comment]
if you add unoptimized attribute like i say in below, bug should be solved.
<Image src={someImage} unoptimized={true} width={1000} height={1000}/>
i'm using macbook air m1 and node 16.3 and next.js 11.0.0

**Comment by trm217** [comment]
> if you add unoptimized attribute like i say in below, bug should be solved.
> 
> `<Image src={someImage} unoptimized={true} width={1000} height={1000}/>`
> 
> i'm using macbook air m1 and node 16.3 and next.js 11.0.0

Well this eliminates the whole point of `next/image` though. Only viable option at the moment is to downgrade node :(

**Comment by saeed-jalilian** [comment]
> > if you add unoptimized attribute like i say in below, bug should be solved.
> > `<Image src={someImage} unoptimized={true} width={1000} height={1000}/>`
> > i'm using macbook air m1 and node 16.3 and next.js 11.0.0
> 
> Well this eliminates the whole point of `next/image` though. The only viable option at the moment is to downgrade node :(

well i have to mention this problem only happens when you are developing the app, you can set unoptimized={true} for developing and when you want to deploy your app, remove this attribute.

**Comment by trm217** [comment]
> > > if you add unoptimized attribute like i say in below, bug should be solved.
> 
> > > `<Image src={someImage} unoptimized={true} width={1000} height={1000}/>`
> 
> > > i'm using macbook air m1 and node 16.3 and next.js 11.0.0
> 
> > 
> 
> > Well this eliminates the whole point of `next/image` though. The only viable option at the moment is to downgrade node :(
> 
> 
> 
> well i have to mention this problem only happens when you are developing the app, you can set unoptimized={true} for developing and when you want to deploy your app, remove this attribute.

If you run the app in production with the same system it will crash non the less.

**Comment by verekia** [comment]
It's easier to remove all `unoptimized={true}` (or `unoptimized={IS_DEV}`) when this issue will be fixed than replacing all `img` by `Image`, since `Image` is not a drop-in replacement of `img` and may require some layout tweaks. Thanks @saeed-jalilian for the temporary solution.

**Comment by altmshfkgudtjr** [comment]
It runs fine with Next.js version 11.0.1!
:)

Macbook Air (M1, 2021)
Mac OS: 11.4(20F71)
Node.js :v16.2.0 arm64

**Comment by verekia** [comment]
> It runs fine with Next.js version 11.0.1! :)
> 
> Macbook Air (M1, 2021)
> Mac OS: 11.4(20F71)
> Node.js :v16.2.0 arm64

That might be a false positive. For me, it sometimes work, sometimes crashes. In some places or my site, Image works, in some others it segfaults. Not sure what the conditions are exactly.

**Comment by artecoop** [comment]
> > It runs fine with Next.js version 11.0.1! :)
> > Macbook Air (M1, 2021)
> > Mac OS: 11.4(20F71)
> > Node.js :v16.2.0 arm64
> 
> That might be a false positive. For me, it sometimes work, sometimes crashes. In some places of my site, Image works, in some others it segfaults. Not sure what the conditions are exactly.

Not for me either. I highly doubt that the Next team will change the optimization engine in a patch release.

**Comment by trm217** [comment]
> > > It runs fine with Next.js version 11.0.1! :)
> 
> > > Macbook Air (M1, 2021)
> 
> > > Mac OS: 11.4(20F71)
> 
> > > Node.js :v16.2.0 arm64
> 
> > 
> 
> > That might be a false positive. For me, it sometimes work, sometimes crashes. In some places of my site, Image works, in some others it segfaults. Not sure what the conditions are exactly.
> 
> 
> 
> Not for me either. I highly doubt that the Next team will change the optimization engine in a patch release.

Also it's very unfortunately that the issue I created on the squoosh lib is not given any attention. Would go about debugging myself, but working with wasm and their codebase is next to impossible for me.

**Comment by verekia** [comment]
To anyone experiencing this problem, please go upvote his issue here to help get it fixed faster:

https://github.com/GoogleChromeLabs/squoosh/issues/1056

**Comment by davidossahdez** [comment]
This bug was reported 2 months ago and we aren't even close to properly identify what is causing it. So before you keep pulling your hair out over this while developing Next.js projects on M1 Apple Silicon, use this workaround:

`<Image src={src} alt={alt} ... unoptimized={process.env.NODE_ENV === 'development'} />`

Simply use the `Image` component as usual and add the `unoptimized` attribute to disable the optimizations on your development environment. Deploying to Vercel or any other server works as expected due to the servers using regular x86_64 binaries of Node and the other dependencies. (The problem are the ARM based binaries)

You get optimized images in production, raw images while developing and avoid the errors because they happen during the optimizations.  Everyone happy while we wait for this bug's fix.

**Comment by saeed-jalilian** [comment]
> This bug was reported 2 months ago and we aren't even close to properly identify what is causing it. So before you keep pulling your hair out over this while developing Next.js projects on M1 Apple Silicon, use this workaround:
> 
> `<Image src={src} alt={alt} ... unoptimized={process.env.NODE_ENV === 'development'} />`
> 
> Simply use the `Image` component as usual and add the `unoptimized` attribute to disable the optimizations on your development environment. Deploying to Vercel or any other server works as expected due to the servers using regular x86_64 binaries of Node and the other dependencies. (The problem are the ARM based binaries)
> 
> You get optimized images in production, raw images while developing and avoid the errors because they happen during the optimizations. Everyone happy while we wait for this bug's fix.

i totally agree with you, this is the best known solution right now.

**Comment by karlhorky** [comment]
Maybe it can be taken one step further, with detection for the architecture (`arm64`) and platform (`darwin` aka macOS):

```jsx
<Image src={src} alt={alt} ... unoptimized={
  process.env.NODE_ENV === 'development' &&
  process.arch === 'arm64' &&
  process.platform === 'darwin'
} />
```

**Comment by karlhorky** [comment]
I guess since this is a potentially long-running issue, the Next.js team could also consider making this default until the Squoosh bug is fixed.

cc @timneutkens @shuding @surma

**Comment by karlhorky** [comment]
If you can use something like `getServerSideProps`, then you can leave out the complex, fragile browser code, and it becomes a bit nicer:

```
export default function Home(props) {
  return (
    <Image
      src={src}
      alt=""
      unoptimized={
        process.env.NODE_ENV === 'development' && props.isAppleM1
      }
    />
  )
}

export async function getServerSideProps() {
  return {
    props: {
      isAppleM1: process.arch === 'arm64' && process.platform === 'darwin',
    },
  };
}
```

**Comment by trm217** [comment]
@karlhorky I don't see why one would want to add a workaround to the library. The problem has been pointed out plenty of times, it obviously is a problem for many people, so instead of committing a workaround to the library, I believe it would be better if more people just got behind it.
For example, I have pointed out the issue on the squoosh repo, I've seen little to no response to that. Also, I don't quite understand how squoosh is incorporated into Next.js. If you check out the [code](https://github.com/vercel/next.js/tree/canary/packages/next/next-server/server/lib/squoosh), squoosh seems to be copied into Next.js  instead of being added as a dependency. It would surely be helpful if some of the people that have a good knowledge of the codebase could assist us in further narrowing down the issue and sharing the findings with the developers at the squoosh code base.

**Comment by karlhorky** [comment]
First of all, let me say, I agree that it would be best to have this resolved properly as soon as possible! 👍 I would even go so far to say that it would be nice to revert to `sharp` instead of Squoosh, so that the performance problem would also be resolved: #23637

However, this is a known issue since April, and since it's a problem in a third-party low-level dependency with a very specific configuration (maintained by another team), it's possible that it may be around for a while longer.

If that is the case, in the meantime, it may make sense to make the (admittedly not ideal) tradeoff to make sure that the Next.js `Image` component doesn't crash on M1 machines. That's the point I was trying to make above.

**Comment by surma** [comment]
Fwiw NextJS vendors an old version of the Squoosh CLI. The team working on Squoosh is not able to fix these issues in here (some of the issues mentioned have been fixed in Squoosh for a while).

**Comment by ijjk** [comment]
Hi, this has been updated in `v11.0.2-canary.12` of Next.js, please upgrade and give it a try!

**Comment by karlhorky** [comment]
Wow, investigated all the way up to v8, good job @ijjk @styfle @surma and anyone else involved! 🙌 🚀

**Comment by RajceP** [comment]
I am experiencing this issue with `11.0.2-canary.13`.

**Comment by verekia** [comment]
I also got some `SIGSEGV` crashes on `11.0.2-canary.13`. I _think_ it happened on hot reload. It is more stable that before though.

**Comment by artecoop** [comment]
I have tried `11.0.2-canary.13` too: now it work on startup, sometimes work after hot reload or browser refresh, but the bug is definitely still here. 
This is promising tho, is a step forward the solution and we're still in canary! 
Again, issue closed too soon.

**Comment by styfle** [comment]
This is fixed in [Node.js 16.5.0](https://github.com/nodejs/node/releases/tag/v16.5.0)

**Comment by karlhorky** [comment]
Homebrew tracking issue, in case you use that: https://github.com/Homebrew/homebrew-core/pull/81245

**Comment by RajceP** [comment]
I can confirm it's fixed with Node v16.5.0 (Next.js v 11.0.1).

**Comment by artecoop** [comment]
Yes! Can confirm that 16.5.0 fix the problem. I'll close this issue as is resolved

**Comment by sarazeaiter1** [comment]
worked with node v14.17.0

**Comment by surma** [comment]
@sarazeaiter1 There is no native version of Node 14 for M1, so you are running x86 emulated via Rosetta :) (But yes, that one should work just fine as well). IIRC, Node 16 is the first version with native M1 support.

**Comment by fernando-nog** [comment]
This problema was fixed using node version -> v16.5.0 or above on Mac M1.
just use: `nvm install v16.5.0 `

**Comment by arcataroger** [comment]
This still causes a crash with node v17.0.1 :(

**Comment by styfle** [comment]
Please create a new issue with steps to reproduce

**Comment by kirillzakharov** [comment]
Can confirm still happening on my end. M1 Mac, running node `16.5.0` with Next `12`.

**Comment by balazsorban44** [comment]
@kirillzakharov https://github.com/vercel/next.js/issues/24421#issuecomment-963420182
