### ISSUE TITLE
Unintended page refresh with webpack5

### ISSUE THREAD

**Issue by j-jiseophan** [vercel/next.js#25434]
### What version of Next.js are you using?

10.2.0

### What version of Node.js are you using?

12.14.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS 11.2.3

### How are you deploying your application?

debug mode(next dev)

### Describe the Bug

When I turn on webpack5 and call internal api(/api/*) from page after first render, the page refreshes and logs `Refreshing page data due to server-side change`.  after refreshing once, it works fine as webpack4. 

### Expected Behavior

The page should not refresh on api call after first render.

### To Reproduce

```tsx
// News.tsx

const News = () => {
  const { data } = useSWR("/api/!@#$", async ( ) => {
    const res = await fetch('/api/!@#$');
    const json = await res.json();
    return json;
  });

  //   ..
}

```

```ts
// /api/!@#$/index.ts

const requestHandler: RequestHandler = async (req, res) => {
  const cacheManager = getCacheManager();
  switch (req.method) {
    case "GET": {
      const cache = cacheManager.get(cacheKey);
      if (cache) {
        return res.status(200).json({ data: cache });
      }

      try {
        const { data } = await NewsApi.get<Post[]>("/posts"); // wordpress rest api
        cacheManager.set(cacheKey, data, 60 * 15);
        return res.status(200).json({ data });
      } catch (e) {
        return res.status(500).end();
      }
    }
    default:
      return res.status(404).end();
  }
};

export default requestHandler
```

```js
// next.config.js
module.exports = {
  future: {
    webpack5: true,
  },
}
``

**Comment by feross** [comment]
We're seeing this behavior as well. If you enable "Preserve log" in the Chrome DevTools, then you'll see the following printed when this happens:

```
Refreshing page data due to server-side change
```

And in Terminal, you'll see:

```
wait  - compiling...
```

**Comment by sMteX** [comment]
I'm seeing something similar - a _TON_ of fast refresh rebuilding or refreshing page data due to server-side change (despite me not touching keyboard, let alone the code), which leads to very annoying refreshes or redirects to `/`. This was not the case prior to our latest upgrade (we were running on Next 9.5.5 IIRC).

**Comment by feross** [comment]
The issue is present in `10.2.3` and goes away when downgrading to `10.2.0`. We've locked to version `10.2.0` until this issue is fixed.

**Comment by j-jiseophan** [comment]
> The issue is present in `10.2.3` and goes away when downgrading to `10.2.0`. We've locked to version `10.2.0` until this issue is fixed.

As I wrote in the description above, I'm having the issue in `10.2.0`

**Comment by ijjk** [comment]
Hi, we're not able to reproduce this with the above provided information please provide a repo with a minimal reproduction and steps to be reproduce to allow us to investigate this quicker!

@j-jiseophan note if the `!@#$` value wasn't a placeholder then in the initial reproduction you are fetching an API route `!@#$` and the hash `#` gets treated literally in the `fetch` causing `#$` to not be sent to the server so it 404s, this behavior isn't controlled by Next.js as it's fetch's behavior so doesn't seem related to the page refreshing.

**Comment by message** [comment]
Same. I get a ton of refreshes on a page even though i'm not changing anything. Glad that i'm not alone. 

I narrowed it down to `10.2.1-canary.9`. Not happening in `10.2.1-canary.8`. @ijjk let me know if I can help you with some debugging information.

**Comment by j-jiseophan** [comment]
@ijjk 

I failed to create a new project that reproduces error. So the reproduction steps in the description may not be helpful to reproduce the error.
+) To clarify, the `!@#$ ` means just some path stirng, not a path with `#`

**Comment by ijjk** [comment]
Hi, I think we tracked this down to https://github.com/vercel/next.js/pull/25735 can you please update to `v10.2.4-canary.3` and see if you are still seeing the unexpected page reloading with webpack 5?

**Comment by j-jiseophan** [comment]
@ijjk To me, the problem is solved in v10.2.4-canary.3.

**Comment by message** [comment]
@ijjk yeap, seems to be fixed. Thank you :heart:

**Comment by ijjk** [comment]
Going to close this per the above comments as it seems to be resolved on the latest canary

**Comment by tunesmith** [comment]
Looks like `v10.2.4-canary.3` is affected by https://github.com/vercel/next.js/issues/26163, which isn't fixed until `v11.0.1-canary.2`.

**Comment by Hemanth-M-K** [comment]
I was using Next 11 and configured webpack5 to true in next configure. after next 12 release i upgraded to next 12 but facing same unintended page refresh when I trigger the next api

**Comment by hughriegelwt** [comment]
> I was using Next 11 and configured webpack5 to true in next configure. after next 12 release i upgraded to next 12 but facing same unintended page refresh when I trigger the next api

We are experiencing the same page refresh problem where a page refresh occurs when an API is called.
