### ISSUE TITLE
Scroll restoration happens too early before the page gets rendered after hitting browser back button

### ISSUE THREAD

**Issue by liweinan0423** [vercel/next.js#3303]
- [x] I have searched the [issues](https://github.com/zeit/next.js/issues) of this repository and believe that this is not a duplicate.

After transiting from one page to another page via next `<Link />`, if user clicks the back button and the previous page has `getInitialProps` method that takes some time to finish, the scroll position of the previous will be restored before the previous pages gets rendered.

## Demo 
source code can be found [here](https://github.com/liweinan0423/nextjs-scroll-restoration-issue)
![out](https://user-images.githubusercontent.com/646159/32951715-ed75a7e6-cbe5-11e7-9d08-a9747a48329d.gif)

After clicking back button, the "go back" text should still be visible (not scroll down to previous position) until the previous page gets rendered

**Comment by pablopunk** [comment]
This seems to happen because next's router (and `<Link />`) uses `window.history.pushState` and then `window.history.back` restores the scroll. This doesn't happen with common `<a   />` because it doesn't use `pushState`.

[This is an interesting article](https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration) about how scroll restoration works on each browser. Basically you can disable it and manage the scroll on your own:

```js
history.scrollRestoration = 'manual'
```

**Comment by liweinan0423** [comment]
Thanks for you explanation. 

Using a plain `<a />` tag would cause a full page reload, which is not what I expected. I expect the back button would either not trigger the `getInitialProps` method or don’t restore scroll until the `getInitialProps` is finished

**Comment by pablopunk** [comment]
Yeah, I understand. I'm not sure what the solution would be from within *next*.

**Comment by pablopunk** [comment]
@liweinan0423 I'm not sure but [this](https://github.com/scaleapi/data-prefetch-link) could be a workaround

**Comment by raffij** [comment]
We've come across this too and it feels like something next should be doing internally. Otherwise everyone needs to write their own code to store scrollpositions and then scroll on completion of getInitialProps.

**Comment by mgiraldo** [comment]
we're having a related issue where, upon clicking a link from a scrolled-down position (say, result 20 in a list) the new page shows up halfway down so the user needs to scroll up to see the item itself.

**Comment by mgiraldo** [comment]
here's an example screen capture of the issue we're having:

![scroll](https://user-images.githubusercontent.com/133020/37115722-eed3c552-2219-11e8-98b8-b214bcd2f281.gif)

**Comment by jlei523** [comment]
We're also running into this issue and it makes the user experience very frustrating to use. @arunoda Any thoughts or way to fix this?

**Comment by spencersmb** [comment]
I was having this same issue as @mgiraldo awhile back and I originally was just using router.push(), but as soon as I switched to using the <Link> tag, my problem resolved itself with out needing to implement a hack like scroll-to-top in component did mount or something ghetto like that. Curious if you are using a Link tag at all?

**Comment by mgiraldo** [comment]
it is a regular `<Link />` see: https://github.com/dpla/dpla-frontend/blob/master/components/ExhibitionsComponents/AllExhibitions/components/ExhibitionsList/index.js#L8-L18

but we ended up using `componentDidMount` with `window.scrollTo` in the destination page: https://github.com/dpla/dpla-frontend/blob/master/pages/exhibitions/exhibition/index.js#L25-L27

feels very hacky, though... and we have the Back button issue mentioned in the issue in other parts of the site. 

you can see the problem in action here: https://dp.la/exhibitions (scroll down and click)... the patch will be up tomorrow

**Comment by mgiraldo** [comment]
you can see the patched version here: https://beta-staging.dp.la/exhibitions

**Comment by jlei523** [comment]
@mgiraldo I see a slight flash when using the back button. We're running into the same issue.

**Comment by spencersmb** [comment]
@mgiraldo In another part of my site I forgot I did this:

`Router.push("/account")`
 `window.scrollTo(0, 0)`
 `document.body.focus()`

which works when navigating TO a page, but like you said when you hit the back button, its at the top of the window because I think the window recorded that in its history....
What are you doing to mitigate that back button issue?

**Comment by jlei523** [comment]
@spencersmb What do you mean switch to using the tag? What tag is that?

**Comment by arunoda** [comment]
We've a similar issues reported here: https://spectrum.chat/thread/3d65b436-b085-4eef-ad84-0941c473e09d

Next.js doesn't hijack scrolling. But this is a real issue. Here's what's happening.
This is because of browser's default scrolling behavior. See: https://github.com/zeit/next.js/issues/3303#issuecomment-354225323

When you go back, browser tries to go to the previous scroll position for better UX. But in the ^^ case, the data is not loaded yet. But the data will be there in a bit with the latency of `getInitialProps()`.  When the data rendered, it's not the correct position as before.

So, in order fix this you can do a few things:

* Cache the data locally and render the page from that cache. You can even update the data in behind the scene. In this case data will be there as the user hit the back button.
* Control scrolling manually via `Router.push()`. (This will return a promise and it'll get resolved when the page is rendered)

We've no plan to manage scrolling inside Next.js yet. But you can do it in the userland and publish a new Link component like `LinkBetterScrolling`.

**Comment by developer239** [comment]
I mean every time a javascript library gets popular and people start using it in production ... some majors issues show up and the official response is: "_Fix it yourself._" 😢 

I fail to understand how does `Router.push()` fix an issue when pressing `button back` in a browser.

@mgiraldo Posted a link to a patched version of his website.

1) Go here: https://beta-staging.dp.la/exhibitions 
2) Scroll to the bottom
3) Click on `activism in the US`
4) Click on `button back` in your browser or just swipe back

There are two **major** issues:
1) Before the list gets rendered. Item detail scrolls to the bottom for no reason.
2) When the list gets rendered you are not at the bottom of the screen but somewhere in the middle.

I believe it would be nice to _at least consider fixing this issue in the future_.

**Comment by jlei523** [comment]
@developer239 We have the exact same issue with our Next.js app as documented here: https://spectrum.chat/thread/3d65b436-b085-4eef-ad84-0941c473e09d

It completely kills the user experience.

@arunoda Could you explain why the Next team isn't considering an official fix to this issue? It seems like it's a breaking bug that completely ruins the user experience. Moving back to the previous scroll position **is** a basic web browser behavior.

**Comment by mgiraldo** [comment]
if i understand correctly the back button/scroll position functionality is a native browser behavior that assumes a standard page refresh (user goes from url x to url y via a standard http request). what client-side javascript-based frameworks do is implement a page transition without making use of the native browser behavior (via `pushState` or similar). the browser is counting on itself having a cached version of the page to return you to, but it doesn't (it has an incomplete version that is completed by the framework after the jump is made). however, if your app is not fast enough to produce page transitions/content using the framework (in either direction, backwards or forward), you will get this jarring, second-rate experience. what i think the nextjs team is saying is the effort of implementing a cross-browser solution to this problem is beyond the scope they are willing to take on.

**Comment by developer239** [comment]
@mgiraldo Yes but `Router.push` does not solve the issue for me. I understand that this one might be hard to fix but it is a major issue. The example that @liweinan0423 provided could not be simpler. There are no images, not text, nothing. And still, the `Link` component does not work properly.

**Comment by MisterKort** [comment]
I think if a next.js team provides its own routing management they should care about similar critical issues as well. For example react-router doesn't have this issue and they don't think that is should be implemented by another developer themselves.
Definitely this should be fixed because it makes the user experience very frustrating and confusing.

**Comment by vitaliy-webmaster** [comment]
I came across mentioned issue while building my portfolio site and I think this is really a big breaking thing in user experience overall. 
I can confirm that problem occurs when the page to go back has more height than the current page. And (IMHO) this has nothing to do with getInitialProps as was stated in official next team response. I get similar bad result with or without using getInitialProps . More likely it happens because scroll restoration occurs before route change but not after it. Try to set simple page transitions and you'll see that scroll height jumps instantly despite the content of current page is still there.
In my case I found temporary solution. This involves setting the height of <html> tag to a very high value (like 15000px) on onRouteChangeStart event, and restoring its original height in 2 seconds after onRouteChangeComplete. This works for me and hope it will help someone until we get official fix. Good luck.

**Comment by hardwit** [comment]
My solution for restoring scroll position when the browser **back button** clicked:

**_app.js**
```
componentDidMount() {
    const cachedPageHeight = []
    const html = document.querySelector('html')

    Router.events.on('routeChangeStart', () => {
      cachedPageHeight.push(document.documentElement.offsetHeight)

      this.setState({ routeChanging: true })
    })

    Router.events.on('routeChangeComplete', () => {
      html.style.height = 'initial'

      this.setState({ routeChanging: false })
    })

    Router.beforePopState(() => {
      html.style.height = `${cachedPageHeight.pop()}px`

      return true
    })
}
```

**Comment by vitaliy-webmaster** [comment]
@hardwit well done!
however it works for me only if I restore height asynchronously like this:

`Router.events.on("routeChangeComplete", () => {
			setTimeout(() => {
				html.style.height = 'initial'
			}, 1500);
		});`

**Comment by malthemilthers** [comment]
> My solution for restoring scroll position when the browser **back button** clicked:
> 
> **_app.js**
> 
> ```
> componentDidMount() {
>     const cachedPageHeight = []
>     const html = document.querySelector('html')
> 
>     Router.events.on('routeChangeStart', () => {
>       cachedPageHeight.push(document.documentElement.offsetHeight)
>     })
> 
>     Router.events.on('routeChangeComplete', () => {
>       html.style.height = 'initial'
>     })
> 
>     Router.beforePopState(() => {
>       html.style.height = `${cachedPageHeight.pop()}px`
> 
>       return true
>     })
> }
> ```

Where does Router come from?

**Comment by daniel-primea** [comment]
This worked for me:

```  
  componentDidMount() {
    window.history.scrollRestoration = "manual";

    const cachedScroll = [];

    Router.events.on("routeChangeStart", () => {
      cachedScroll.push([window.scrollX, window.scrollY]);
    });

    Router.beforePopState(() => {
      const [x, y] = cachedScroll.pop();
      setTimeout(() => {
        window.scrollTo(x, y);
      }, 100);

      return true;
    });
  }
```

**Comment by bnhovde** [comment]
For me, the above didn't work. I'm not sure if it was related to the fixed timeout, but `beforePopState` didn't trigger at the scroll at the right time.

What I ended up with was storing a potential scroll and then triggering it in `onRouteChangeComplete`.

```
  componentDidMount() {
    window.history.scrollRestoration = "manual";
    const cachedScrollPositions = [];
    let shouldScrollRestore = false;

    Router.events.on("routeChangeStart", () => {
      cachedScrollPositions.push([window.scrollX, window.scrollY]);
    });

    Router.events.on("routeChangeComplete", () => {
      if (shouldScrollRestore) {
        const { x, y } = shouldScrollRestore;
        window.scrollTo(x, y);
        shouldScrollRestore = false;
      }
    });

    Router.beforePopState(() => {
      const [x, y] = cachedScroll.pop();
      shouldScrollRestore = { x, y };

      return true;
    });
  }
```

**Comment by NickMurr** [comment]
I found some issues with `window.history.scrollRestoration = "manual"` on moving through few pages and then when we returning back and reloading page - it's jumping through the top to previous location.

So i found solution to swithing `window.history.scrollRestoration` on different window lifeCycles:

**_app.tsx**

`  componentDidMount() {
    window.history.scrollRestoration = 'auto';
    const cachedScrollPositions: any[] = [];
    let shouldScrollRestore: any;

    Router.events.on('routeChangeStart', () => {
      cachedScrollPositions.push([window.scrollX, window.scrollY]);
    });

    Router.events.on('routeChangeComplete', () => {
      if (shouldScrollRestore) {
        const { x, y } = shouldScrollRestore;
        window.scrollTo(x, y);
        shouldScrollRestore = null;
      }
      window.history.scrollRestoration = 'auto';
    });

    Router.beforePopState(() => {
      if (cachedScrollPositions.length > 0) {
        const [x, y] = cachedScrollPositions.pop();
        shouldScrollRestore = { x, y };
      }
      window.history.scrollRestoration = 'manual';
      return true;
    });
  }`

**Comment by jlei523** [comment]
I'm curious why people are still trying to manually scroll Next.js pages. @arunoda gave a clear explanation of the problem here: https://github.com/zeit/next.js/issues/3303#issuecomment-376804494

It's because getInitialProps runs even when someone clicks on the browser back button. This means it'll try to grab fresh data. But the browser expects the data to be there already. Just cache any remote data from getInitialProps in the client and the problem should go away. I gave an example here: https://levelup.gitconnected.com/6-tips-using-next-js-for-your-next-web-app-e3f056fa46

**Comment by pavlo-vasylkivskyi-scx** [comment]
I added this code and it works perfect for me
`componentDidMount() {
    if ('scrollRestoration' in window.history) {
      window.history.scrollRestoration = 'manual';
      const cachedScrollPositions = [];
      let shouldScrollRestore;

      Router.events.on('routeChangeStart', () => {
        cachedScrollPositions.push([window.scrollX, window.scrollY]);
      });

      Router.events.on('routeChangeComplete', () => {
        if (shouldScrollRestore) {
          const { x, y } = shouldScrollRestore;
          window.scrollTo(x, y);
          shouldScrollRestore = false;
        }
      });

      Router.beforePopState(() => {
        const [x, y] = cachedScrollPositions.pop();
        shouldScrollRestore = { x, y };

        return true;
      });
    }
  }`

**Comment by vitalyliber** [comment]
@pavlo-vasylkivskyi-scx thank you!

I little bit changed your code for using with functional component.

```javascript
import Router from 'next/router'

let cachedScrollPositions = [];

const Home = props => {
  useEffect(() => {
    if ('scrollRestoration' in window.history) {
      window.history.scrollRestoration = 'manual';
      let shouldScrollRestore;

      Router.events.on('routeChangeStart', () => {
        cachedScrollPositions.push([window.scrollX, window.scrollY]);
      });

      Router.events.on('routeChangeComplete', () => {
        if (shouldScrollRestore) {
          const { x, y } = shouldScrollRestore;
          window.scrollTo(x, y);
          shouldScrollRestore = false;
        }
      });

      Router.beforePopState(() => {
        const [x, y] = cachedScrollPositions.pop();
        shouldScrollRestore = { x, y };

        return true;
      });
    }
  }, []);

  return (...long list of elements with links)
}
```

**Comment by kimnagui** [comment]
@pavlo-vasylkivskyi-scx  Thank you!

But an error occurred when I refreshed the page and click browser back button.

`TypeError: Invalid attempt to destructure none-iterable instance`

so I changed your code.

```js
componentDidMount() {
    if ("scrollRestoration" in window.history) {
        window.history.scrollRestoration = "manual";
        const cachedScrollPositions: Array<any> = [];
        let shouldScrollRestore;

        Router.events.on("routeChangeStart", () => {
            cachedScrollPositions.push([window.scrollX, window.scrollY]);
        });

        Router.events.on("routeChangeComplete", () => {
            if (shouldScrollRestore) {
                const { x, y } = shouldScrollRestore;
                window.scrollTo(x, y);
                shouldScrollRestore = false;
            }
        });

        Router.beforePopState(() => {
            if (cachedScrollPositions.length > 0) {  // <---- Add this !
                const [x, y] = cachedScrollPositions.pop();
                shouldScrollRestore = { x, y };
            }
            return true;
        });
    }
}
```

**Comment by feluxe** [comment]
I've been working for a whole week to find a reliable solution to this problem. I couldn't fine one which:

1) works reliably with both Firefox and Chrome.
2) works reliably using both the back-button and the forward-button across your website.
3) works reliably when you hit the back-/forward-button coming from an external website.
4) works reliably even if you hit the refresh button on one of your pages during the session.
5) works reliably even if you hammer the back-button or the forward-button multiple times.

I tried various approaches which I found across the web. I tried with different approaches of my own. Not a single one worked reliably. The approach which took me the farthest was one which used `scrollRestoration = 'manual'` and `sessionStorage` to keep track of the position history. It worked flawlessly except for `3.`.

I'm wondering, has anyone found a solution which works for all items from the list above?

**Comment by schmidsi** [comment]
I had this requirement too on an actual project and I came up with the following solution:

https://gist.github.com/schmidsi/2719fef211df9160a43808d505e30b4e

It does not address all points from @feluxe, but it works pretty well for us. Maybe this can help someone as a boilerplate for their own solution.

**Comment by claus** [comment]
Here's my take:

https://gist.github.com/claus/992a5596d6532ac91b24abe24e10ae81

It should satisfy all of @feluxe's [requirements](https://github.com/zeit/next.js/issues/3303#issuecomment-597810586) and behave like native scrollRestoration, although i haven't tested it too much yet. I ran it through Chrome, Firefox and Safari and it worked fine. YMMV if you do out of the ordinary stuff with the router. One caveat is that sometimes scrollTo seems to come a tiny bit too late so you see the top of the page flash for a frame or so.

**Comment by alekslario** [comment]
Caching helped with getInitialProps, since it run client side. Now with getServerSideProps the issue is back.

**Comment by onderonur** [comment]
> Caching helped with getInitialProps, since it run client side. Now with getServerSideProps the issue is back.

Yep, when I use `getServerSideProps`, scroll restoration happens and after that the page gets rendered.

**Comment by callumbooth** [comment]
Im seeing this issue too with getServerSideProps, the scroll restoration happens too early

**Comment by wddwycc** [comment]
@Timer 

I think we need more notice on this issue, `getServerSideProps` would cause scroll restoration happens too early.  
The flikering causes very bad user experience, especially on mobile platform.

**Comment by OnurErtugral** [comment]
I came across the same issue today. It is really frustrating that Next.js doesn't have a baked in solution for this problem.

@hardwit's solution works for me.

**Comment by atirudom** [comment]
This is a UX killer that many developers didn't notice. 
Yes, there should be more notice on this issue for all Next.js users or atleast attach this thread in the common issues so people know the solutions in advance.

Thanks @hardwit for starting all the solutions and it solves for me now.

**Comment by igormartimiano** [comment]
Also came across this problem, thank you everyone for the possible solutions.
This definitely should be officially addressed, huge impact in UX and may even be a necessity for a lot of use cases.

**Comment by meotimdihia** [comment]
Tested all scripts in this issue and always get problems. 
I am trying to use this module and it works well for now:
https://github.com/moxystudio/next-router-scroll

**Comment by Timer** [comment]
This behavior has been fixed on Next.js 10.0.5+.

**Comment by wddwycc** [comment]
@Timer tried upgrade to 10.0.5, the problem is still there.

**Comment by meotimdihia** [comment]
I just tested with 10.0.5. Scroll restoration still random, even if it works, the position is not the same as the last position.

**Comment by JinDevT** [comment]
Has anyone solved this problem? Applying @claus code causes the same problem.

**Comment by ynsfasttoday** [comment]
It has already been implemented here. https://demo.vercel.store/ why is it so hard to provide a solution. Here there is no use of module exports but the results is as desired by us.


I guess problem persists even if we use scroll={false}, it just scrolls back to random position above expected position. Using Tim's module export in next config for scroll restoration same as above.

**Comment by PixeledCode** [comment]
> It has already been implemented here. https://demo.vercel.store/ why is it so hard to provide a solution.
> This moxystudio guy is the best
> https://github.com/moxystudio/next-router-scroll

I tried this package but found some issues, can you share any repo where you might have used this package and it worked?

**Comment by meotimdihia** [comment]
I used next-router-scroll on the site: https://animek.fun/

**Comment by PixeledCode** [comment]
> I used `next-router-scroll` on the site: https://animek.fun/

great site, I just bookmarked it lol. can you share the part of code where you used the the package?

**Comment by meotimdihia** [comment]
I can't share code but I used use it with disableNextLinkScroll option: 
```javascript
              <RouterScrollProvider disableNextLinkScroll={false}>
                <Layout>
                  <Component {...pageProps} />
                </Layout>
              </RouterScrollProvider>
```

**Comment by Edjevw12** [comment]
I'm using getServerSideProps, none of the above solutions works for my case :( Anyone got it working with getServerSideProps?

**Comment by meotimdihia** [comment]
`moxystudio/next-router-scroll` not working anymore.

I used the package `react-query`: `https://github.com/tannerlinsley/react-query/issues/1623
I dunno this problem was caused by next or react-query.
```javascript
  const [mounted, setMounted] = useState(false)
  useEffect(() => 
     setMounted(true)
  }, [])

return (
  renderFullScreenHeight() // scroll restoration was stopped at here
  {mounted && renderSomething()}
)
```

when clicking back on the browser, it won't scroll to the `mounted` position.

**Comment by filippofilip95** [comment]
In my case I've fixed it with enabling experimental scroll-restoration by changing `next.config.js` to

```javascript
module.exports = {
  experimental: {
    scrollRestoration: true
  }
}
```

It's mentioned also here https://github.com/vercel/next.js/pull/22727#issuecomment-803276977

**Comment by satoyan** [comment]
To  set true to scrollRestoration worked well with Safari, but did not work with Chrome (in iOS). :cry:

**Comment by micksabox** [comment]
as @filippofilip95 mentioned, changing the `next.config.js` to include the `scrollRestoration` expermental flag solved my issue on iOS 14.4.

**Comment by ndimatteo** [comment]
@claus I'm using your solution in conjunction with a page transition approach (with framer motion), and I'm noticing that **exclusively on iOS Chrome, sporadically during history changes that the new scroll position gets applied immediately**. It seems like Next's `routeChangeComplete` event is firing too early on history changes, my `setTimeout` isn't being respected, or something else is going on.

I'm not sure why this is only happening on history changes with iOS Chrome. Has anyone else experienced this?

> Here's my take:
> 
> https://gist.github.com/claus/992a5596d6532ac91b24abe24e10ae81
> 
> It should satisfy all of @feluxe's [requirements](https://github.com/zeit/next.js/issues/3303#issuecomment-597810586) and behave like native scrollRestoration, although i haven't tested it too much yet. I ran it through Chrome, Firefox and Safari and it worked fine. YMMV if you do out of the ordinary stuff with the router. One caveat is that sometimes scrollTo seems to come a tiny bit too late so you see the top of the page flash for a frame or so.

**Comment by claus** [comment]
@ndimatteo In a current project i also ran into something like that (consistently in all browsers though). Something is setting scroll position immediately on click on a `Link`, even though i do the `{scroll: false}` thing. Weird thing is that this happens only when i'm scrolled down far enough, and it sets the position to something seemingly random (not really random, but also nothing that would make sense to me). I tried to figure out what exactly it is that's setting scroll position but i didn't find anything. Pretty sure it isn't my code (scroll restoration only kicks in much later), and it's not a layout shift. This is driving me nuts.

**Comment by lmf-git** [comment]
I'm my project, sometimes I can't even scroll down after changing page in development... if it was a production issue I'd switch framework.

**Comment by adrienpicard** [comment]
Facing the same issue on a project where I'd like to have more control over when the scroll restoration is triggered. There's a [hook in Nuxt](https://nuxtjs.org/docs/configuration-glossary/configuration-router/#scrollbehavior) allowing this, perhaps something similar could be implemented in Next?

**Comment by veasna-ung** [comment]
Hi ! It seems to still not work on [nextjs.org](https://nextjs.org/) with Chrome iOS when I click on footer links.
I also tried with another projects based on Next 12 and got same issues.
Have you any solutions ? 

Tested with Chrome IOS (v.96.0.4664.101) on 15.1 and 14.7. 

https://user-images.githubusercontent.com/63233026/146800065-a3398c1c-5d80-4ad4-98af-a02844e19629.MP4

**Comment by dejesus2010** [comment]
Welp, I just ran into this issue 2 days before I'm scheduled to ship my project... None of the solutions work. Nextjs has been awesome, but this bug really sucks. Any chance this has been looked at recently?

**Comment by abhimanyuPatil** [comment]
> Welp, I just ran into this issue 2 days before I'm scheduled to ship my project... None of the solutions work. Nextjs has been awesome, but this bug really sucks. Any chance this has been looked at recently?

@dejesus2010  Trying to get this solved since last month but still didn't get any solution. 
Any help ?

**Comment by Kipitup** [comment]
I'm having the same issue.  I've added a setTimeout to delay the scroll, but this is obviously not a sustainable solution.

**Comment by reza-akbari** [comment]
next: 12.2.2
chrome: 105

````js
module.exports = {
  experimental: {
    scrollRestoration: true
  }
}
````
this flag triggers `replaceState` on every scroll, it broke the browser back/forward buttons for me.
I ended up doing something like this: (in the `_app.tsx`)
````ts
  const router = useRouter();
  const scrollCache = useRef<Record<string, [number, number]>>({});
  const activeRestorePath = useRef<string>();
  useEffect(() => {
    if (history.scrollRestoration !== "manual") {
      history.scrollRestoration = "manual";
    }
    const getCurrentPath = () => location.pathname + location.search;
    router.beforePopState(() => {
      activeRestorePath.current = getCurrentPath();
      return true;
    });
    const onComplete = () => {
      const scrollPath = activeRestorePath.current;
      if (!scrollPath || !(scrollPath in scrollCache.current)) {
        return;
      }
      activeRestorePath.current = undefined;
      const [scrollX, scrollY] = scrollCache.current[scrollPath];
      window.scrollTo(scrollX, scrollY);
      // sometimes rendering the page can take a bit longer
      const delays = [10, 20, 40, 80, 160];
      const checkAndScroll = () => {
        if (
          (window.scrollX === scrollX && window.scrollY === scrollY) ||
          scrollPath !== getCurrentPath()
        ) {
          return;
        }
        window.scrollTo(scrollX, scrollY);
        const delay = delays.shift();
        if (delay) {
          setTimeout(checkAndScroll, delay);
        }
      };
      setTimeout(checkAndScroll, delays.shift());
    };
    const onScroll = () => {
      scrollCache.current[getCurrentPath()] = [window.scrollX, window.scrollY];
    };
    router.events.on("routeChangeComplete", onComplete);
    window.addEventListener("scroll", onScroll);
    return () => {
      router.events.off("routeChangeComplete", onComplete);
      window.removeEventListener("scroll", onScroll);
    };
  }, []);
````
hope it helps

**Comment by jsvelte** [comment]
> next: 12.2.2 chrome: 105
> 
> ```js
> module.exports = {
>   experimental: {
>     scrollRestoration: true
>   }
> }
> ```
> 
> this flag triggers `replaceState` on every scroll, it broke the browser back/forward buttons for me. I ended up doing something like this: (in the `_app.tsx`)
> 
> ```ts
>   const router = useRouter();
>   const scrollCache = useRef<Record<string, [number, number]>>({});
>   const activeRestorePath = useRef<string>();
>   useEffect(() => {
>     if (history.scrollRestoration !== "manual") {
>       history.scrollRestoration = "manual";
>     }
>     const getCurrentPath = () => location.pathname + location.search;
>     router.beforePopState(() => {
>       activeRestorePath.current = getCurrentPath();
>       return true;
>     });
>     const onComplete = () => {
>       const scrollPath = activeRestorePath.current;
>       if (!scrollPath || !(scrollPath in scrollCache.current)) {
>         return;
>       }
>       activeRestorePath.current = undefined;
>       const [scrollX, scrollY] = scrollCache.current[scrollPath];
>       window.scrollTo(scrollX, scrollY);
>       // sometimes rendering the page can take a bit longer
>       const delays = [10, 20, 40, 80, 160];
>       const checkAndScroll = () => {
>         if (
>           (window.scrollX === scrollX && window.scrollY === scrollY) ||
>           scrollPath !== getCurrentPath()
>         ) {
>           return;
>         }
>         window.scrollTo(scrollX, scrollY);
>         const delay = delays.shift();
>         if (delay) {
>           setTimeout(checkAndScroll, delay);
>         }
>       };
>       setTimeout(checkAndScroll, delays.shift());
>     };
>     const onScroll = () => {
>       scrollCache.current[getCurrentPath()] = [window.scrollX, window.scrollY];
>     };
>     router.events.on("routeChangeComplete", onComplete);
>     window.addEventListener("scroll", onScroll);
>     return () => {
>       router.events.off("routeChangeComplete", onComplete);
>       window.removeEventListener("scroll", onScroll);
>     };
>   }, []);
> ```
> 
> hope it helps

This does not work for me bro!

**Comment by reza-akbari** [comment]
@jsvelte I updated code. after using it for a few days I noticed it doesn't work on IOS safari. I noticed calling `window.scrollTo` with any numbers was setting the `window.scrollX` and `window.scrollY` to exactly those numbers for a short time on safari.
now it's working fine so far. but using setTimeout isn't ideal anyway.

**Comment by MikeDrewitt** [comment]
I'm kinda at my wits end with this one. I'm not sure if I'm just having a configuration issue or what's going on, but surely the intended behavior is not to maintain scroll position when loading a new page?

Is the intended behavior out of the box for `<Link />` to maintain scroll position when loading a new page when clicked with `href` as its only prop?

**Comment by simonhrogers** [comment]
Absolutely mental that this hasn’t been solved in four years! But there you go...

**Comment by zgreen** [comment]
Just noting that this also seems to be an issue with Next's own [`router.back`](https://nextjs.org/docs/api-reference/next/router#routerback).

**Comment by James-Lam** [comment]
It seems that the official documentation has not handled scrolling restoration well.

https://github.com/vercel/next.js/assets/15834794/d2e6c834-d76f-4c64-9ca6-1b9493dcdfa8


https://github.com/vercel/next.js/assets/15834794/09666f67-c35e-4ac5-90ea-5052ce4a8299

**Comment by simonhrogers** [comment]
For anyone working with or without Framer – hopefully this helps as an easy solution. If you aren’t using Framer, you can follow Jakob Chill’s post here:  https://jak-ch-ll.medium.com/next-js-preserve-scroll-history-334cf699802a 

```
import { useEffect, useRef } from 'react'
import { AppProps } from 'next/app'
import { WindowInfoProvider } from '@faceless-ui/window-info'
import { ScrollInfoProvider } from '@faceless-ui/scroll-info'
import { LazyMotion, m, AnimatePresence } from 'framer-motion'
const framerFeatures = () => import("utils/framerFeatures").then(res => res.default)
import { SplashProvider, useSplashContext } from "context/splash"
import { PreviousRouteProvider } from "context/previousRoute"
import Layout from 'components/global/Layout'

import useFouc from 'hooks/useFoucFix'

import 'styles/sanity.css'
import 'styles/scss/main.scss'
import { useRouter } from 'next/router'


export default function App({ Component, pageProps }: AppProps) {

  // Scroll restoration
  // Next.js scroll restoration is not working with framer-motion
  // So we have to do it manually
  // I’ve adapted the kind work of Jakob Chill in order for it to work with framer-motion
  // The original article is here:
  // https://jak-ch-ll.medium.com/next-js-preserve-scroll-history-334cf699802a
  // if you weren’t using framer-motion, you could just use it as-is as a convenient hook
  // if I ever do a blog I’ll write a basic post about this incase anyone has better ideas

  useFouc()

  // Stop the browser from scrolling the exiting page to top before transition 
  useEffect(() => {
    if (history.scrollRestoration !== "manual") {
      history.scrollRestoration = "manual";
    }
  }, [])

  const router = useRouter()
  const scrollPositions = useRef<{ [url: string]: number }>({})
  const isBack = useRef(false)
  const currentRoute = router.pathname
  const baseRoute = currentRoute.split('/')[1]

  const onRouteChangeComplete = (url: any) => {
    if (isBack.current && scrollPositions.current[url]) {
      setTimeout(() => {
        window.scroll({
          top: scrollPositions.current[url],
          behavior: "auto",
        })
      }, 1)
    } else {
      setTimeout(() => {
        window.scroll({
          top: 0,
          behavior: "auto",
        })
      }, 1)
    }
    isBack.current = false
  }

  useEffect(() => {
    router.beforePopState(() => {
      isBack.current = true
      return true
    })
    const onRouteChangeStart = () => {
      const url = router.asPath
      scrollPositions.current[url] = window.scrollY
    }
    router.events.on("routeChangeStart", onRouteChangeStart)
    return () => {
      router.events.off("routeChangeStart", onRouteChangeStart)
    }
  }, [router])

  // delQuery removes the query string from the url
  // this is necessary to prevent framer motion from animating on query string changes

  function delQuery(asPath) {
    return asPath.split('?')[0]
  }

  return (
    <>
      {baseRoute && baseRoute === 'studio' ? (
        <Component {...pageProps} />
      ) : (
        <WindowInfoProvider
          breakpoints={{
            phone: '(max-width: 767px)',
            tablet: '(min-width: 768px)',
            laptop: '(min-width: 1224px)',
            desktop: '(min-width: 1748px)',
          }}
        >
          <ScrollInfoProvider>
            <PreviousRouteProvider>
              <SplashProvider>
                {/* <Layout {...pageProps}> */}
                  <LazyMotion features={framerFeatures}>
                    <AnimatePresence 
                      mode="wait" 
                      initial={false}
                      onExitComplete={() => onRouteChangeComplete(router.asPath)} 
                    >
                      <m.div
                        key={delQuery(router.asPath)} 
                        initial="pageInitial" 
                        animate="pageAnimate"
                        exit="pageInitial"
                        variants={{
                          pageInitial: {
                            opacity: 0
                          },
                          pageAnimate: {
                            opacity: 1
                          },
                        }}
                      >
                        <Component {...pageProps} key={router.asPath} />
                      </m.div>
                    </AnimatePresence>
                  </LazyMotion>
                {/* </Layout> */}
              </SplashProvider>
            </PreviousRouteProvider>
          </ScrollInfoProvider>
        </WindowInfoProvider>
      )}
    </>
  )
}
```

**Comment by claus** [comment]
> It seems that the official documentation has not handled scrolling restoration well.

It's an infinite scroller, getting scroll restoration right with those is not trivial

**Comment by timneutkens** [comment]
Good news: This issue has been solved in App Router, we've kept it in mind from the start when building the new router. 
Unfortunate news: due to limitations of how the Pages Router and React work you can't reliably restore scroll as the client-side router did not have a cache that is reused when navigating back/forward, which means that e.g. getInitialProps / getStaticProps / getServerSideProps has to be re-executed to get the props for the page component. Theoretically this could be changed but it's very likely that would break existing applications.

For App Router we've changed this, the router is built around a client-side cache that is reused when navigating back/forward. In addition to that we've made changes in React to support React Transitions being synchronous when triggered in the `popstate` event. This ensures React blocks the main thread while rendering on `popstate` as browsers have a behavior where there's a time window before it commits on popstate in order for JS-based navigation to apply.
