### ISSUE TITLE
Hydration issues with dynamic and React 18

### ISSUE THREAD

**Issue by cornedor** [vercel/next.js#35728]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
    Binaries:
      Node: 16.13.2
      npm: 8.1.2
      Yarn: 1.22.0
      pnpm: N/A
    Relevant packages:
      next: 12.1.3-canary.0
      react: 18.0.0
      react-dom: 18.0.0

### What browser are you using? (if relevant)

Not relevant

### How are you deploying your application? (if relevant)

next dev, next start and vercel

### Describe the Bug

In apps we are building we use a catch-all route for CMS pages. These pages define different layouts. These pages are loaded using dynamic. With React 18 this causes hydration issues, in the case described in "to reproduce" you can see that the page is rendered below the SSR content. 

The /not-dynamic has a dynamic loaded component a level deeper, this works better but also causes a white flash.

![image](https://user-images.githubusercontent.com/570297/160828841-96df04c6-b30f-43bf-bb34-82cff3a8ee89.png)

### Expected Behavior

The app is hydrated properly when dynamic is used.

### To Reproduce

Source: https://github.com/cornedor/catch-all-dynamic-bug

Interactive content below SSR: https://catch-all-dynamic-bug.vercel.app/
White flash: https://catch-all-dynamic-bug.vercel.app/not-dynamic

EDIT:

Test case using Suspense: https://catch-all-dynamic-bug-git-suspense-cornedor.vercel.app/
Test case using React 17, everything works as expected: https://catch-all-dynamic-bug-git-react17-cornedor.vercel.app/

**Comment by diegohaz** [comment]
Seeing the same issue. I also tried to follow https://nextjs.org/docs/advanced-features/react-18/streaming#nextdynamic and replace `dynamic` with `React.lazy` and `Suspense`, but then I get this error:

> This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.

**Comment by cornedor** [comment]
Here de case with [Streaming SSR](https://nextjs.org/docs/advanced-features/react-18/streaming#enable-streaming-ssr) enabled and using suspense in dynamic:

The issue with the double content is resolved, but the content loaded using dynamic still flashes.

https://user-images.githubusercontent.com/570297/160841043-276e3ed8-3333-409a-aeeb-91db028e97e8.mov

Test case using Suspense: https://catch-all-dynamic-bug-git-suspense-cornedor.vercel.app/
Test case using React 17, everything works as expected: https://catch-all-dynamic-bug-git-react17-cornedor.vercel.app/

**Comment by huozhi** [comment]
It's fixed in 12.1.4, can you try to upgrade to it to see if it works for you? 🙏

**Comment by cornedor** [comment]
https://catch-all-dynamic-bug-git-12-1-4-cornedor.vercel.app/

The issue seems to be resolved. Thanks.

**Comment by lveillard** [comment]
> EDIT: My problem has ben fixed on 12.1.3-canary.2
> 
> Seeing the same issue. I also tried to follow https://nextjs.org/docs/advanced-features/react-18/streaming#nextdynamic and replace `dynamic` with `React.lazy` and `Suspense`, but then I get this error:
> 
> > This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition.

I keep having this issue with this error on console

**Comment by balazsorban44** [comment]
@lveillard could you attach a reproduction? (Make sure to test `canary`, to be sure it's not yet fixed)

**Comment by lveillard** [comment]
Let me create a quick repo, but first in case is enougth, this are the key elements throwing this error:
```
import { lazily } from 'react-lazily';

const { Home } = lazily(() => import('./svg/home'));
const { Search } = lazily(() => import('./svg/search'));
[...]
export const IconComp: React.FC<IconProps> = ({
  iconName,
  classNames,
}): React.ReactElement => {

  return (
    <span className={classNames}>
      <Suspense aria-hidden="true" fallback={<div>test</div>}>
        {
          {
            home: <Home />,
            search: <Search />,
          }[iconName]
        }
      </Suspense>
    </span>
  );
  
```

And my config:
```
/* eslint-disable import/no-extraneous-dependencies */
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});

module.exports = withBundleAnalyzer({
  reactStrictMode: false, // todo: set to true  once headlessui fixes react 18 issues
  eslint: {
    dirs: ['.'],
  },
  experimental: {
    concurrentFeatures: false,
  },
  poweredByHeader: false,
  trailingSlash: true,
  swcMinify: true,
  basePath: '',
});

```
