### ISSUE TITLE
Cannot build with-styled-components-babel

### ISSUE THREAD

**Issue by rafma0** [vercel/next.js#37281]
### Verify canary release

- [X] I verified that the issue exists in Next.js canary release

### Provide environment information

    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 17.8.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 12.1.7-canary.19
      react: 17.0.2
      react-dom: 17.0.2

### Which example does this report relate to?

with-styled-components-babel

### Describe the Bug

Trying to build the example without any changes results in

```
yarn build
yarn run v1.22.18
$ next build
Failed to compile.

./pages/_document.tsx:15:34
Type error: 'App' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<AppPropsType<NextRouter, {}>, any, any>' is not a valid JSX element.
    Type 'Component<AppPropsType<NextRouter, {}>, any, any>' is not assignable to type 'Element | ElementClass'.
      Type 'Component<AppPropsType<NextRouter, {}>, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("C:/Users/rafma0/with-styled-components-babel-app/node_modules/@types/styled-components/node_modules/@types/react/index").ReactNode'.
            Type '{}' is not assignable to type 'ReactNode'.

  13 |         originalRenderPage({
  14 |           enhanceApp: (App) => (props) =>
> 15 |             sheet.collectStyles(<App {...props} />),
     |                                  ^
  16 |         })
  17 |
  18 |       const initialProps = await Document.getInitialProps(ctx)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Upgrading React 17 > 18 solves the problem

### Expected Behavior

Build without error

### To Reproduce

1. yarn create next-app --example with-styled-components-babel with-styled-components-babel-app
2. cd with-styled-components-babel-app
3. yarn build

**Comment by ijjk** [comment]
Hi, this type is fixed in the latest canary of Next.js, please update and give it a try! x-ref: https://github.com/vercel/next.js/pull/36392

**Comment by rafma0** [comment]
Hey @ijjk thanks you for the fast reply, I just tried with latest canary `next@12.1.7-canary.23` and it still only compiles if I upgrade to react 18. 

The difference now is it tries 4 times before the error and ends up with

```
> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (C:\Users\rafma0\with-styled-components-babel-app\node_modules\next\dist\compiled\jest-worker\index.js:1:11661)
    at ChildProcessWorker._onExit (C:\Users\rafma0\with-styled-components-babel-app\node_modules\next\dist\compiled\jest-worker\index.js:1:12599)
    at ChildProcess.emit (node:events:527:28)
    at ChildProcess.emit (node:domain:475:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  type: 'WorkerError'
}
```

**Comment by balazsorban44** [comment]
@rafma0 I just tried to reproduce this, and I couldn't. If you still have issues, please create a repo and a separate issue, thanks!

**Comment by rafma0** [comment]
@balazsorban44 I upgraded my project to react 18 so I don't have this issue anymore but I just tried again without upgrade and I still get the errors. I'm attaching a video if you want to take a look at it. Thank you

https://user-images.githubusercontent.com/28578847/173208368-26cf9b44-b9e7-4bd5-b03f-cb33b5903829.mp4
