### ISSUE TITLE
TypeScript error on <style> with attributes `global` and `jsx`

### ISSUE THREAD

**Issue by Jule-** [vercel/next.js#38333]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: linux
      Arch: x64
      Version: #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022
    Binaries:
      Node: 16.14.2
      npm: 8.7.0
      Yarn: 1.22.5
      pnpm: N/A
    Relevant packages:
      next: 12.2.1-canary.2
      eslint-config-next: N/A
      react: 17.0.2
      react-dom: 17.0.2

### Describe the Bug

In my project when I try to create a component with global style I get a TypeScript error:
```tsx
// Test.tsx

export function Test() {
  return (
    <div>
      <style global jsx>{``}</style>
      {/*    ~~~~~~    */}
    </div>
  )
}
```
```
Type '{ children: string; global: true; jsx: true; }' is not assignable to type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.
  Property 'global' does not exist on type 'DetailedHTMLProps<StyleHTMLAttributes<HTMLStyleElement>, HTMLStyleElement>'.ts(2322)
```

And what seems strange is that `styled-jsx@5.0.2` seems to correctly define extension of `react` type with:
```ts
declare module 'react' {
  interface StyleHTMLAttributes<T> extends HTMLAttributes<T> {
    jsx?: boolean
    global?: boolean
  }
}
```
But for some reason, this seems not to be used by TypeScript.

### Expected Behavior

No TS error.

### Link to reproduction

https://codesandbox.io/s/musing-mcnulty-i2crqc?file=/components/Test.tsx

### To Reproduce

Just hover the `global` attribute in order to see the TypeScript error.

**Comment by Jule-** [comment]
Hi bot! Can't you read the `I verified that the issue exists in the latest Next.js canary release` checkbox? :sweat_smile: Or check on the repro link that is using `next@canary`? :wink:

**Comment by wiesson** [comment]
It also doesn't work with next canary

@Jule- Have you been able to suppress the error until it gets fixed? It's quite annoying.

The docs mentions that 

```
/// <reference types="styled-jsx" />
```
might help, but for me it did not: Source https://github.com/vercel/styled-jsx#typescript

**Comment by Jule-** [comment]
@wiesson I can confirm it works in my project. I put it in a project root folder named `types`, it's a habit, I am not sure if it is still relevant but I remember that sometimes (with some versions or with some tsconfig stuff) TS is looking in this folder.

**Comment by tangye1234** [comment]
file: ./node_modules/next/index.d.ts

![image](https://user-images.githubusercontent.com/447084/177762371-28c30d4e-18ae-4b25-a4c0-4c4c388b6b39.png)

If I changed the selected line into
```ts
/// <reference path="./dist/styled-jsx-types/global.d.ts" />
```

then all problems are addressed.

**Comment by SukkaW** [comment]
I was able to reproduce the issue in one of my projects: https://github.com/sukkaw/vercel-dns-console

I have fixed the issue by copy-pasting `styled-jsx` types directly into my repo: https://github.com/SukkaW/vercel-dns-console/blob/master/styled-jsx.d.ts

**Comment by Jule-** [comment]
@balazsorban44 Can you confirm that change spot by @tangye1234 is a wanted change? Or does it should be reverted?
And then, that @wiesson comment about importing types on our own is the intended way to handle this? (even if it feels a bit strange to have to do this while it is not a direct dependency of our projects)

Thanks a lot!

**Comment by handycode** [comment]
> file: ./node_modules/next/index.d.ts
> 
> ![image](https://user-images.githubusercontent.com/447084/177762371-28c30d4e-18ae-4b25-a4c0-4c4c388b6b39.png)
> 
> If I changed the selected line into
> 
> ```ts
> /// <reference path="./dist/styled-jsx-types/global.d.ts" />
> ```
> 
> then all problems are addressed.

It works! thanks!

**Comment by Jule-** [comment]
I think this commit should fix this issue https://github.com/vercel/next.js/commit/62f3f87891f71c4ef6d057880d760f318b131191 in the way @tangye1234 exposed.

At least I don't have the issue on CodeSandbox with `12.2.3-canary.7`. Closable with a new version release! :+1:

**Comment by ijjk** [comment]
Closing per above, please update to the latest version of Next.js `v12.2.3` and give it a try!

**Comment by anasik** [comment]
This still exists in v12.2.4

**Comment by ijjk** [comment]
@anasik could you open a fresh issue with a reproduction? Would be good to verify this is the case with `v12.2.5`

**Comment by Chamberlainfrancis** [comment]
This issue still exists with `v12.2.5` although I am not using typescript, I still got this error during build `Unknown property 'jsx' found` on here `<style jsx>{ }</style>`

**Comment by mskarimi** [comment]
> This issue still exists with `v12.2.5` although I am not using typescript, I still got this error during build `Unknown property 'jsx' found` on here `<style jsx>{ }</style>`

me too

**Comment by seiyab** [comment]
I also encountered same error in my project with v12.2.5.
So I tried to write a reproduction.
However, it works fine when I setup next project from start 🤔 
https://github.com/seiyab/repro/tree/main/next-styled-jsx
I'll continue to investigate it.

**Comment by seiyab** [comment]
I reproduced the problem.
`npx next build` and `npx next lint` complains when I install eslint.
```
./pages/index.tsx
4:16  Error: Unknown property 'jsx' found  react/no-unknown-property
```
https://github.com/seiyab/repro/tree/main/next-styled-jsx
It seems to be slightly different problem from this issue.
This issue is TypeScript error, and error in v12.2.5 is ESLint error.

I'll open a fresh issue 💡

**Comment by seiyab** [comment]
I found that a discussion for v12.2.5 has already opened.
https://github.com/vercel/next.js/discussions/40269
