### ISSUE TITLE
getStaticProps broken when changing language on index page

### ISSUE THREAD

**Issue by testerez** [vercel/next.js#38679]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

    Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101
    Binaries:
      Node: 16.16.0
      npm: 8.11.0
      Yarn: 1.22.19
      pnpm: 7.5.0
    Relevant packages:
      next: 12.2.3-canary.8
      eslint-config-next: 12.2.2
      react: 18.2.0
      react-dom: 18.2.0

### What browser are you using? (if relevant)

Chrome 103.0.5060.114

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

When switching the language on the root index page, staticProps are not passed to the page component. This issue does not happen locally, only once deployed to Vercel.

### Expected Behavior

I would except the static props to be properly fetched and passed to the page component.

### Link to reproduction

https://github.com/testerez/next-static-props-undefined/blob/main/pages/index.tsx

### To Reproduce

I have setup a minimal project to demonstrate the issue. It's deployed on Vercel: https://next-static-props-undefined.vercel.app/
To reproduce the issue, just click multiple times on the link to change the language. You should see that the props object becomes empty.
Looking at the browser network, I can see that https://next-static-props-undefined.vercel.app/_next/data/oQt2gXwVC5x6ncBnkzzsW/fr.json gets redirected to https://next-static-props-undefined.vercel.app/fr
I guess this is part of the issue.

**Comment by Babbili** [comment]
@testerez `getStaticProps` will pre-render the page at build time using the props returned by `getStaticProps` to deployment,  [getStaticProps Docs](https://nextjs.org/docs/basic-features/data-fetching/get-static-props) 

In case of switching locale it's better to use `getServerSideProps` as it will pre-render this page on each request using fresh data.
I used `getServerSideProps` in this [example (next-i18n)](https://github.com/Babbili/nextjs-multilingual) and it's going very well

**Comment by testerez** [comment]
Thanks for your reply @Babbili.
On most websites, the language can be switched on any page. So following your advice, `getStaticProps` could not be used at all. I believe my example should be working and it looks like there is a bug with either nextjs or Vercel.

**Comment by Babbili** [comment]
> Thanks for your reply @Babbili. On most websites, the language can be switched on any page. So following your advice, `getStaticProps` could not be used at all. I believe my example should be working and it looks like there is a bug with either nextjs or Vercel.

yes in you example it switched as you're `revalidating` the static props every 30 seconds, using [Incremental Static Regeneration](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration), while in `getServerSideProps` it switches at request time

**Comment by dmudro** [comment]
we are seeing the same issue when client side exception is thrown due to empty props passed. replicating the issue is _almost_ consistent and happens upon **any client side navigation to homepage** including changing lang, click on the logo etc. @testerez do you also see this or _only_ upon client side locale change?

the cient side exception is gone upon full browser reload as the props are normally populated.

had to downgrade back to `12.1`.

**Comment by dmudro** [comment]
`v12.2.4` issue still there; `getStaticProps` occasionally  returns no props when navigating to `/` homepage client-side and breaking the app until the next server side render.

**Comment by ijjk** [comment]
Hi, the initial reproduction appears to be working correctly in the latest version of Next.js `v12.2.4` as can be seen here https://next-static-props-undefined-bib7ubo03-ijjk-testing.vercel.app/ 

If you are still encountering this after a fresh deployment on the latest version please share a new reproduction/deployment so we can investigate further!

**Comment by dmudro** [comment]
in `v12.2.4` the issue was still there occasionally but looking good in `v12.2.5` 👍
