### ISSUE TITLE
'SomeComponent' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by professorhaseeb** [vercel/next.js#42292]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Pro
    Binaries:
      Node: 18.12.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.0.1-canary.4
      eslint-config-next: 13.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

### Describe the Bug

Any components are producing IDE error but builds successfully.

```
'SomeComponent' cannot be used as a JSX component.
  Its return type 'Promise<Element>' is not a valid JSX element.
    Type 'Promise<Element>' is missing the following properties from type 'ReactElement<any, any>': type, props, key `ts(2786)`
```

### Expected Behavior

probably not give an error when using async components

### Link to reproduction

no link

### To Reproduce

```ts
// ~/component/SomeComponent.tsx

export default async function SomeComponent() {
    let categories: any = await getCategories()
    return ...
}
```

**Comment by icyJoseph** [comment]
I think a fix is upcoming, but pretty much the issue is that TypeScript doesn't understand async components... It always expects JSX as child, not `Promise<JSX>`.

Many are type casting the component and exporting that type casted version... I think it might be better to do:

```tsx
import { RSCList } from "../../../components/RSCList";

export default function Page({ params }: { params: { id: string } }) {
  return (
    <div>
      Order: {params.id}
      <div>
        {/* @ts-expect-error Server Component */}
        <RSCList />
      </div>
    </div>
  );
}
```

When the types are fixed, the `@ts-expect-error` directive will complain that it is unused... 

This fix might come from the next typescript plugin I think, not sure.

**Comment by professorhaseeb** [comment]
@icyJoseph 

`{/* @ts-expect-error Server Component */}` worked for now.

Thanks

**Comment by saidMounaim** [comment]
> {/* @ts-expect-error Server Component */}

Thanks worked for me

**Comment by saidMounaim** [comment]
Thanks @icyJoseph 

`{/* @ts-expect-error Server Component */}` worked for me

**Comment by timneutkens** [comment]
This particular error is hardcoded in TypeScript. The React team is working with the TypeScript team to resolve this. For now you can use the recommendation above 👍

**Comment by leerob** [comment]
Just added a few notes about this workaround to the beta docs as well, thank you!

**Comment by diegohaz** [comment]
> The React team is working with the TypeScript team to resolve this.

Is there a public issue/PR on the TypeScript repo where that work can be followed?

**Comment by is-it-ayush** [comment]
The `{/* @ts-expect-error Server Component */}` get's rid of the typescript error as mentioned by [icyJoseph](https://github.com/icyJoseph). However, This produces a different `Server Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.`. Unsure If I'm doing something wrong. I'm using a RSC in the `/pages` directory which is `Promise<JSX.Element>` and returns a list. The data to it is passed via gssp and props. 

My guess is that the Promise is not resolved at the time of rendering. Hence, the error. If this is so, any workarounds until it is fixed.

**Comment by is-it-ayush** [comment]
> > However, This produces a different `Server Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.`. Unsure If I'm doing something wrong. I'm using a RSC in the `/pages` directory which is `Promise<JSX.Element>` and returns a list. The data to it is passed via gssp and props.
> 
> To my understanding server components are only available in the new app/ folder not pages/ so that would be the cause of your issue.

Ah Yes. I was not aware of it. In a sandbox I was able to reproduce the above error which I was expecting in `/pages` directory. Then I switched to beta `/app` directory and it worked charmingly. I now understand why it happened. Thanks @dantman!

**Comment by bongdungyeuem27** [comment]
> 

You only use async component inside app folder and server component.

**Comment by gaithoben** [comment]
The issue may have been introduced to your project via some other packages' peer dependency.

If you have a .tsconfig file, Add following to compilerOptions:

"paths": {
   "react": [ "./node_modules/@types/react" ]
 }

**Comment by Kamrulhasan12345** [comment]
Don't know why, but I am using `app` directory, but I can still see, `Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.` issue while rendering

**Comment by mstachalski** [comment]
Same here, I am passing a SSC as a child to a CSC. Both are wrapped in a SSC as mentioned in the Nextjs Docs.
Still I am getting the error "TS2786: 'TopicCardContent' cannot be used as a JSX component."

`<TopicCard side={"left"}><TopicCardContent /></TopicCard>`

**Comment by bgdnvk** [comment]
I'm using NextJS 13, the error still persists if you pass async server components. But `{/* @ts-expect-error Server Component */}` makes it work, would love to have a non-hacky way to approach this.

**Comment by Kamrulhasan12345** [comment]
@bgdnvk Mine is a render-time error, so this doesn't get mine working.

**Comment by sjohns21** [comment]
I upgraded my package types:
    "@types/node": "18.14.2",
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
and it was resolved!

**Comment by roniaxe** [comment]
> I upgraded my package types: "@types/node": "18.14.2", "@types/react": "18.0.28", "@types/react-dom": "18.0.11", and it was resolved!

Didn't work for me.

**Comment by sooohka** [comment]
> I upgraded my package types: "@types/node": "18.14.2", "@types/react": "18.0.28", "@types/react-dom": "18.0.11", and it was resolved!

didn't work either :(

**Comment by AveshLutchman** [comment]
> I upgraded my package types: "@types/node": "18.14.2", "@types/react": "18.0.28", "@types/react-dom": "18.0.11", and it was resolved!

Didn't work for me, on most recent for each as well.

**Comment by hiendaovinh** [comment]
The problem with `{/* @ts-expect-error Server Component */}` is that it will silence other typing errors.

**Comment by sami616** [comment]
@hiendaovinh  

Here is a wonky workaround which gets around the issue without losing all type safety for your incoming props. 👇🏼

```ts
type UserPostsProps = {
  userId: number
}

async function UserPosts({ userId }: UserPostsProps) {
  const userPosts: any = await fetch(
    `https://jsonplaceholder.typicode.com/posts?userId=${userId}`
  ).then(res => res.json())

  return (
    <ul>
      {userPosts.map((post: any) => (
        <li>{post.title}</li>
      ))}
    </ul>
  )
}

// As a temporary work around, we can override the type so that it returns a JSX.Element instead of a promsie 
const _UserPosts = UserPosts as unknown as (props: UserPostsProps) => JSX.Element
export { _UserPosts as UserPosts }
```

**Comment by srigi** [comment]
@sami616 genius, thanks!
It can be simplified to...

```ts
type Props {
  foo: number;
}

const UserPosts = (async ({ foo }: Props) => {
  // some await fetch()

  return (
    <h2>some JSX</h2>
  );
}) as unknown as (props: Props) => JSX.Element;

export default UserPosts;
```

**Comment by sami616** [comment]
@srigi trying to figure out if it’s possible to just the function keyword with a named export using this solution? 🤔

**Comment by mufidat3250** [comment]
i am using Next 13 and i tried using async on my component to fetch data but  was getting an error   
### cannot be used as a JSX component. Its return type 'Promise<Element>' is not a valid JSX element.

i tried using {/* @ts-expect-error Server Component */} to solve the problem but it still persist 
what am i doing wrong

**Comment by karlhorky** [comment]
> Is there a public issue/PR on the TypeScript repo where that work can be followed?

@diegohaz seems like this may be the related PR in the TypeScript repo (found via [this comment](https://github.com/vercel/next.js/issues/43537#issuecomment-1331054397) from @balazsorban44 ):

- https://github.com/microsoft/TypeScript/pull/51328

**Comment by PhilippeR26** [comment]
Hello,
The solutions provided the last days solves compilation error, but at execution, I have always : 
`error - Error: Objects are not valid as a React child (found: [object Promise]). If you meant to render a collection of children, use an array instead.`

**Comment by leggant** [comment]
> @srigi Another variation using the function keyword with a named export, note i have named both the variable and function the same to minimize refactoring when this TS issue is resolved.
> 
> ```ts
> export const Foo = async function Foo() {
>   //...
> } as unknown as () => JSX.Element
> ```

This worked perfect - thanks :)

**Comment by madfcat** [comment]
I still get an error in next.js 13.2.4. [in this scenario](https://beta.nextjs.org/docs/data-fetching/fetching#sequential-data-fetching):

`// ...

async function Playlists({ artistID }) {
  // Wait for the playlists
  const playlists = await getArtistPlaylists(artistID);

  return (
    <ul>
      {playlists.map((playlist) => (
        <li key={playlist.id}>{playlist.name}</li>
      ))}
    </ul>
  );
}

export default async function Page({ params: { username } }) {
  // Wait for the artist
  const artist = await getArtist(username);

  return (
    <>
      <h1>{artist.name}</h1>
      <Suspense fallback={<div>Loading...</div>}>
        <Playlists artistID={artist.id} />
      </Suspense>
    </>
  );
}`

This code `{/* @ts-expect-error Server Component */}` helps a bit though, but does not solve the issue.

**Comment by WoLfulus** [comment]
I worked around this one by writing a HOC.

```tsx
type AFC<P = {}> = (
  ...args: Parameters<React.FC<P>>
) => Promise<ReturnType<React.FC<P>>>;

function asSyncComponent<T extends AFC<any>>(
  component: T
): React.FC<T extends AFC<infer P> ? P : never> {
  return component as any;
}
```

```tsx
export const MyComponent = asSyncComponent(async function (props: any) {
  const data = await ...;
  return <>{...}</>;
});
```

**Comment by lukevers** [comment]
I just ran into this too--the recommendation to use `as unknown as () => JSX.Element` is what worked for me, here's what I was doing:

```typescript
<HasPermission resource={Resource.REFERRAL} action={Permission.CREATE}>
```

## `@/util/HasPermission.tsx`
```
'use server';

import React from 'react';
import { getSession } from './session';
import db, { Permission, Resource } from './db';

interface Props {
  children: React.ReactNode;
  resource: Resource;
  action: Permission;
}

const HasPermission = async function HasPermission(props: Props) {
  const session = await getSession();
  if (!session || !session.user || !session.user.email) {
    return null;
  }

  const permission = await db.userRolePermission.findFirst({
    where: {
      resource: props.resource,
      actions: {
        has: props.action,
      },
      Role: {
        is: {
          Users: {
            some: {
              email: session.user.email,
            },
          },
        },
      },
    },
  });

  if (!permission) {
    return null;
  }

  return <>{props.children}</>;
};

export default HasPermission as unknown as (props: Props) => JSX.Element;
```

**Comment by lukevers** [comment]
I just ran into this too--the recommendation to use `as unknown as () => JSX.Element` is what worked for me, here's what I was doing:

### some page
```typescript
<HasPermission resource={Resource.EXAMPLE} action={Permission.CREATE}>
  <div>stuff</div>
</HasPermission>
```

### `@/util/HasPermission.tsx`
```typescript
'use server';

import React from 'react';
import { getSession } from './session';
import db, { Permission, Resource } from './db';

interface Props {
  children: React.ReactNode;
  resource: Resource;
  action: Permission;
}

const HasPermission = async function HasPermission(props: Props) {
  const session = await getSession();
  if (!session || !session.user || !session.user.email) {
    return null;
  }

  const permission = await db.userRolePermission.findFirst({
    where: {
      resource: props.resource,
      actions: {
        has: props.action,
      },
      Role: {
        is: {
          Users: {
            some: {
              email: session.user.email,
            },
          },
        },
      },
    },
  });

  if (!permission) {
    return null;
  }

  return <>{props.children}</>;
};

export default HasPermission as unknown as (props: Props) => JSX.Element;
```

I was happy to see at least here that in my call at the bottom, setting `(props: Props)` continued to let typescript understand what the required props were.

**Comment by webbugt** [comment]
> I worked around this one by writing a HOC. At least it wont shadow typing errors, keeps argument names and it's less verbose to write compare to casting it multiple times.

This works great. No need to fuss around with same pattern on every ServerComponent

**Comment by IgorMagal** [comment]
{/* @ts-expect-error Server Component */}

Saved my day!

**Comment by headexpanded** [comment]
@srigi
Thanks for this, it works perfectly:
```
type Props {
  foo: number;
}

export default (async function UserPosts({ foo }: Props) {
  // some await fetch()

  return (
    <h2>some JSX</h2>
  );
} as unknown as (props: Props) => JSX.Element);
```

**Comment by omgismartinez** [comment]
if you use **server components**, make sure that you do not import an async component when it is a client-side component

```typescript
// Server component

export default async function Account() {
    const user = await getCurrentUser()
    return <FormAccount user={user} />
}
``` 

```typescript
// Client component

'use client'

               error
                 |   
export default async function FormAccount ({ user }: User) {
    const handleSave = (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault()
    }
    return (
        <form onSubmit={handleSave}>
            <input placeholder='name' defaultValue={user.name} />
            <button type='submit'>Submit</button>
        </form>
    )
}
``` 
this is just an observation.

**Comment by nmiddendorff** [comment]
Now that https://github.com/microsoft/TypeScript/pull/51328 is merged and available in `typescript@5.1.0-beta` are there any additional changes needed for this to work without the `{/* @ts-expect-error Server Component */}` hack?

Example
```tsx
// page.tsx
import React from 'react';
import MarkdownBlock from './markdown-block';

export default function Home(): React.ReactElement {
  return <MarkdownBlock markdown="hello" />;
}

```
```tsx
// markdown-block.tsx
export default async function MarkdownBlock({
  markdown,
}: {
  markdown: string;
}): Promise<React.ReactElement> {
  return <span>{markdown}</span>;
}

```


I upgraded typescript to the beta and still see the error:
```
'CodeSnippet' cannot be used as a JSX component.
  Its return type 'Promise<Element>' is not a valid JSX element.
```

**Comment by kachkaev** [comment]
Seeing the same problem as @nmiddendorff in https://github.com/kachkaev/website/pull/32/files after upgrading to `typescript@5.1.0-beta`, `@types/react@18.0.38` and `next@13.3.1`.

**Comment by urakymzhan** [comment]
> Seeing the same problem as @nmiddendorff in [kachkaev/website#32](https://github.com/kachkaev/website/pull/32). I thought that upgrading to `typescript@5.1.0-beta`, `@types/react@18.2.1` and `next@13.3.1` would help but it did not. What else is needed to remove `@ts-expect-error` before `<ServerComponent />`?

I am also having this issue. Upgrading didn't help because type `ElementType` is not available in new packages?

**Comment by kachkaev** [comment]
Just upgraded to `next 13.4.0`, `@types/react 18.2.5` `@types/react-dom 18.2.3` in https://github.com/kachkaev/website/pull/32 – still seeing this error:

```
'MyAsyncComponent' cannot be used as a JSX component.
  Its return type 'Promise<Element>' is not a valid JSX element.
    Type 'Promise<Element>' is missing the following properties from type 'ReactElement<any, any>': type, props, key
```

Upgrading `typescript 5.1.0-beta` to `typescript 5.1.0-dev.20230502` (latest available build) did not help.

**Comment by Slamerz** [comment]
Started encountering this same error messages when upgrading `"@types/react": "18.2.1"` to `"@types/react": "18.2.5"`

**Comment by bjarn** [comment]
Starts at 18.2.4, 18.2.3 and lower are fine.

**Comment by zackdotcomputer** [comment]
The reoccurance of this error with `@types/react` 18.2.4+ is because of a mismatch in the typedefs between the one used internally by Next and the one your app uses if you are using Typescript 5. The types package added a TS5 specific typedef in 18.2.4 that isn't present previously. If you downgrade to TS4 or the types package, it will fix the issue, but you can also force Next's types to use the latest version in `package.json` to make the issue go away:

```json
  "resolutions": {
    "@types/react-dom": "18.2.4",
    "@types/react": "18.2.5"
  }
```

**Comment by temasaguru** [comment]
> The reoccurance of this error with `@types/react` 18.2.4+ is because of a mismatch in the typedefs between the one used internally by Next and the one your app uses if you are using Typescript 5. The types package added a TS5 specific typedef in 18.2.4 that isn't present previously. If you downgrade to TS4 or the types package, it will fix the issue, but you can also force Next's types to use the latest version in `package.json` to make the issue go away:
> 
> ```json
>   "resolutions": {
>     "@types/react-dom": "18.2.4",
>     "@types/react": "18.2.5"
>   }
> ```
> 
> (Edit: I see they've already updated the dependency in Next so the next release should also fix this.)

Thank you for pointing out the cause!

As they upgraded the dependency, my errors are now gone after upgrading next to latest.

**Comment by AndrejGajdos** [comment]
@zackdotcomputer I tried that, but it didn't change anything.

**Comment by zackdotcomputer** [comment]
@AndrejGajdos are you using npm or yarn? I should have noted that the resolutions feature only works for yarn - npm users will have to use the equivalent overrides feature.

**Comment by AndrejGajdos** [comment]
@zackdotcomputer sorry I should have been more specific. I use npm, but I checked my lock file and use both:

"@types/react-dom": "18.2.4",
"@types/react": "18.2.5"

**Comment by marcelo-albuquerque** [comment]
Issue persisted.

**Comment by ozzyonfire** [comment]
I fixed this in my project by changing VSCode's typescript version. 
Ctrl + Shift + P > Typescript: Select Typescript Version...
Change to "Use workspace version" 

Mine was a later version of Typescript than VSCode's

**Comment by freeatnet** [comment]
I faced a similar issue after upgrading `@types/react` from `18.2.0` to `18.2.6` alongside `@types/react-dom` from `18.2.1` to `18.2.4`.

TL;DR: Try deduplicating `@types/react` in your lockfile, or remove and re-install `@types/react-dom`.

The underlying issue appeared to be that `@types/react-dom` lists `@types/react@*` as a dependency, so both `@types/react@18.2.6` and `@types/react-dom > @types/react@18.2.0` ended up being installed after the upgrade. This results in some sort of a type conflict and produces the error above.

**Comment by Puetz** [comment]
> Worth to note: If you put the `{/* @ts-expect-error Server Component */}` before the async JSX element, it will also ignore any other (unrelated) errors you might have. For example passing a prop but with a wrong type.

I'm really glad I came back to this thread. I was having some issues with my localization because of this exact reason. I passed down wrong props and did not get any Typescript errors.

I now changed my exports to `as unknown as (props: Props) => JSX.Element;` as suggested by lukevers. Works very well for me.

**Comment by kachkaev** [comment]
@freeatnet did deduplicating help you resolve this issue? Still seeing the same error for async components in https://github.com/kachkaev/website/pull/32 (`typescript@5.1.1-rc`). React types are deduplicated:

```
pnpm why @types/react @types/react-dom

devDependencies:
@types/react 18.2.7
@types/react-dom 18.2.4
└── @types/react 18.2.7
```

**Comment by edxeth** [comment]
`as unknown as () => JSX.Element` works like a charm, thank you!

```typescript
// ./app/components/Home/Logo.tsx
import Image from "next/image";

async function getData() {
  const res = await fetch('http://locahost/api/test');
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.
  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error('Failed to fetch data');
  }
  return res.json();
}

export default (async function Logo() {
  const data = await getData();
  return (
    <div className="relative flex place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px]">
      <Image
        className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
        src="/img/next.svg"
        alt="Next.js Logo"
        width={180}
        height={37}
        priority
      />
      <p>{data.message}</p>
    </div>
  );
} as unknown as () => JSX.Element);
``` 

Although `{/* @ts-expect-error Server Component */}` also works, the earlier workaround remains the **best**.

**Comment by furkanbay** [comment]
> `as unknown as () => JSX.Element` works like a charm, thank you!
> 
> ```ts
> // ./app/components/Home/Logo.tsx
> import Image from "next/image";
> 
> async function getData() {
>   const res = await fetch('http://locahost/api/test');
>   // The return value is *not* serialized
>   // You can return Date, Map, Set, etc.
>   if (!res.ok) {
>     // This will activate the closest `error.js` Error Boundary
>     throw new Error('Failed to fetch data');
>   }
>   return res.json();
> }
> 
> export default (async function Logo() {
>   const data = await getData();
>   return (
>     <div className="relative flex place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px]">
>       <Image
>         className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
>         src="/img/next.svg"
>         alt="Next.js Logo"
>         width={180}
>         height={37}
>         priority
>       />
>       <p>{data.message}</p>
>     </div>
>   );
> } as unknown as () => JSX.Element);
> ```
> 
> Although `{/* @ts-expect-error Server Component */}` also works, the earlier workaround remains the **best**.

This worked for me. 

`export default Header as unknown as () => JSX.Element;`

**Comment by masterkain** [comment]
doesn't for me at least when props are passed down

**Comment by WoLfulus** [comment]
> ~doesn't for me at least when props are passed down~
> 
> edit: this did it, thanks `export default OccurrencesTable as unknown as (props: OccurrencesTableProps) => JSX.Element;` 👍

https://github.com/vercel/next.js/issues/42292#issuecomment-1491127192

**Comment by Frikki** [comment]
A temporary workaround is to add `{/* @ts-expect-error Async Server Component */}` above the component to disable type checking.

See [async and await in Server Components](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching#async-and-await-in-server-components)

**Comment by pawelblaszczyk5** [comment]
Afaik, this is the PR that will fix it https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65135 in combination with TypeScript 5.1.
I've managed to make it work locally by patching this PR content onto older version of react types - https://github.com/pawelblaszczyk5/coloruiz/blob/main/patches/%40types__react%4018.2.7.patch

**Comment by pawelblaszczyk5** [comment]
The PR got merged and It's working correctly with `@types/react@18.2.8` and latest TypeScript version 🥳

**Comment by karlhorky** [comment]
@professorhaseeb or @leerob maybe the issue can be closed now?

**Comment by pawelblaszczyk5** [comment]
It'd be also nice to adjust this docs part https://nextjs.org/docs/app/building-your-application/data-fetching/fetching#async-and-await-in-server-components:~:text=Async%20Server%20Component%20TypeScript%20Error

**Comment by Inviz** [comment]
how to write jsx now in a way that works with both? New builds now fail if i used ts-expect-error

**Comment by pawelblaszczyk5** [comment]
> how to write jsx now in a way that works with both? New builds now fail if i used ts-expect-error

You can remove all ts-expect-error related to this error now. If you're using vscode make sure you're using local version of it. 
<img width="732" alt="image" src="https://github.com/vercel/next.js/assets/54995479/c312a2df-26ce-4ba6-b059-f949c7e126d7">
<img width="724" alt="image" src="https://github.com/vercel/next.js/assets/54995479/1468c943-234b-4692-acaf-d86ca645361f">

**Comment by PerssonDennis** [comment]
These other docs will also need to be updated: https://nextjs.org/docs/app/building-your-application/configuring/typescript#async-server-component-typescript-error

But issue will still continue to exist for a while in new different boilerplates.

**Comment by Davidihl** [comment]
I updated the Typescript version in my project to 5.1.3 as well as @types/react to 18.2.8 suggested by @pawelblaszczyk5  but unfortunately the error still shows up in my case.

**Comment by rnnyrk** [comment]
Reloading the window in VSCode might help. Worked from me. Also make sure @pawelblaszczyk5 suggestion about the workspace is set correctly.

**Comment by Davidihl** [comment]
I did exactly that.

First I updated typescript and made sure it is applied in my workspace while running @types/react on v18.2.6
<img width="166" alt="Bildschirmfoto 2023-06-02 um 00 57 27" src="https://github.com/vercel/next.js/assets/111972510/601ef3b7-0350-4501-9c0c-cf38f86c9ab6">

Then I updated @types/react to 18.2.8 which created 2 new errors:

1. A `<Fragment> <AnotherComponent /> </Fragment>`triggered the same error, which I could resolve by removing the wrapping fragment
2. `import {cache} from 'react';` triggers an error `Module '"react"' has no exported member 'cache'.` which has been resolved according to https://github.com/vercel/next.js/issues/49707 with @types/react v18.2.6

I reloaded the window between each step. So my guess is that I am missing a step that you already did.

**Comment by childrentime** [comment]
still

**Comment by Inviz** [comment]
> > how to write jsx now in a way that works with both? New builds now fail if i used ts-expect-error
> 
> You can remove all ts-expect-error related to this error now. If you're using vscode make sure you're using local version of it. <img alt="image" width="732" src="https://user-images.githubusercontent.com/54995479/242715777-c312a2df-26ce-4ba6-b059-f949c7e126d7.png"> <img alt="image" width="724" src="https://user-images.githubusercontent.com/54995479/242715897-1468c943-234b-4692-acaf-d86ca645361f.png">

Unfortunately I can not do that. We are generating code for user to copy and paste into their app. We dont know which version of TS/react types will they have. If we remove ts-expect-error that will fail old versions. If we keep it we fail new versions. If we change it to ts-ignore we basically disable type checking. All bad  options :(

**Comment by charleskoehl** [comment]
I tried updating @types/react, @types/react-dom to latest, and typescript to 5.1.3, but still many errors like these all over my next.js app:

'SomeComponent' cannot be used as a JSX component.  Its return type 'ReactNode' is not a valid JSX element. 

I finally had to downgrade typescript to 5.0.4

**Comment by leerob** [comment]
I've confirmed this is working! 🎉 

To use an `async` Server Component with TypeScript, ensure you are using TypeScript `5.2` or higher and `@types/react` `18.2.8` or higher, and select the correct TypeScript version inside of VSCode. 

If you are still seeing issues, please try restarting VSCode or clearing `node_modules`.

**Comment by stefanprobst** [comment]
> TypeScript 5.2 or higher

do you mean 5.1?

**Comment by ryanagillie** [comment]
Yeah I'm still getting the issue `Module '"react"' has no exported member 'cache'.`
```json
"@types/react": "18.2.8",
"@types/react-dom": "18.2.4",
"typescript": "5.1.3"
```

**Comment by amlcodes** [comment]
use "@types/react": "18.2.5",

**Comment by s-fletcher** [comment]
>> TypeScript 5.2 or higher
>
> do you mean 5.1?

I have confirmed this is now working with
* `@types/react` `18.2.8`
* `typescript` `5.1.3`

**Comment by niko-la-petrovic** [comment]
@s-fletcher Thanks! Working well.

**Comment by nmiddendorff** [comment]
I just confirmed that upgrading typescript packages and selecting the VSCode TS version fixed the issue. 🙌

**Comment by khaledyd** [comment]
I just confirmed, is now working with

@types/react 18.2.8
typescript 5.1.3

**Comment by JohnSmith0602** [comment]
I've done all the steps, yet still with the error of 'xxx cannot be used as a JSX component'.

- @types/react 18.2.8
- typescript 5.1.3
- select VS code ts version to typescript 5.1.3
- remove node_modules and install again
- restart VS code and computer

**Comment by Davidihl** [comment]
Finally I can also confirm that I could fix the issue for my case:

What did I do:

1. removed node_modules directory from my local repository
2. removed pnpm-lock.yaml
3. ran pnpm install
4. made sure I am running on typescript 5.1.3 and @types/react 18.2.8
5. made sure my VScode workspace is running on typescript 5.1.3

check your `package.json` and make sure that the correct versions are set inside.

Thanks to everyone contributing!

**Comment by SachaG** [comment]
Working for me as well following the steps outlined by @leerob.

**Comment by MarcosRZ** [comment]
Similar solution here. In my case:

1. Set new versions in package.json
```
"@types/react": "^18.2.8",
"@types/react-dom": "^18.2.4",
"typescript": "^5.1.3"
```
2. Remove node_modules
3. `npm i`
4. `> Developer: Reload window`

And VSCode asked me to use the local typescript version instead of the global one. That did the trick.

**Comment by lucgagan** [comment]
Didn't expect this to work, but nuking node_modules and pnpm-lock.yarn and re-installing actually fixed the issue.

**Comment by qmmr** [comment]
In my case that was enough 💪 
```git
diff --git a/package.json b/package.json
index b5f95bd..c53ca79 100644
--- a/package.json
+++ b/package.json
@@ -13,7 +13,7 @@
-    "@types/react": "18.2.7",
+    "@types/react": "18.2.9",
     "@types/react-dom": "18.2.4",
@@ -33,7 +33,7 @@
-    "typescript": "^5.0.4"
+    "typescript": "^5.1.3"
   },
```

**Comment by travistylerVII** [comment]
Finally worked: 

1. Updated packages. 

```
"@types/react": "^18.2.8",
"@types/react-dom": "^18.2.4",
"typescript": "^5.1.3"
```

2. Nuked node_modules. 
3. Nuked package-lock.json
4. Restarted Typescript & ESlist server. 
5. Sold my first born to the coding gods. 
6. Restarted VS Code. 

No error. :')

**Comment by tomosnam** [comment]
This is what nextjs doc says: https://nextjs.org/docs/app/building-your-application/configuring/typescript)

**Comment by urakymzhan** [comment]
It worked with ts: 18 and react/types: 18
Thanks all

**Comment by nfabacus** [comment]
Unfortunately, it solves the "cannot be used as a JSX component" error, but it will break eslint for me with eslint-config-next in next/core-web-vitals.
My IDE webstorm can no longer detect .eslintrc.json.
{
  "extends": ["next/core-web-vitals"]
}

**Comment by shubasishdas** [comment]
> 



> Finally worked:
> 
> 1. Updated packages.
> 
> ```
> "@types/react": "^18.2.8",
> "@types/react-dom": "^18.2.4",
> "typescript": "^5.1.3"
> ```
> 
> 2. Nuked node_modules.
> 3. Nuked package-lock.json
> 4. Restarted Typescript & ESlist server.
> 5. Sold my first born to the coding gods.
> 6. Restarted VS Code.
> 
> No error. :')


This guide along with this link fixed my issue  - https://nextjs.org/docs/app/building-your-application/configuring/typescript

**Comment by hydRAnger** [comment]
I found this issue will occur again if upgrade to 😕 
```
    "@types/react": "18.2.13",
    "@types/react-dom": "18.2.6",
    "typescript": "5.1.3"
 ```
 
 but below works
 ```
     "@types/react": "18.2.12",
    "@types/react-dom": "18.2.5",
    "typescript": "5.1.3"
 ```

**Comment by fanzypantz** [comment]
> I found this issue will occur again if upgrade to 😕
> 
> ```
>     "@types/react": "18.2.13",
>     "@types/react-dom": "18.2.6",
>     "typescript": "5.1.3"
> ```
> 
> but below works
> 
> ```
>    "@types/react": "18.2.12",
>    "@types/react-dom": "18.2.5",
>    "typescript": "5.1.3"
> ```

What react verrsion? I am on latest and still got errors from these versions.

**Comment by hydRAnger** [comment]
> > I found this issue will occur again if upgrade to 😕
> > ```
> >     "@types/react": "18.2.13",
> >     "@types/react-dom": "18.2.6",
> >     "typescript": "5.1.3"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but below works
> > ```
> >    "@types/react": "18.2.12",
> >    "@types/react-dom": "18.2.5",
> >    "typescript": "5.1.3"
> > ```
> 
> What react verrsion? I am on latest and still got errors from these versions.

```
    "react": "18.2.0",
    "react-dom": "18.2.0",
```

**Comment by noviceGuru** [comment]
## For who wants to test an `async Component` :
In my opinion it makes sense for `TypeScript` to throw an error, after all this is an `async` function and may return a `Promise`. So, I would await it to return the `JSX` we are expecting:
```
test('RSCList  renders correctly', async () => {
	 render(
		await (async () => await RSCList())()
	 )

	expect(...).toBe(...)
})
```

**Comment by timneutkens** [comment]
Based on https://twitter.com/sebsilbermann/status/1664356039876124672 I created a new Next.js application using create-next-app and was able to verify it works now.

- `pnpm create next-app --typescript typescript-async-component`
- Changed `app/page.tsx`:

```tsx
async function MyComponent() {
  await new Promise((resolve) => {
    setTimeout(resolve, 500);
  });

  return <h1>Hello World</h1>;
}
```

And added:

```tsx
<div className={styles.center}>
  <MyComponent />
</div>
```

Great work @eps1lon!


> In my opinion it makes sense for TypeScript to throw an error, after all this is an async function and may return a Promise. So, I would await it to return the JSX we are expecting:

The latest version of React (specifically for server components) supports async functions as JSX, TypeScript just wasn't up to date with that yet.

**Comment by stefanprobst** [comment]
@timneutkens i am still seeing an error with an explicit `Promise<ReactNode>` return type annotation: "Type is referenced directly or indirectly in the fulfillment callback of its own 'then' method.ts(1062)"

see https://github.com/vercel/next.js/issues/42292#issuecomment-1575583207

**Comment by pawelblaszczyk5** [comment]
> @timneutkens i am still seeing an error with an explicit `Promise<ReactNode>` return type annotation: "Type is referenced directly or indirectly in the fulfillment callback of its own 'then' method.ts(1062)"
> 
> see [#42292 (comment)](https://github.com/vercel/next.js/issues/42292#issuecomment-1575583207)

ReactNode now basically includes the Promise<ReactNode> part atm, so your type is recursive and never ends 😄 If you really want to explicitly type it - using just a ReactNode should be fine

**Comment by stefanprobst** [comment]
hmm, `async function SomeComponent(): ReactNode { /** */ }` results in: "The return type of an async function or method must be the global Promise<T> type. Did you mean to write 'Promise<string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | ReactPortal | null | undefined>'? ts(1064)"

**Comment by pawelblaszczyk5** [comment]
> > ReactNode now basically includes the Promise part atm, so your type is recursive and never ends smile If you really want to explicitly type it - using just a ReactNode should be fine
> 
> hmm, `async function SomeComponent(): ReactNode { /** */ }` results in: "The return type of an async function or method must be the global Promise type. Did you mean to write 'Promise<string | number | boolean | ReactElement<any, string | JSXElementConstructor> | Iterable | ReactPortal | null | undefined>'? ts(1064)"

Oh, that's strange, I've checked it now and I see this issue as well. Maybe it's because the underlying type is using `PromiseLike` instead of native `Promise` interface 🤔 Because it seems like it gets stripped in proposed type

<img width="862" alt="image" src="https://github.com/vercel/next.js/assets/54995479/d66e46b8-5ff6-49c4-bb2d-a8b1170ebe07">

I personally don't use explicit return types so I don't have an idea for a *good* solution here, sorry. Though, it's not related to this issue tbh, it's just a typing problem

**Comment by eps1lon** [comment]
`Promise<React.ReactNode>` seems to work just fine with latest types: [Playground Link](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAcigUwIYGMYHpkA8zJSjIB2MqANggFCiSxwBUcqAznAEpqZwBmUEEIhQYYNalixwAAjFYBaPAUyKoAqNTYBPEuj4BXXTGAQScAMKDIJUjAAUASgBcnbjAB0XUQDkIAE2Q4AG8AX2pNVh09XkNMEzNLcFNbACZHFwAFARBgVmQAHi9MTzdfAIA+YOo4GrgUGH0oMwAiZuoQoA)


The only bug we need to fix in types/react is that async is only for experimental when it's already available in canary.

**Comment by jacobsfletch** [comment]
Bumping `@types/react` to v18.2.14 fixed this for me in dev, but for some reason its still throwing an error when building 🤷 

![Screenshot 2023-07-06 at 12 34 02 AM](https://github.com/vercel/next.js/assets/15735305/353276e0-2ac0-4030-8e6b-656960d8be85)

![Screenshot 2023-07-06 at 12 32 38 AM](https://github.com/vercel/next.js/assets/15735305/55bd13b6-dd29-4fe0-ac98-da89061d956a)

I also tried explicitly typing the return of my component to `Promise<React.ReactNode>` like @stefanprobst suggested but that is throwing the same error for me as was reported. For now I get around this by using `@ts-expect-error` but ts thinks this directive is unused:

![Screenshot 2023-07-06 at 12 55 49 AM](https://github.com/vercel/next.js/assets/15735305/51ac2db8-00ac-492c-a529-4861cc66ace3)

**Comment by jjm2317** [comment]
If you are using the `jsxImportSource` option in `tsconfig.json`, there is a possibility that the issue you encountered could be due to the outdated version of the related jsx parsing module.
 
In my case, I was using the `"jsxImportSource": "@emotion/react"` option in `tsconfig.json`. When I updated `@types/react` from version 18.0 to 18.2.14, I faced the problem `'Component' cannot be used as a JSX component`. I found that this issue was fixed in the release version 11.11.1 of @emotion/react, as mentioned in https://github.com/emotion-js/emotion/releases/tag/%40emotion%2Freact%4011.11.1. After updating @emotion/react to the latest version, the problem was resolved.

**Comment by karlhorky** [comment]
More background on the `@emotion/react` problem here:

- https://github.com/emotion-js/emotion/issues/3049

**Comment by WooodHead** [comment]
I solved this problem with following steps (if you are using VSCode):
- npm install -g typescript@lastest
- Install extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

Source: https://stackoverflow.com/a/65151679/3317931
