### ISSUE TITLE
502 TOO_MANY_FORKS on next/data JSON with middleware and fallback: false

### ISSUE THREAD

**Issue by erzr** [vercel/next.js#47016]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Enterprise
    Binaries:
      Node: 18.13.0
      npm: N/A
      Yarn: N/A
      pnpm: N/A
    Relevant packages:
      next: 13.2.5-canary.0
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Data fetching (gS(S)P, getInitialProps), Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue

https://github.com/erzr/vercel-middleware-slug

### To Reproduce

* Deploy linked GitHub repository to Vercel site
* Open Developer Tools
* Observe that `index.json` fetch requests are producing a 502: TOO_MANY_FORKS error 🍴

### Describe the Bug

When you define a middleware (https://github.com/erzr/vercel-middleware-slug/blob/main/middleware.ts), even if it does nothing besides call `NextResponse.next()` in combination with a page route (https://github.com/erzr/vercel-middleware-slug/blob/main/pages/%5B%5B...slug%5D%5D.tsx) that exports `getStaticPaths` which returns `fallback: false` and deploy this to a Vercel site, requests to JSON files in `next/data` will produce 502, TOO_MANY_FORKS errors.

Example deployed version demonstrating this issue: https://vercel-middleware-slug.vercel.app/

### Expected Behavior

Requests to files in `next/data` return JSON with status code 200.

### How are you deploying your application? (if relevant)

Vercel

**Comment by electricenjindevops** [comment]
We are having this same issue recently. We are not sure of the full implications right now, but are worried because this came out of nowhere for us, and we don't have a choice: we must use fallback false, and we must use middleware. There is no way for us to avoid those two settings being used, and we also can't avoid the 6 slug folders we need for different routes. Only 2 routes are true wildcards, the rest start with a static folder name.

**Comment by maverickdude** [comment]
I am facing this issue too. It came out of nowhere today.
Removed middleware temporarily to see if this fixes the issue and it indeed did. So issue must be in the middleware.

`    Operating System:
      Platform: darwin
      Arch: x64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64
    Binaries:
      Node: 18.14.0
      npm: 9.3.1
      Yarn: 1.22.18
      pnpm: N/A
    Relevant packages:
      next: 13.1.1
      eslint-config-next: 13.1.1
      react: 18.2.0
      react-dom: 18.2.0`

**Comment by electricenjindevops** [comment]
Hi Uma, yes - super annoying bug. Here is how we fixed it:

We solved it by finding obscure bug reports about notFound: true
interfering with Middleware, along with being on a specific Next version.
V13.2.4 is working great for us, but yeah, not sure how to solve on older
versions - we had to stop our project, upgrade from 12 to 13 and re-QA /
fix everything - but at least we can keep using our Middleware.ts file!

This link helped give us some clues:
https://github.com/vercel/next.js/issues/38239

Good luck to all of you!

**Comment by maverickdude** [comment]
Hi @electricenjindevops 
Thanks for your quick reply and help.

Thing is, in my project we are not using `getStaticProps` and `getStaticPaths` anywhere, only `getServerSideProps`.
And Middleware too is very simple, only checking for Auth header.

I also tried upgrading the Next.js version to both v13.2.4 and latest now but issue still persists.

I will look into it more. Thanks again for your help. 🙏

**Comment by ijjk** [comment]
Hi, if you are hitting the forks limit could you reach out via https://vercel.com/help and submit a case sharing the affected project, we have an update that can help alleviate this!

**Comment by maverickdude** [comment]
Hi @ijjk 
I'm on Hobby plan on Vercel and thus can't submit a case. Could you please guide here? Many thanks!

**Comment by maverickdude** [comment]
Hey @ijjk 
Sorry or bothering. But is there a way to have it fixed wihout submitting a case on Vercel?

**Comment by maverickdude** [comment]
@ijjk 
I have submitted a case #00144438.
If possible please look into that.

**Comment by iwasrobbed** [comment]
Ran into this as well, ended up having to delete the middleware to get it working. Seems like Vercel is setting some arbitrary limit of how many pages can be rewritten. I only had a single `has` but it was intended to rewrite many nested pages 

If nothing else, it's an incredibly confusing error message to throw and the rewrites documentation says nothing about this or how it conflicts with the middleware component

**Comment by balazsorban44** [comment]
Closing as per the above comment.
