### ISSUE TITLE
React lazy or next dynamic don't reduce an app route's "First Load JS"

### ISSUE THREAD

**Issue by antoineol** [vercel/next.js#49454]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.4.2-canary.0
      eslint-config-next: 13.4.0
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
```

### Link to the code that reproduces this issue

https://codesandbox.io/p/github/antoineol/repro-next-lazy-build-size/main?layout=%257B%2522activeFilepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522fullScreenDevtools%2522%253Afalse%252C%2522rootPanelGroup%2522%253A%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clheryg3i00z3356lq12hxizh%2522%257D%255D%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS_PANELS%2522%257D%252C%2522tabbedPanels%2522%253A%257B%2522clheryg3i00z3356lq12hxizh%2522%253A%257B%2522id%2522%253A%2522clheryg3i00z3356lq12hxizh%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522id%2522%253A%2522clhes0d6l01go356lvx2x3s0w%2522%252C%2522taskId%2522%253A%2522build%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clhes0d6l01go356lvx2x3s0w%2522%257D%257D%252C%2522showSidebar%2522%253Atrue%252C%2522showDevtools%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%252C%2522editorPanelSize%2522%253A41.68257051007683%252C%2522devtoolsPanelSize%2522%253A41.442795629349064%257D

### To Reproduce

https://github.com/antoineol/repro-next-lazy-build-size

`yarn build`, you will get:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/6078211/236819994-6b5ea3ca-0dec-4a40-be0f-cf437685bfb7.png">

Open `app/page.tsx`, comment this line:

```tsx
const DynamicHeavy = lazy(() => import("./DynamicHeavy"));
```

Then build again. You will get:

<img width="344" alt="image" src="https://user-images.githubusercontent.com/6078211/236820247-e78031b1-9dd6-41c5-b5ae-c4a5cd1519bc.png">

Same result if using the `dynamic` wrapper instead of `lazy`.

### Describe the Bug

My understanding is that the "First Load JS" is the minimal bundle size to render the page, excluding lazy-loaded content that are in separate chunks, and counted separately. I expect "First Load JS" to be what matters for a quick initial rendering to improve the lighthouse score.

In this experimentation, lazy does not seem to reduce this initial bundle size. It behaves like a traditional "import" that includes everything in the initial bundle.

Unless I'm missing something?

### Expected Behavior

The "First Load JS" remains the same, with or without this line commented:

```tsx
const DynamicHeavy = lazy(() => import("./DynamicHeavy"));
```

Since I would expect it to he a separate chunk, not counted in the initial render.

**Comment by ethanryan** [comment]
@antoineol try adding `ssr: false` to your dynamic import:

```
const DynamicHeavy = lazy(() => import("./DynamicHeavy"), {ssr: false});
```

see docs: 

> [Skipping SSR](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#skipping-ssr)
> When using React.lazy() and Suspense, client components will be pre-rendered (SSR) by default.
> 
> If you want to disable pre-rendering for a client component, you can use the ssr option set to false:
> ```
> const ComponentC = dynamic(() => import('../components/C'), { ssr: false });
> ```

via: https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading#skipping-ssr

**Comment by antoineol** [comment]
Using `dynamic` with `ssr: false` doesn't seem to change the JS load size in the build :(

<img width="916" alt="image" src="https://github.com/vercel/next.js/assets/6078211/85a22e7e-1e29-4391-bef7-dd3792a42114">

---

[CodeSandbox link](https://codesandbox.io/p/github/antoineol/repro-next-lazy-build-size/main?file=%2Fapp%2Fpage.tsx%3A7%2C22-7%2C29&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhhigdr801lu356kjvvft0ps%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhhigdr801lw356keari4muj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clhhigdr801lu356kjvvft0ps%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clhhigdr801lt356krlbp89na%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A29%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clhhigdr801lu356kjvvft0ps%2522%252C%2522activeTabId%2522%253A%2522clhhigdr801lt356krlbp89na%2522%257D%252C%2522clhhigdr801lw356keari4muj%2522%253A%257B%2522id%2522%253A%2522clhhigdr801lw356keari4muj%2522%252C%2522activeTabId%2522%253A%2522clhhihd2102bz356kloi3j1ti%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clhhign2w01xe356k9729hcsv%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clhhigprl026p356kfu3q3owe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522id%2522%253A%2522clhhihd2102bz356kloi3j1ti%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Am I missing something?

I remember I read that `lazy()` was the recommended approach over `dynamic`, but I can't find the mention. Was it removed?

Assuming the SSR is what would make the trick, does activating the SSR have any noticeable negative impact, e.g. on lighthouse score, initial bundle size, user experience...? It sounds like doing as much as possible in SSR is the Next.js way, so I'm wondering if it is at the cost of a bigger initial bundle size. Or if it is just the build tool which prints irrelevant (or harmless) sizes.

> Also, based on your before and after screenshots, your homepage size and first load JS is decreasing.

Before = with lazy import, after = without any import. So yes, it's aligned with the bug (to clarify, I should have reverted the order).

**Comment by ethanryan** [comment]
does the "first load JS shared by all" number change? i see above, it is 76.9 kB.

is it smaller when using a dynamic import? 

next/dynamic is what you should be using, and add `ssr: false` if what is being imported is a component that isn't needed for server-side rendering, for example, something that won't help with SEO. 

https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-no-ssr

```
import dynamic from 'next/dynamic';
 
const DynamicHeader = dynamic(() => import('../components/header'), {
  ssr: false,
});
```

**Comment by antoineol** [comment]
> does the "first load JS shared by all" number change?

No, "first load JS shared by all" does not change. Only the "First Load JS" of the page, depending on what's imported.

> you're not rendering that imported component anywhere

True, for the minimal reproduction, just importing (lazily) was enough to increase the "First Load JS", even without any usage. Using the component doesn't change it.

---

It sounds like the issue is still there:

> Using `dynamic` with `ssr: false` doesn't seem to change the JS load size in the build :(
> 
> <img alt="image" width="916" src="https://user-images.githubusercontent.com/6078211/237349384-85a22e7e-1e29-4391-bef7-dd3792a42114.png">

Any idea about what could be wrong?

- Is it normal to have that huge "First Load JS", although I'm using dynamic + no ssr (cf [latest sandbox](https://codesandbox.io/p/github/antoineol/repro-next-lazy-build-size/main?file=%2Fapp%2Fpage.tsx%3A7%2C22-7%2C29&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhhigdr801lu356kjvvft0ps%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clhhigdr801lw356keari4muj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clhhigdr801lu356kjvvft0ps%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clhhigdr801lt356krlbp89na%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A29%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%257D%255D%252C%2522id%2522%253A%2522clhhigdr801lu356kjvvft0ps%2522%252C%2522activeTabId%2522%253A%2522clhhigdr801lt356krlbp89na%2522%257D%252C%2522clhhigdr801lw356keari4muj%2522%253A%257B%2522id%2522%253A%2522clhhigdr801lw356keari4muj%2522%252C%2522activeTabId%2522%253A%2522clhhihd2102bz356kloi3j1ti%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clhhign2w01xe356k9729hcsv%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clhhigprl026p356kfu3q3owe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522id%2522%253A%2522clhhihd2102bz356kloi3j1ti%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D))?
- If not, anything I can try to get back to the initial 82 kB while still lazy-loading components?

Thanks for your help!

**Comment by pewallin** [comment]
We're seeing something similar. We are consuming svg libs with a custom Icon-component where we pass name and then use an object built up by next/dynamic values for the actual svg icon. With the app dir enabled these svgs end up as part of one of the main bundles, without it into separate bundles per file (as intended). I've experimented a bit and it seems like next/dynamic loaded components referenced from a sever component will find it's way into one of the client js bundles.

**Comment by DK-Stern** [comment]
I have the same issue.
I have a client component which imports videojs. If i try to lazy load my client component with dynamic or react lazy, my client component is part of my page bundle, even if my client component is not rendered on page. With page router it works as expected.

Project with lazy load and app router:

```
Route (app)                                Size     First Load JS
┌ λ /                                      0 B                0 B
├ ○ /_not-found                            0 B                0 B
└ λ /[lang]/[...slug]                      189 kB          273 kB
+ First Load JS shared by all              77.7 kB
  ├ chunks/30-4ccb14782f155261.js          25.2 kB
  ├ chunks/fafd0397-71f37467b7d59c6b.js    50.5 kB
  ├ chunks/main-app-6838a55df8afa3de.js    215 B
  └ chunks/webpack-ff5e6d03dffd593b.js     1.79 kB
```

Same project with lazy load and page router:
```
Route (pages)                              Size     First Load JS
┌   /_app                                  0 B            84.9 kB
├ λ /[...slug]                             31 kB           116 kB
├   └ css/bbe34a0f0511bdf3.css             1.08 kB
├ ○ /404                                   280 B          85.2 kB
└ ○ /500                                   283 B          85.2 kB
+ First Load JS shared by all              87.4 kB
  ├ chunks/framework-2647c7e378e02044.js   45.2 kB
  ├ chunks/main-3604bd5040fa8c54.js        27.7 kB
  ├ chunks/pages/_app-32d8dc03914cc684.js  9.83 kB
  ├ chunks/webpack-3d5f4964a2af1dd8.js     2.13 kB
  └ css/a4966c8e561ff6c3.css               2.53 kB
```

**Comment by ivan-kleshnin** [comment]
I observe the same behavior in older NextJS without Server components. `dynamic` components are bundled (regardless of `{ssr: true}` which is not even expected to affect bundling, btw, not sure why it's mentioned...)

Which means `dynamic` does not actually work as code splitter 😨

**Comment by alex-krasikau** [comment]
Want to share my observations on this topic.

I created a demo using the latest 13.5.2 Next.js and App Router:
- [Code](https://github.com/alex-krasikau/next-lazy-loading)
- [Demo](https://next-lazy-loading-alex-krasikau.vercel.app/)

The application has a dynamic route segment that renders pages based on the configuration from the JSON file. In the application, I implemented 5 base sections used as building blocks for the pages:
1. Light Server Component - plain text
2. Heavy Server Component - receives a large payload
3. Light Client Component - server + client component that renders plain text
4. Heavy Client Component - server + client component that renders react-select
5. Heavy Client Component 2 - server + client component that renders @dotlottie/react-player

I implemented lazy loading for both Heavy Components:
- Heavy Client Component dynamically loads the Client Component from the Server Component (this doesn't split the bundle).
- Heavy Client Component 2 dynamically loads the Library from the Client component (this does split the bundle).

<img width="1343" alt="image" src="https://github.com/vercel/next.js/assets/97882909/87ad56a2-491e-4018-a33c-d61c5297b14b">

I tested different configurations of the pages, and I found that bundle splitting works only when dynamically loading the components from the client:

![image](https://github.com/vercel/next.js/assets/97882909/45a515a2-e161-45e3-bf95-f4bb121431a9)

**Comment by qqpann** [comment]
having the same problem with app router

**Comment by qqpann** [comment]
It's a wired behavior (and not well documented), but I stopped dynamic import from ssr and extracted to a client side file it worked.

Before (600KB first load js):
```
1. app/specific/page.tsx # "use server". dynamic import form from here.
2. components/form.tsx # "use client"
```

After (80KB first load js):
```
1. app/specific/page.tsx # "use server". import dynamic-wrapper.tsx
2. components/dynamic-wrapper.tsx # "use client". dynamic import form.tsx from here.
3. components/form.tsx # "use client"
```

**Comment by SushantLoop** [comment]
Experiencing the same issue in next 13 using app router

**Comment by jacekkuczynski** [comment]
> It's a wired behavior (and not well documented), but I stopped dynamic import from ssr and extracted to a client side file it worked.
> 
> Before (600KB first load js):
> 
> ```
> 1. app/specific/page.tsx # "use server". dynamic import form from here.
> 2. components/form.tsx # "use client"
> ```
> 
> After (80KB first load js):
> 
> ```
> 1. app/specific/page.tsx # "use server". import dynamic-wrapper.tsx
> 2. components/dynamic-wrapper.tsx # "use client". dynamic import form.tsx from here.
> 3. components/form.tsx # "use client"
> ```

that works for me; however, there is still an issue with PSI (google pagespeed insights or lighthouse):


using wrapper with a dynamic inside client component with ssr:false

Route (app)                              Size     First Load JS
┌ λ /                                    36.3 kB         152 kB
└ λ /_not-found                          883 B          81.5 kB
+ First Load JS shared by all            80.6 kB
  ├ chunks/864-0b213d31e832b6bb.js       27.5 kB
  ├ chunks/fd9d1056-7aefd8da81a6c06f.js  51 kB
  ├ chunks/main-app-8f13c08947745519.js  234 B
  └ chunks/webpack-1e90f92f40d0d340.js   1.92 kB

![Screenshot from 2023-10-08 16-45-42](https://github.com/vercel/next.js/assets/86817239/48634c3b-dd47-4357-b5bf-0891844843f3)

  
without an element at all:
  
  Route (app)                              Size     First Load JS
┌ λ /                                    35.8 kB         152 kB
└ λ /_not-found                          883 B          81.3 kB
+ First Load JS shared by all            80.5 kB
  ├ chunks/864-e7cea71e9d7bf99a.js       27.5 kB
  ├ chunks/fd9d1056-f55a7501bef01e1e.js  51 kB
  ├ chunks/main-app-8f13c08947745519.js  234 B
  └ chunks/webpack-896863269213614c.js   1.77 kB

![Screenshot from 2023-10-08 16-53-22](https://github.com/vercel/next.js/assets/86817239/a12dd694-609d-4b32-9366-17da371df00f)


without wrapper - using a dynamic in server component with ssr:false:
Route (app)                              Size     First Load JS
┌ λ /                                    244 kB          360 kB
└ λ /_not-found                          883 B          81.4 kB
+ First Load JS shared by all            80.5 kB
  ├ chunks/864-0b213d31e832b6bb.js       27.5 kB
  ├ chunks/fd9d1056-7aefd8da81a6c06f.js  51 kB
  ├ chunks/main-app-8f13c08947745519.js  234 B
  └ chunks/webpack-ccd32fcfcf42f8bb.js   1.83 kB

![Screenshot from 2023-10-08 16-29-27](https://github.com/vercel/next.js/assets/86817239/761ea66d-1ad1-478a-a3b7-4b79c699c7a2)

**Comment by marekmiotelka** [comment]
it's kind of a joke that at least since May code splitting doesn't work in NextJS app directory. We are now on version 14.0.1, app router is recommended for all new applications since May, (v13.4.0 right?) and core features don't work at all (code splitting, cache & revalidation (fixed in 14.0.2-canary.3 tho, finally)). 2.4k open issues and Vercel is focusing on server actions that are just a sugar layer on top of the api routes. Like... seriously?

Let's imagine any app that has a CMS - currently EVERY SINGLE PAGE, no matter if renders 1 component or 100, gets the same, huge bundle with all components included.

Like seriously, using Next stopped to be fun with version 13, as most of the development time is spend on debugging the newly introduced bugs or discovering that core features that worked since v1.0.0 now just don't and no ones gives a s**t about it for half of the year.
I get that you want to introduce new features, Server Actions looks nice, but for God's sake - first make sure the core features are working properly and issues relating core features are not left open for half of the year.

I don't know what are your processes of development, but would be nice to revisit them, as almost every new update introduces more bugs than it fixes.

App router is not stable and shouldn't be used by any project larger than a landing page.

PS: code split works fine with pages directory (v14.0.1).

**Comment by SergiuGrisca** [comment]
For me in the pages dir is not working even, or I don't understand something

how it is possible that lighthouse is complaining about not used js, if that component is with dynamic import and ssr: false ?

**Comment by manuelseisl** [comment]
Experiencing the same issue in app router. It's not possible to use app router for large apolication, because Pagespeed performance is really bad, when using many components.

**Comment by levipadre** [comment]
Same issue here. CMS, all content is dynamic, and the page is slow (not just page speed numbers, but visible too for the eyes). We need a solution for dynamic import, suspense, lazy load, file sizes

**Comment by rharrisuk** [comment]
Exact same issue here. This is preventing me from using Next in any production site and as I see it, is not fit for purpose. 

This issue has been open over 6 months now and it would be nice to know if it isn't being worked on so I can look for an alternative framework. If it is then why the lack of communication?

**Comment by huozhi** [comment]
Hi, sorry for the late response, definitely missed the discussion here as there're too many issues atm. Wanna share a bit more that how can you do code-splitting better.

### Solution

If we look at the reproduction case that shared in the issue description, it's using `next/dynamic` call in the server components, loading a client component. The quick way to make code splitting work is to use `next/dynamic` in client components.

```
page.js -> client component using `next/dynamic` -> module to load in splitting chunk
```

So you could either add a client component in between the module you're loading or mark the page.js as client component if that works for you.

### Why

Calling `next/dynamic` with client component in server component is so far not able to do code splitting. It's like you're trying to code splitting in server components where you might not worry about the chunks size especially when you want those async loaded chunks to be loaded on client. So you need to move them to a client component and call `next/dynamic` there to split the module you'd like to separate into other chunks.

Using `next/dynamic` in server components that loading a client component is still including everything in server side rendering, and that client component doesn't know it needs to be split into another chunk in browser chunks.

We'll improve the education resource to make it more clear and any feedback to it is welcomed, thanks
