### ISSUE TITLE
[NEXT-1337] Parallel routes keep refreshing in DEV in next 13.4.7

### ISSUE THREAD

**Issue by Fredkiss3** [vercel/next.js#51951]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103
    Binaries:
      Node: 18.16.0
      npm: 9.5.1
      Yarn: 1.22.19
      pnpm: 8.6.2
    Relevant Packages:
      next: 13.4.8-canary.8
      eslint-config-next: N/A
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 4.9.4
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

App directory (appDir: true)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/Fredkiss3/infinite-reload-parallel-routes-bug

### To Reproduce

1. Run the DEV server and go to `http://localhost:3000`
2. Watch as the color of the text keep changing every couple of seconds

### Describe the Bug

In the  latest version of next (`13.4.7`) and even on the latest canary, when we use parallel routes, they get refreshed every couple of seconds without doing any action in DEV, i've noticed that everytime the websocket used by next for HMR does  does a ping, next refresh the page and the server code is reexecuted.  

I've tested with the previous version (`13.4.6`) and it worked fine.

### Expected Behavior

The parallel route should not refresh every couple of seconds.

<sub>[NEXT-1337](https://linear.app/vercel/issue/NEXT-1337/parallel-routes-keep-refreshing-in-dev-in-next-1347)</sub>

**Comment by nicksan222** [comment]
As described in the [documentation](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes)

> Parallel routes are created using named slots. Slots are defined with the @folder convention, and are passed to the same-level layout as props.
Slots are not route segments and do not affect the URL structure. The file path /@team/members would be accessible at /members.

Maybe you should try to move the layout to the folder level as the @parallel

Might be wrong let me know if that works since i never used parallels directly

**Comment by m10rten** [comment]
Moving the layout won't fix it, perhaps making some `"use client";`
And I have no idea what that randomColor thing does, but try removing that?

**Comment by Fredkiss3** [comment]
@m10rten `randomColor` does not do anything particular, it is just a package that generates a random rgb color, it is there for demo purposes to see the bug more clearly.

**Comment by nicksan222** [comment]
So i fixed the issue.

The things i did were:

- Created a page.tsx file on `app` folder
```tsx
// page.tsx

export default function Page() {
    return <div></div>
}
```

- Modified the `layout.tsx` like this
```tsx
import * as React from "react";

export default function RootLayout({
  children,
  parallel
}: {
  children: React.ReactNode,
  parallel: React.ReactNode;
}) {
  return (
    <html>
      <head />
      <body>
        <h2>ROOT LAYOUT</h2>
        {parallel}
      </body>
    </html>
  );
}
```

I guess children must always be the first argument, kind of a reserved keywork

**Comment by m10rten** [comment]
not having a root page should not have been the issue though.

**Comment by Fredkiss3** [comment]
Thank you @nicksan222 , i've tested and the fix is to simply add a `page.tsx` at the same level as the layout, no need to add `children` to the `layout.tsx` file : 

```tsx
// app/page.tsx

export default function Page() {
  return null;
}
```
The weird thing is that this did not happen with `next@13.4.6` and only with the latest version. If this is an evolution and it is needed in new versions, it should be documented in my opinion. 


However i followed the [guide on the docs](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes#conditional-routes) which did not mention the use of a root page, and since it worked in the versions before, i am more inclined to say this is a bug, i may be wrong though.

**Comment by feedthejim** [comment]
will take a look on Monday, I think I broke it in #51604

**Comment by tnoor-co** [comment]
Please advise if I should open another issue or if we can continue the conversation here. I'm still experiencing infinite refreshing when a default.tsx page is rendered inside a parallel route. Here's the repo with a minimal example: https://github.com/tnoor-co/next-infinite-parallel-refresh

**Comment by Fredkiss3** [comment]
cc @feedthejim , this issue is still not totally fixed, there are some edge cases like here : https://github.com/vercel/next.js/pull/52061#issuecomment-1622931149 i'm still hitting this one.

**Comment by MostafaKMilly** [comment]
I still have the issue on 13.4.9 
<img width="955" alt="Screenshot 2023-07-09 at 6 59 14 AM" src="https://github.com/vercel/next.js/assets/57003058/d5125bbf-b3ba-435b-8c44-d00f41ba92d7">

**Comment by timneutkens** [comment]
@MostafaKMilly can you provide a reproduction?
