### ISSUE TITLE
Api route req on close event not triggered when request is cancelled

### ISSUE THREAD

**Issue by jbojcic1** [vercel/next.js#52809]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #22 SMP Tue Jan 10 18:39:00 UTC 2023
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: N/A
    Relevant Packages:
      next: 13.4.10-canary.8
      eslint-config-next: 13.4.8
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.0.4
    Next.js Config:
      output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime)

### Link to the code that reproduces this issue or a replay of the bug

https://codesandbox.io/p/sandbox/blissful-driscoll-y78mrd

### To Reproduce

1. open the link from above
2. click on "Trigger API call" button
3. click on "Cancel API call" button and note in browser network tab that the request which was previously pending is now cancelled
4. note how `req.on("close"` event handler didn't run and API route work is still being done

### Describe the Bug

Request close event is not firing in the API route when the caller cancels the request

### Expected Behavior

Request close event should be fired so that any necessary cleanup can be done

**Comment by masterkain** [comment]
perhaps related https://github.com/vercel/next.js/pull/52281

**Comment by jbojcic1** [comment]
I also just noticed that `req.destroyed` is set to true immediately in the API route handler (see the log I just added to the same demo). Isn't that supposed to be true only if the request was forcefully closed (e.g. cancelled by the client)?

**Comment by jridgewell** [comment]
> I also just noticed that `req.destroyed` is set to true immediately in the API route handler (see the log I just added to the same demo). Isn't that supposed to be true only if the request was forcefully closed (e.g. cancelled by the client)?

`request` is destroyed when the stream's data is fully read into the program, which happens automatically because Next provides you with a [req.body](https://github.com/vercel/next.js/blob/a26bac96048c7231271b5947eaf80241e94ca2fc/packages/next/src/server/api-utils/node.ts#L553-L560). If the stream data isn't read, then it's also destroyed when the client disconnects.

`response` is only destroyed when the client disconnects, so it's the one you should use for the disconnect signal.

So, this is working as intended. `req.on('close', cb)` will never invoke the callback, because the request is already closed. Try using `res.on('close')` instead, and possibly listening to `'end'` event as well if you want to distinguish the client closing the stream from you ending the response with `res.end()`.

**Comment by jbojcic1** [comment]
> `request` is destroyed when the stream's data is fully read into the program, which happens automatically because Next provides you with a [req.body](https://github.com/vercel/next.js/blob/a26bac96048c7231271b5947eaf80241e94ca2fc/packages/next/src/server/api-utils/node.ts#L553-L560). If the stream data isn't read, then it's also destroyed when the client disconnects.

@jridgewell I see. Thx for the explanation. However, not even `res.on('close')` is emitting. I've updated my example to demonstrate. You can see in the network tab that hitting cancel API call cancels the request but server logs don't show that close event is emitted

**Comment by jbojcic1** [comment]
also if I disable bodyParser request destroyed and closed are false but still when the request is cancelled by the client request closed is not emitted + destroyed and closed flags stay false. Example of this can be seen [here](https://codesandbox.io/p/sandbox/vibrant-wiles-nymnvf)

**Comment by jridgewell** [comment]
Strange, I'm not sure why the close event isn't firing.

**Comment by jridgewell** [comment]
[Confirmed](https://codesandbox.io/p/sandbox/gifted-keldysh-66cvyq?file=%2Fapp%2Fpage.tsx%3A49%2C8), by writing to the response it will eventually get the close signal (and a few modifications to the client code, because you're immediately `setRunning(false)` in the `makeApiCall` function). I'll get this fixed in https://github.com/vercel/next.js/pull/52281

**Comment by tangye1234** [comment]
When invoking the response piping in the Node server, special attention should be paid to the issue of backpressure.

I highly recommend using the node Readable.from(iterable) method to obtain the readable stream, and then using the node stream.pipe method to pipe the readable stream to the outgoing stream.

**Comment by jbojcic1** [comment]
@ijjk @jridgewell I don't think the issue is fixed. I've updated [my example](https://codesandbox.io/p/sandbox/blissful-driscoll-y78mrd) to use 13.4.13 but I still see the same issue

**Comment by bkrausz** [comment]
This now works in dev, but we're still seeing it not working in standalone production builds. I'm digging into the cause but wanted to give a heads up.

**Comment by jridgewell** [comment]
> I've updated [my example](https://codesandbox.io/p/sandbox/blissful-driscoll-y78mrd) to use 13.4.13 but I still see the same issue. [Here](https://codesandbox.io/p/sandbox/gifted-keldysh-66cvyq?file=%2Fapp%2Fpage.tsx%3A49%2C8) is also the @jridgewell's updated version which also shows that it's not fixed

Given that this works in dev, I think it might be CodeSandbox's servers that are breaking it. Even an [app route handler](https://codesandbox.io/p/sandbox/serene-neumann-vgwq4w) doesn't work.

> This now works in dev, but we're still seeing it not working in standalone production builds

Are you deploying to Vercel? It was pointed out to me yesterday that we don't support [streaming Pages API](https://vercel.com/docs/concepts/functions/edge-functions/streaming#streaming-data-with-edge-functions:~:text=Streaming%20responses%20is,using%20Route%20Handlers.) when running the nodejs runtime. I'm trying to bring this up to the team, and I'll see if we can fix that.

**Comment by bkrausz** [comment]
> Are you deploying to Vercel? It was pointed out to me yesterday that we don't support [streaming Pages API](https://vercel.com/docs/concepts/functions/edge-functions/streaming#streaming-data-with-edge-functions:~:text=Streaming%20responses%20is,using%20Route%20Handlers.) when running the nodejs runtime. I'm trying to bring this up to the team, and I'll see if we can fix that.

We're using a standalone NodeJS build that we deploy to GCP cloud run, and we're on app, not pages. If you think that should work I can try to make a minimal repro.
