### ISSUE TITLE
Server side locale always default in dynamic routes when a middleware is present

### ISSUE THREAD

**Issue by XavierLasierra** [vercel/next.js#54217]
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000
Binaries:
  Node: 18.8.0
  npm: 8.18.0
  Yarn: 1.22.19
  pnpm: N/A
Relevant Packages:
  next: 13.4.18-canary.0
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```

### Which area(s) of Next.js are affected? (leave empty if unsure)

Middleware / Edge (API routes, runtime), Routing (next/router, next/navigation, next/link)

### Link to the code that reproduces this issue or a replay of the bug

https://github.com/XavierLasierra/next-dynamic-routes-bug

### To Reproduce

1. Clone repository, install dependencies and start the server
2. Go to the main page with a locale other than the default (ex `/en`)
3. Navigate to a dynamic route using `next/link`
4. The locale on the server side will be always the default one only when doing client navigation

### Describe the Bug

When doing client side navigation to a dynamic route having a `middleware.js` file, the locale will always be the default one.

````
export const getServerSideProps = async ({ locale }) => {
  return {
    props: {
      locale, // Always default with client side navigation
    },
  };
};
````

- This is not happening for static routes.
- This is not happening for dynamic routes with no `middleware.js` file.

### Expected Behavior

The locale will be consistent in dynamic routes.

### Which browser are you using? (if relevant)

Chrome 115.0.5790.170

**Comment by lkappeler** [comment]
We are facing the same issue using a global middleware file on the project. The locale passed to the `getServerSideProps` is the default locale.

We are using the locale for a subsequent request inside the `getServerSideProps` function. As a temporary workaround, I parsed the locale from the invoke path header so we can use it for our internal request. I thought it might be handy for someone.

```
const isValidLanguage = (value: string | null): value is Language => {
  if (!value) return false;

  return languages.includes(value as Language);
};


export const parseLocaleWithHeaderFallback = ({
  req,
  locale,
}: {
  req: IncomingMessage;
  locale: string;
}): Language => {
  if (locale !== 'default' && isValidLanguage(locale)) return locale;

  const headerValue = req.headers['x-invoke-path'];
  const [xInvokePath] = Array.isArray(headerValue)
    ? headerValue
    : [headerValue];
  const [parsedLocale] = xInvokePath
    ? xInvokePath.substring(1).split('/')
    : [null];

  if (isValidLanguage(parsedLocale)) return parsedLocale;

  Sentry.captureException(new Error('Could not derive locale from request header'), {
    extra: { req },
  });
  return 'de';
};
```

next.config.js
```
...
  i18n: {
    locales: ["default", "en", "de"],
    defaultLocale: "default",
  },
  ...
  ```

**Comment by avitslv** [comment]
Having the same issue when middleware file present. Problem is since v13.4.13.  
We have multi locale setup. Navigating pages with `next/link` getting 404 page not found, because `getStaticProps` is getting the default locale.

**Comment by lauripiispanen** [comment]
`git bisect` reveals commit 1398de9977b89c9c4717d26e213b52bc63ccbe7e to be the culprit. Not sure how helpful it is in pinpointing the actual cause since it's such a big merge commit, but it would seem that middleware URL normalization is leaking downstream and breaks locale handling for internal `_next` requests.

Workaround: enabling the `skipMiddlewareUrlNormalize` flag for the middleware seems to revert to the old behavior. i.e. add this config to your `middleware.ts`:

```
export const config = {
  skipMiddlewareUrlNormalize: true,
}
```

**Comment by emilioschepis** [comment]
Same issue here. We'll revert to 13.4.12 for the time being, let us know if we can provide any more info to help troubleshooting.

**Comment by lx-maxhaslehner** [comment]
We also ran into a similar problem when updating Next.js which broke our internationalization strategy. We´ll also keep using 13.4.12 for the moment.

**Comment by SanderRuusmaa** [comment]
Yup, after updating from 13.4.12 to 13.4.13+, the [internationalization strategy](https://nextjs.org/docs/pages/building-your-application/routing/internationalization#prefixing-the-default-locale) breaks. getServerSideProps gets "default" as the passed locale.

Hopefully this gets looked into soon.

**Comment by raRaRa** [comment]
Wow, this bug was annoying me today. Downgrading to 13.14.12 fixed it. I use two languages, 'is' and 'en', where 'en' is the default one. If I open /is/ then the page opens in Icelandic. If I open it dynamically with Link, then it uses the default locale. Refreshing the page makes it work. I wonder if this is also a bug on prod?

**Comment by raRaRa** [comment]
In my case I have a middleware with a matcher of specific URLs. The middleware is not even run for the pages where this issue happens. But removing the middleware fixes it.

**Comment by raRaRa** [comment]
I wonder if this PR fixes it: https://github.com/vercel/next.js/pull/54357

**Comment by vinnycodes** [comment]
Any updates on this issue?
We're finding this issue on all of our pages that use getServerSideProps.

According to nextjs docs, "default" should be added for prefixing locale. 
Now "default" is what is being passed to all of our link components that do no explicitly state what the locale is.

**Comment by raRaRa** [comment]
Still broken in 13.5.1

**Comment by SanderRuusmaa** [comment]
Upgrading to 13.5.1 breaks the internationalization in a new way. The app gets stuck in a redirect loop when trying to navigate to the app's root ("/" or "/en" or "/et").

Seems to me that the automatic locale prefixing is still broken and 13.4.12 is still the last working version for me. Either some logic was changed and the Docs is not updated or it's just bugging out still.

```
//next.config.js (by the book, according to docs)
const nextConfig = {
  reactStrictMode: true,

  i18n: {
    locales: ['default', 'en', 'et'],
    defaultLocale: 'default',
  },

}

module.exports = nextConfig
```

```
//middleware.ts (by the book, according to docs)
import { NextRequest, NextResponse } from 'next/server'

const PUBLIC_FILE = /\.(.*)$/

export async function middleware(req: NextRequest) {
	if (
		req.nextUrl.pathname.startsWith('/_next') ||
		req.nextUrl.pathname.includes('/api/') ||
		PUBLIC_FILE.test(req.nextUrl.pathname)
	) {
		return
	}
        
        // automatic locale prefixing
	if (req.nextUrl.locale === 'default') {
		const locale = req.cookies.get('NEXT_LOCALE')?.value || 'en'

		return NextResponse.redirect(
			new URL(`/${locale}${req.nextUrl.pathname}${req.nextUrl.search}`, req.url)
		)
	}
}
```

network tab when routing to "/":
![image](https://github.com/vercel/next.js/assets/56891593/59f9725c-7b58-4573-8248-234745948bd6)

**Comment by gijsbotje** [comment]
Facing the same issue. Upgraded tot 13.5.2 from 13.3.1. Server always has the default locale when routing via a NextLink. Reloading the page does give the correct locale.

**Comment by raRaRa** [comment]
It's really worrying that this has been an issue for such a long time without Vercel taking any action. This breaks so many websites that support multiple locales + have middleware file present (very common as well).

**Comment by danielkoller** [comment]
We have the same issue as well. Downgrading to 13.3.1 for now.

**Comment by jeremymarc** [comment]
same issue here...

**Comment by Zerebokep** [comment]
Same issue here, upgrading > 13.4.19 breaks the app with the 307 redirect loop.

**Comment by thany** [comment]
Same issue. I couldn't fathom this to be a bug, since it seems to basic and so easily (regression-)testable at Vercel's end.

So I started [this discussion](https://github.com/vercel/next.js/discussions/56040). No responses yet, at the time of writing, unfortunately.

I spent another 2 hours stepping through internal Next.js code, and I couldn't find any place where the locale definitely gets reset to default. Even knowing the middleware mechanism is the culprit, it still didn't help to figure out how, where, and why this is happening.

I'm also very interested to how this could've slipped through QA at Vercel. Since i18n seems like a pretty important feature, I would assume it goes through some sort of testing. Maybe not good enough then.

**Comment by gijsbotje** [comment]
@thany I would also assume such a feature has the proper tests in place. It might be because the app router doesn't provide out of the box i18n routing that this slipped through. I believe the app router is the main focus, which is quite clear as no one from vercel or the next team has replied about this issue yet.

**Comment by raRaRa** [comment]
Still an issue in 13.5.4 - reverting to 13.4.12 works.

**Comment by avitslv** [comment]
> Having the same issue when middleware file present. Problem is since v13.4.13. We have multi locale setup. Navigating pages with `next/link` getting 404 page not found. The page is in `en` locale. In middleware `req.nextUrl.locale` is `en`, but in `getStaticProps` the `context.locale` is the default locale - e.g.`de`.

We updated the project to next 13.5.4, and now both in middleware and in pages `getStaticProps` the correct `locale` value is provided, not always the default.

**Comment by avitslv** [comment]
> Having the same issue when middleware file present. Problem is since v13.4.13. We have multi locale setup. Navigating pages with `next/link` getting 404 page not found. The page is in `en` locale. In middleware `req.nextUrl.locale` is `en`, but in `getStaticProps` the `context.locale` is the default locale - e.g.`de`.

We updated project to use next v13.5.4, and now both in middleware and page `getStaticPaths` getting the correct `locale` values, not always the default locale.

**Comment by raRaRa** [comment]
> The same issue of infinite redirects occurred, so I downgraded from version `v13.5.4`-> `v13.4.12`.
> 
> Is there a solution?

Unfortunately not, unless you remove the middleware file.

**Comment by odincov** [comment]
v13.5.4 works for here as expected... Make sure you updated properly (check your lock file for the correct next version presence only), remove .next directory before running again, update your middleware file to contain the new config bit with a matcher.

**Comment by raRaRa** [comment]
> v13.5.4 works for here as expected... Make sure you updated properly (check your lock file for the correct next version presence only), remove .next directory before running again, update your middleware file to contain the new config bit with a matcher.

Doesn't work for me. Do you have a middleware present in your pages folder and are you using the pages folder? All client-side routing returns the default locale for me in 13.5.4. I've deleted ./.next & ./node_modules, etc. Still no luck.

**Comment by odincov** [comment]
@raRaRa middleware has to be in the same directory as pages, yes i am using pages and the middleware file is present...

Check your paths, make sure locale is outside of params `{ params: { slug }, locale }` etc... Good luck.

**Comment by raRaRa** [comment]
That's precisely how I do it.

```
export async function getStaticProps({
  params,
  locale,
  previewData,
}: GetStaticPropsContext) {
```

Locale defaults to en.

```
  i18n: {
    locales: ["en", "is"],
    localeDetection: false,
    defaultLocale: "en",
  },
```

If I navigate to some URL with Nextjs <Link> on client-side, such as `/is/test`, locale becomes `en` in my `getStaticProps`, but if I refresh that page I get it as `is` (correct). So client-side navigation doesn't work on a locale different than the `defaultLocale`, but it works if I refresh the page (server-side navigation).

The middleware doesn't even run for those paths, it just needs to be present for this bug to appear. If I remove the middleware file it works. I tried console logging inside my middleware and it doesn't run for the path I tried. It only runs for certain paths which the matcher is configured to.

**Comment by mkataja** [comment]
> The same issue of infinite redirects occurred, so I downgraded from version `v13.5.4`-> `v13.4.12`.
> 
> Is there a solution?

Try with `localeDetection: false`. In our case 13.5.5 seems to work correctly but only with that option set.

**Comment by raRaRa** [comment]
Still broken in 13.5.5.

**Comment by rhkdgns95** [comment]
@mkataja 
> Try with localeDetection: false. In our case 13.5.5 seems to work correctly but only with that option set. Otherwise we get a redirect loop.


This is still an unresolved issue (v13.5.5)

What is unusual is that loops do not occur in local development, but issues do occur in the environment deployed after building.

**Comment by SanderRuusmaa** [comment]
> > The same issue of infinite redirects occurred, so I downgraded from version `v13.5.4`-> `v13.4.12`.
> > Is there a solution?
> 
> Try with `localeDetection: false`. In our case 13.5.5 seems to work correctly but only with that option set. Otherwise we get a redirect loop.

This fixes the redirect issue for us as well. But if the localeDetection is "true", then it keeps getting into the redirect loop.

This means that automatic locale prefixing with localeDetection is still broken in version 13.5.6... *sigh*

**Comment by raRaRa** [comment]
Does anyone know if this affects the App Router? I'm already thinking about migrating after watching Nextjs conf.

**Comment by gijsbotje** [comment]
@raRaRa As the app router doesn't have built in localized routes, it should not affect it. You'll need to create your own middleware to handle localization.

**Comment by pixelass** [comment]
It seems so be resolved with next v14.

**Comment by oleggrishechkin** [comment]
Looks like this issue resolved in v14+.

**Comment by SvetlioSS** [comment]
Not working for me with v14.0.1

**Comment by soulchild** [comment]
@leerob Do you guys even care about the fact you're introducing app-breaking bugs with minor-/patch-level upgrades affecting real users or are you too busy riding the app-router hype train? I for one will not consider Next.js for upcoming projects anymore, just because no client is willing to pay for countless hours of chasing down bugs that come with every upgrade of the underlying framework. No wonder people hate on the JS ecosystem if all they ever tried was Next.js. Express and plain React have served me well for a decade now with almost no surprises when upgrading. This right here is ridiculous.

**Comment by Mattgic** [comment]
I confirm the issue is still here on latest 14.0.3 version. It's a serious problem for us as we can't upgrade Next anymore, and won't be able to migrate to App Router anytime soon.

**Comment by soulchild** [comment]
Also, it took us days to even find out what the problem was: Our client reported the redirect loop and I was unable to reproduce it - neither on the production system nor on my local machine. I initially wrote it off as some reverse proxy fuckup on the client's side. Turns out, I had my locale set to the app's default locale which prevented the problem from showing up on my machine. 😞

**Comment by balthazur** [comment]
Facing the same problem, getStaticProps returns the default locale in dynamic routes with middleware file present (auth).

**Comment by balthazur** [comment]
Bug still present in [v14.0.5-canary.5](https://github.com/vercel/next.js/releases/tag/v14.0.5-canary.5)

**Comment by joaogarin** [comment]
Still facing this bug, its really worrying that no one in vercel seems to care about this one. This has been broken for many months and there is really no path forward since there is no real workaround. 

> Try with localeDetection: false. In our case 13.5.5 seems to work correctly but only with that option set

This doesn't really help in my case it seems. I still get really weird redirects even with this option set. We are pilling security vulnearbilities and other issues like https://github.com/vercel/next.js/issues/51263 which have been fixed but we can't update.

**Comment by raRaRa** [comment]
I would just do all the locale functionality manually, which will also help you migrate to app router in the future.

**Comment by angelovdev** [comment]
@leerob it has been more than 4 months since this issue was reported and there has been no communication from the team whatsoever.

**Comment by florianmutter** [comment]
I guess someone using a payed vercel product needs to open a support ticket or something to increase priority

**Comment by TrevorThomp** [comment]
Would love to see an update on this so we can upgrade to v14 for now we are pinned to v13.

**Comment by gabrielf** [comment]
I don't experience the "Server side locale always default in dynamic routes when a middleware is present" error when using next 14.1.0 in the minimal repo that reproduces the error: https://github.com/XavierLasierra/next-dynamic-routes-bug Both the 

But I do experience the redirect issue mentioned above unless I set `localeDetection: false` in the i18n-config.

I've performed this test:

1. Clone the repo above
2. Upgrade to next 14.1.0
3. Set `localeDetection: false` in `next.config.js`
4. Visit each locale (default, en, de) and each page (`/`, `/dynamic/1`, `/static`) both via link and reload

And all pages seem to show the correct locale.

Maybe someone who still experiences this error, even with next 14.1.0, can update the minimal repo to reproduce the error?

**Comment by balthazur** [comment]
I just tried 14.1.0. Client side navigation is working now without reload. I use localeDetection and I don't experience the redirect issue.

However, the locale in getStaticProps is always the default locale.

**Comment by ninjarogue** [comment]
We are facing the same issue with `14.0.4`. Why is this issue being ignored?

**Comment by MartinDavi** [comment]
@leerob This issue has a reproduction, what needs to happen to get a response from Vercel?

**Comment by evtaranov** [comment]
The problem is still relevant, and it seems that the development team has no plans to fix it.

**Comment by smatjes** [comment]
Just want to chime in and add that we also face this issue in a similar setup. Also blocking us from updating to > 13.4.12.

**Comment by florianmutter** [comment]
Might be fixed by #62606

**Comment by gabrielf** [comment]
I think this issue should be closed.

The bug as stated in the original issue: "Server side locale always default in dynamic routes when a middleware is present" using the original reproduction repo but updated to the latest next (14.1.4) does not show the bug.

With next 14.1.4 the endless redirect mentioned in the thread is also gone. I tried adding a Static Site Generation (SSG) page using `getStaticProps` also mentioned in the thread but it also got the correct locale both on client side navigation and on page reload.

There are other bugs related to i18n such as:
* https://github.com/vercel/next.js/issues/57704
* https://github.com/vercel/next.js/issues/61201

But the particular bug discussed in this thread seem to be solved.

I suggest that anyone that still sees this issue update the original reproduction repository https://github.com/XavierLasierra/next-dynamic-routes-bug or create a new, minimal one, that demonstrates the issue and submits a new issue or updates this one if you think its the same issue. 

Please remember that router (app/pages), middleware (present or matching/not present or matching), runtime (node/edge), i18n (on/off), server (npm run dev/npm run build + npm start/vercel/other) can all affect the behavior. If you see this problem in your app then there may be something in it that differs from the minimal reproduction.

**Comment by Thevyn** [comment]
Still have the same problem as @Mattgic

**Comment by gabrielf** [comment]
@Mattgic I tested your updated repo and can confirm that with the additional middleware config the bug is still present. Here is an updated bug report using the new template:

### Link to the code that reproduces this issue

https://github.com/Mattgic/next-dynamic-routes-bug

### To Reproduce

1. Clone repository, run `npm i && npm run dev`
1. Visit <http://localhost:3000/en>
1. Click the link `Dynamic 1`

### Current vs. Expected behavior

As I click the link I expect the locale to be `en` but it is `default`.

Reloading the page correctly shows the locale as `en`.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 18.18.2
  npm: 9.8.1
  Yarn: 1.22.22
  pnpm: 8.15.5
Relevant Packages:
  next: 14.3.0-canary.9 // Latest available version is detected (14.3.0-canary.9).
  eslint-config-next: N/A
  react: 18.2.0
  react-dom: 18.2.0
  typescript: N/A
Next.js Config:
  output: N/A
```


### Which area(s) are affected? (Select all that apply)

Internationalization (i18n), Middleware / Edge (runtime), Routing (next/router, next/link)

### Which stage(s) are affected? (Select all that apply)

next dev (local), next build (local), next start (local)

### Additional context

The bug seems to be triggered by pages router + i18n + middlware present with matcher config + dynamic route.

The example repo demonstrates the bug using a Server Side Rendered page but the bug is also present for a Static Site Generated page using `getStaticPaths` + `getStaticProps`.

**Comment by omgovich** [comment]
We have the same issue on our project (Next.js v14.2.4).

Almost a year since the bug appeared, **why is nobody fixing it?**

**Comment by omgovich** [comment]
> I am going to try replacing the config matcher with conditions inside the middleware (https://nextjs.org/docs/app/building-your-application/routing/middleware#conditional-statements), it should do the trick.

I have tried the same, but enabling `middleware` for all URLs breaks next.config.js `rewrites` (but we have a lot of them).

**Comment by thansk** [comment]
> Almost a year since the bug appeared, **why is nobody fixing it?**
> 
> P.S. I have reported the bug to "Pro Support" using my corporate Vercel account, but they said they can't help me with **my** Next.js problems.

I thought only Next.js is abandoned but it seems the company is abandoning its customers too.

**Comment by samcx** [comment]
Hi everyone,

We apologize for the length it has taken to respond to this issue.

I was not able to reproduce the issue when testing the <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> (https://github.com/XavierLasierra/next-dynamic-routes-bug) on the latest   [canary v15.0.0-canary.41](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.41) →

https://github.com/vercel/next.js/assets/28912696/e7b2630c-e176-4494-b7d0-fa3783679831

Let me know if you are able to confirm this or are seeing anything differently <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/frog-eyes/558eb9b0fd306c97.png" alt=":frog-eyes:" align="absmiddle"></picture>

**Comment by tjcampbell** [comment]
@samcx please see @Mattgic's comment above. The issue still exists when the middleware contains a matcher in the config. The repro middleware doesn't contain any config which is misleading.

**Comment by Mattgic** [comment]
I updated my repro repo to latest Next canary, bug still exists as previously said when middleware has a matcher.
https://github.com/Mattgic/next-dynamic-routes-bug

**Comment by samcx** [comment]
@tjcampbell @Mattgic 

This is the matcher I used in particular, and I can't replicate. <picture data-single-emoji=":frog-eyes:" title=":frog-eyes:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/frog-eyes/558eb9b0fd306c97.png" alt=":frog-eyes:" align="absmiddle"></picture> 

Uploading CleanShot 2024-06-27 at 18.03.07.mp4…

**Comment by tjcampbell** [comment]
@samcx you should be able to replicate it with the middleware CORS example, or with @Mattgic's repro.
https://nextjs.org/docs/pages/building-your-application/routing/middleware#cors

```ts
export const config = {
  matcher: '/api/:path*',
}
```

**Comment by samcx** [comment]
@tjcampbell Using @Mattgic's <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> with that config (not the CORS example). Cannot <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture>. 

https://github.com/vercel/next.js/assets/28912696/d4eb9e19-b089-47f3-a926-5d7d46c7bba8

**Comment by thansk** [comment]
> @tjcampbell Using @Mattgic's <img alt=":repro:" width="20" height="auto" src="https://camo.githubusercontent.com/294fcc016906904beb80b3c14e2252d0b6fef2711a1acb2afaac1c89b8427edc/68747470733a2f2f656d6f6a692e736c61636b2d656467652e636f6d2f5430434151303054552f726570726f2f356365613533623535333238323562342e706e67"> with that config (not the CORS example). Cannot <img alt=":repro:" width="20" height="auto" src="https://camo.githubusercontent.com/294fcc016906904beb80b3c14e2252d0b6fef2711a1acb2afaac1c89b8427edc/68747470733a2f2f656d6f6a692e736c61636b2d656467652e636f6d2f5430434151303054552f726570726f2f356365613533623535333238323562342e706e67">.
> CleanShot.2024-07-01.at.13.49.20.mp4

You are reproducing it. You pick English, you go to the dynamic page and it shows up as `default` which is wrong.

**Comment by samcx** [comment]
@thansk Oh my bad, I see your point, I was just looking at the URL <picture data-single-emoji=":lol:" title=":lol:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/lol/5986e156eca2154f.png" alt=":lol:" align="absmiddle"></picture>

**Comment by samcx** [comment]
@tjcampbell @thansk What's interesting, is I'm only seeing this locally.

- https://54217-next-dynamic-routes.vercel.app/de
- https://vercel.com/sams-igloo/54217-next-dynamic-routes/2txcBHg94BFFLHgJnJtps9U4fcN3/source
- https://vercel.com/sams-igloo/54217-next-dynamic-routes/2txcBHg94BFFLHgJnJtps9U4fcN3/logs?slug=app-future&slug=en-US&slug=sams-igloo&slug=54217-next-dynamic-routes&slug=2txcBHg94BFFLHgJnJtps9U4fcN3&slug=logs&page=1&timeline=past30Minutes&startDate=1719831345876&endDate=1719833145876
