### ISSUE TITLE
API routes returning a 405 on Vercel, fine in dev/local

### ISSUE THREAD

**Issue by wadehammes** [vercel/next.js#55667]
### Link to the code that reproduces this issue

https://codesandbox.io/p/sandbox/agitated-dubinsky-8s9pvw?file=/package.json:1,1

### To Reproduce

1. Have a NextJS app using the pages directory
2. Include an API route in pages/api that returns a JSON response
3. Hit that endpoint in your component, see it works locally
4. Deploy to Vercel, see that you get a 405

### Current vs. Expected behavior

In current 13.4.x versions, there is no issue with these API routes, things are working fine. Upgrading to 13.5.1, all `pages/api` routes that return a 200 JSON response are getting a `405 Method Not Allowed` only once deployed to Vercel.

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
      Platform: linux
      Arch: x64
      Version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
    Binaries:
      Node: 18.18.0
      npm: 9.8.1
      Yarn: 1.22.19
      pnpm: 8.7.6
    Relevant Packages:
      next: 13.5.2-canary.1
      eslint-config-next: 13.5.2-canary.1
      react: 18.2.0
      react-dom: 18.2.0
      typescript: 5.2.2
    Next.js Config:
      output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

### Additional context

I am currently working on the above reproduction, but wanted to get this out as I think it relates to work done in https://github.com/vercel/next.js/pull/51534

**Comment by gadicc** [comment]
Oops, sorry for the inadvertent mention.  In my case, I'm quite ashamed to say, I forgot to commit the `route.ts` to the repo :scream:  All working fine on latest NextJS.  So seems like a different issue to this one.  I've removed the above commit from my repo but seems there's no way to delete the mention on GitHub.  Sorry for the noise.

**Comment by wadehammes** [comment]
> @wadehammes  To add more context to my solution, during build time the file location are change hence the application lost the path of the file email template which is different during development. Hence the file was not found.
> 
> 
> 
> **check logs on /<app_name>/logs**
> 
> 
> 
> `
> 
> import path from 'path';
> 
> 
> 
> 
> 
> // Change the below 
> 
> const emailResponseHTML = await ejs.renderFile(
> 
>       './email/contactMailer.ejs',
> 
>       { fullName: fullName }
> 
>  );
> 
> 
> 
> // To ths below after the above import
> 
>  const emailResponseHTML = await ejs.renderFile(
> 
>       `${path.resolve(process.cwd(), 'email')}/contactMailer.ejs`,
> 
>       { fullName: fullName }
> 
>     );
> 
> `

I don't think this relates to my issue

**Comment by wadehammes** [comment]
I tested these routes using GET instead of POST, which results in a 500 error. Anyway to look into this Next team? Everything works fine on 13.4.19.

**Comment by wadehammes** [comment]
@shuding @leerob sorry to ping directly but want to get some visibility on this, can't upgrade at the moment and am stumped on to what could be the issue. Hard to replicate in Code Sandbox since it's not deployed to Vercel.

**Comment by r0binxp** [comment]
Same problem, any Ideas ?

**Comment by Alex1899** [comment]
Having the same issue. @wadehammes did you manage to figure it out?

**Comment by wadehammes** [comment]
> Having the same issue. @wadehammes did you manage to figure it out?

No it is still broken for me :(

**Comment by Alex1899** [comment]
> > Having the same issue. @wadehammes did you manage to figure it out?
> 
> No it is still broken for me :(

 I figured out what was the issue for me. It was due to the env variable not loading correctly in vercel. I checked the logs in the deployment and found an error there. After fixing that, the 405 not allowed error was gone

**Comment by kevinschaich** [comment]
I believe the problem is due to [static rendering](https://nextjs.org/docs/app/building-your-application/rendering/server-components#switching-to-dynamic-rendering).

Next thinks your page doesn't have any need for data fetching/uploading if you don't use a dynamic function, so it renders the same page for everyone and your outgoing request can't be run because it's static HTML that's delivered from a CDN/edge server.

Here's how I fixed it:

```typescript
import {headers} from 'next/headers'

export default function NewPage() {
    // hack page into dynamic rendering
    const headersList = headers()

    return (
        ...
    )
}
```

@leerob I think this is a bug has been reported on several other issues. Examples:

* Use a third-party data fetching tool like Prisma in Server Components, without the use of a Dynamic Function
* Call a Server Action without the use of a Dynamic Function

**Comment by wadehammes** [comment]
> I believe the problem is due to [static rendering](https://nextjs.org/docs/app/building-your-application/rendering/server-components#switching-to-dynamic-rendering).
> 
> Next thinks your page doesn't have any need for data fetching/uploading if you don't use a dynamic function, so it renders the same page for everyone and your outgoing request can't be run because it's static HTML that's delivered from a CDN/edge server.
> 
> Here's how I fixed it:
> 
> ```ts
> import {headers} from 'next/headers'
> 
> export default function NewPage() {
>     // hack page into dynamic rendering
>     const headersList = headers()
> 
>     return (
>         ...
>     )
> }
> ```
> 
> @leerob I think this is a bug has been reported on several other issues. Examples:
> 
>     * Use a third-party data fetching tool like Prisma in Server Components, without the use of a Dynamic Function
> 
>     * Call a Server Action without the use of a Dynamic Function

Unfortunately, I don't want to dynamically render the pages, as there is a noticeable performance loss in doing so when querying from Contentful. Would love some help from the Next team here.

**Comment by wadehammes** [comment]
Checking logs, I see that there is this error:

![image](https://github.com/vercel/next.js/assets/222170/d681ad0e-e4c0-4b04-bfb5-b2e45431be6e)

I added the packaged `styled-jsx` to my dependencies but the error persists, still only on Vercel.

**Comment by nikhils4** [comment]
@wadehammes Fixed or still broken? On the same boat :(

**Comment by wadehammes** [comment]
> @wadehammes Fixed or still broken? On the same boat :(

Not fixed for me, no response from the Next team so I am still stuck on 13.4.9.

**Comment by nikhils4** [comment]
Honestly just after commenting here I just removed `{ "output": "export" }` form next.config and removed the `export const dynamic = 'auto'` from the route.ts of the failing endpoint and it worked!

PS: I was stuck from last 7 hours on this tried all AI, non-AI based solutions nothing worked

**Comment by wadehammes** [comment]
I don't have any of those things in mine. It is just a standard API route:

```
import { NextApiRequest, NextApiResponse } from "next";

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  const { secret, feedId, type } = req.query;

  // This secret key just allows us to make sure no one externally can hit this endpoint
  if (secret !== process.env.API_SECRET) {
    return res.status(401).json({ message: "Invalid token." });
  }

  if (!type) {
    return res.status(401).json({
      message: 'No type of either "reviews" or "feed" supplied as a parameter.',
    });
  }

  if (!feedId && type === "reviews") {
    return res.status(401).json({
      message: "No feed id supplied as a parameter to fetch reviews.",
    });
  }

  const apiUrl =
    feedId && type === "reviews"
      ? `https://embedsocial.com/admin/v2/api/reviews/reviews-filtered?feed_id=${feedId}&sort=created_on&per_page=200`
      : "https://embedsocial.com/admin/v2/api/reviews/feeds";

  try {
    const fetchReviews = await fetch(apiUrl, {
      method: "GET",
      headers: {
        Accept: "application/json",
        Authorization: `Bearer ${process.env.EMBED_SOCIAL_API_KEY}`,
        "Content-Type": "application/json; charset=utf-8",
      },
    });

    if (fetchReviews.ok) {
      const reviewsJson = await fetchReviews.json();

      if (reviewsJson.success) {
        return res.status(200).json(reviewsJson);
      }

      return res
        .status(400)
        .json({ message: "Not able to fetch reviews json." });
    }
  } catch (e) {
    return res.status(400).json({ message: "Failed to fetch reviews." });
  }
};

export default handler;
```

**Comment by nikhils4** [comment]
> I don't have any of those things in mine. It is just a standard API route:
> 
> ```
> import { NextApiRequest, NextApiResponse } from "next";
> 
> const handler = async (req: NextApiRequest, res: NextApiResponse) => {
>   const { secret, feedId, type } = req.query;
> 
>   // This secret key just allows us to make sure no one externally can hit this endpoint
>   if (secret !== process.env.API_SECRET) {
>     return res.status(401).json({ message: "Invalid token." });
>   }
> 
>   if (!type) {
>     return res.status(401).json({
>       message: 'No type of either "reviews" or "feed" supplied as a parameter.',
>     });
>   }
> 
>   if (!feedId && type === "reviews") {
>     return res.status(401).json({
>       message: "No feed id supplied as a parameter to fetch reviews.",
>     });
>   }
> 
>   const apiUrl =
>     feedId && type === "reviews"
>       ? `https://embedsocial.com/admin/v2/api/reviews/reviews-filtered?feed_id=${feedId}&sort=created_on&per_page=200`
>       : "https://embedsocial.com/admin/v2/api/reviews/feeds";
> 
>   try {
>     const fetchReviews = await fetch(apiUrl, {
>       method: "GET",
>       headers: {
>         Accept: "application/json",
>         Authorization: `Bearer ${process.env.EMBED_SOCIAL_API_KEY}`,
>         "Content-Type": "application/json; charset=utf-8",
>       },
>     });
> 
>     if (fetchReviews.ok) {
>       const reviewsJson = await fetchReviews.json();
> 
>       if (reviewsJson.success) {
>         return res.status(200).json(reviewsJson);
>       }
> 
>       return res
>         .status(400)
>         .json({ message: "Not able to fetch reviews json." });
>     }
>   } catch (e) {
>     return res.status(400).json({ message: "Failed to fetch reviews." });
>   }
> };
> 
> export default handler;
> ```

I was using Next JS 13

**Comment by wadehammes** [comment]
Relevant to https://github.com/vercel/next.js/issues/56900

**Comment by wadehammes** [comment]
Related to changes in this PR potentially? https://github.com/vercel/next.js/pull/51534

**Comment by wadehammes** [comment]
Would really love some assistance here, I know I am being annoying but it has been over a month. @leerob @shuding @timneutkens

**Comment by wadehammes** [comment]
I finally figured out the issue. @Alex1899 was closest, although I never got an error for it in logs like he did, I discovered it haphazardly through the CLI with Next 14 when loading up local dev. We have an env var that we only include on production, that was not added for Preview deploys in Vercel. I added it and builds magically started working. 

I think there should be better logs around missing env var's per environment, or better error handling around when a build is missing vars. Not sure best course of action but that was a doozy to figure out without better messaging or details.
