### ISSUE TITLE
revalidateTag and revalidatePath clears cache of all tags located at the same path

### ISSUE THREAD

**Issue by timuric** [vercel/next.js#63509]
### Link to the code that reproduces this issue

https://github.com/timuric/nextjs-minimal-issue/tree/revalidate-issue

### Project overview

`app > layout.tsx`

```jsx
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await fetch('https://jsonplaceholder.typicode.com/posts/1', {next:  {tags: ['posts']}})
  return (
    <html>
      <body>
        {children}
      </body>
    </html>
  );
}
```

`app > comments > page.tsx`
```jsx
import { revalidateTag} from "next/cache";
import React from "react";


export default async function Home() {
    async function flush() {
        "use server"
        revalidateTag('todo');
    }

    await fetch('https://jsonplaceholder.typicode.com/todos/1', {next:  {tags: ['todo']}})
    await fetch('https://jsonplaceholder.typicode.com/photos/1', {next:  {tags: ['photos']}})

    return <form action={flush}><button type={'submit'}>Flush</button></form>
}
```

### Steps to reproduce

1. Build project and start project `pnpm run build && pnpm start`
2. Launch interceptor to debug server-side requests
3. Go to `localhost:3000/comments` and press flush
4. Observe in the interceptor new request

<img width="1278" alt="image" src="https://github.com/vercel/next.js/assets/4006792/f54ed615-833c-4b68-8584-ec404b542ac0">

#### Current
Revalidating a tag on a page would invalidate all other tags located on the same page, including `root` layout.

#### Expected
Only `todo` tag should be invalidated

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:43 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6000
Binaries:
  Node: 20.5.0
  npm: 9.8.0
  Yarn: 1.22.21
  pnpm: 8.10.5
Relevant Packages:
  next: 14.1.3
  eslint-config-next: 14.1.3
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.4.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

App Router

### Which stage(s) are affected? (Select all that apply)

next dev (local), next start (local)

### Additional context

This minimal repo was based on a bug running in production on Vercel

**Comment by steve-marmalade** [comment]
Wow, I just looked at my app and noticed the same. Surprising indeed! I was definitely expecting to only refetch data associated with the tags that were revalidated.

**Comment by timuric** [comment]
Furthermore revalidate with interval has the same behavior https://github.com/vercel/next.js/issues/63512

**Comment by anicioalexandre** [comment]
I'm having the same issue (NextJs v14.0.4).
By the way, since `next.tags` allows a list of strings, wouldn't be reasonable that the `revalidateTag` accepts a list of strings too? instead of a single string?

**Comment by samcx** [comment]
@timuric Can you clarify if this is happening on the latest canary?

**Comment by ausminternet** [comment]
I just upgrade my project to next@rc and it seems to work as expected.

**Comment by bregtemundo** [comment]
I'm not sure it is fixed. Having simular problem where I fetch multiple items from api to show on a page. 
I have the revalidate set to false.
I pass in following tags ["stories","eventsevent1"] and ["stories","eventsevent2"] . when invalidating tag "eventsevent1" it seems to work correctly and only invalidate and refetch the correct content item.
However if I do the same thing (invalidate tag "eventevent1") a day later, both content items are refetched and show new data. 
I have experienced this behavior when hosted on Vercel. (not sure if also happens on localhost)
This might be due to something else specific in my code, but throwing it in here to see if anyone else is experiencing the same behavior.

**Comment by samcx** [comment]
@bregtemundo If you can create a <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> of this issue, that will be great so we can take a look!

**Comment by bregtemundo** [comment]
Double checked and I can confirm that I don't have the problem on localhost, everything looks to be working correctly. 
I guess the Vercel caching is not the same as the local (file) cache... or I'm missing something else

**Comment by AsaharaMasahiro** [comment]
This issue is still there in next.js 14.2.4.

**Comment by samcx** [comment]
@bregtemundo Does that mean you're still experiencing it on <picture data-single-emoji=":vercel:" title=":vercel:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/vercel/5e06be80d7237806.png" alt=":vercel:" align="absmiddle"></picture>?

@AsaharaMasahiro Is this with the <picture data-single-emoji=":repro:" title=":repro:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/repro/5cea53b5532825b4.png" alt=":repro:" align="absmiddle"></picture> provided above?

**Comment by bregtemundo** [comment]
@samcx yes, I'm still having the problem on vercel, I cleared data cache before testing.

**Comment by samcx** [comment]
@bregtemundo Can you share with us the Vercel Deployment you are testing?
