### ISSUE TITLE
Page is not rendered if router.push({static path with query params})

### ISSUE THREAD

**Issue by khristinalukanets** [vercel/next.js#71365]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/nostalgic-butterfly-m4yqwg?file=%2Fpackage.json

### To Reproduce

1. I use static export and app routes, all my components are client components
2. Reproduse in production env
3. Example: router.push("/login?firstVisit=true") -> login page is not rendered, router.push("/login") -> works
4. I also do prefetch for router.push("/login")

So just if I have query params in url the page is not rendered.

### Current vs. Expected behavior

Login page should render for router.push("/login?firstVisit=true")

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000
  Available memory (MB): 32768
  Available CPU cores: 10
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: 1.22.19
  pnpm: 7.25.1
Relevant Packages:
  next: 14.2.10
  eslint-config-next: 14.2.5
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.5.4
Next.js Config:
  output: export
```

### Which area(s) are affected? (Select all that apply)

Navigation

### Which stage(s) are affected? (Select all that apply)

Other (Deployed)

**Comment by ericschmar** [comment]
I second this bug. Seeing the same issue.

**Comment by bgub** [comment]
I tried to reproduce this on Next.js 16.1.6 (Turbopack) with `output: "export"` and App Router client components.

Setup:
- Home page with two buttons: `router.push("/login")` and `router.push("/login?firstVisit=true")`
- Login page reading `useSearchParams()` (wrapped in Suspense)
- Built with `next build` and served the static `out/` directory

Both navigations render the login page correctly — with and without query params. It seems like this has been fixed somewhere between 14.2.10 and 16.1.6.

**Comment by HerrZatacke** [comment]
I'm currently on next 16.2.0 and the issue persists for me.
I'm using `next build --webpack`

Some notes/observations:
* The initial page load needs to be on a static route with params. Links to the same route with different params will then fail
* calling `router.prefetch(...)` with the link to be visited and waiting (a few ms until the network request is finished) and _then_ load the page **will work**.
* Once a route has been loaded (or prefetched) once. It **will always work**
* The build task must not be run under windows otherwise some of the .txt files are inside folders instead of having the correct filename which will cause a 404 directly on page load and **subsequently** make the faulty request work (_don't ask how long it took me to figure that out_)

**Comment by HerrZatacke** [comment]
The error persists on 16.2.3

Edit:
The error persists on 16.2.4

**Comment by HerrZatacke** [comment]
The error still persists with nextjs version 16.2.7

<sub>Aside; It would be awesome if #92339 could be fixed. With #92340 someone already provided a fix. It would make it way easier for me (on windows) to verify if future version of nextjs still contain this bug...</sub>

**Comment by HerrZatacke** [comment]
The error keeps persisting. Tested now with Next version 16.2.9
