### ISSUE TITLE
[v15] Module parse failed: Bad character escape sequence

### ISSUE THREAD

**Issue by faisalrehmanlums** [vercel/next.js#71582]
### Link to the code that reproduces this issue

https://codesandbox.io/p/devbox/condescending-haze-go8s7s 

### To Reproduce

1. run this commad: `npx create-next-app@latest`
2. This will install latest version of nextjs like in package.json is  `"dependencies": {
    "react": "19.0.0-rc-65a56d0e-20241020",
    "react-dom": "19.0.0-rc-65a56d0e-20241020",
    "next": "15.0.0"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "postcss": "^8",
    "tailwindcss": "^3.4.1",
    "eslint": "^8",
    "eslint-config-next": "15.0.0"
  }` 
3. npm run dev
4. browser showing error `Module parse failed: Bad character escape sequence (11:57)
|   const fileSizeInMB = buffer.byteLength / 1024 / 1024

![error](https://github.com/user-attachments/assets/6955ae7d-ae47-43a2-8e2e-48d181056355) 
`

### Current vs. Expected behavior

I have just not changed any default value during app creation like shown in screenshot 
it should spin up dev server without error. which it dose but after within seconds error pop out. 
![install](https://github.com/user-attachments/assets/37af0273-c78b-41d1-bc6f-789bd01022f1)

### Provide environment information

```bash
test
```

### Which area(s) are affected? (Select all that apply)

create-next-app

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

When i step down to version 14 its working fine with 14.2.15 ` npx create-next-app@14 test-project`

**Comment by FKAJerry** [comment]
v15 stable has this bug it's  CRAZY!

Is anyone in the next.js community actually reviewing code?

**Comment by Sayakie** [comment]
Looks like this started appearing in `next@15.0.0-canary.180` on Windows platform.

* #70353

**Comment by darthmaim** [comment]
What node.js version are you using (please fill out the entire issue template next time)? There was a bug in some recent Node.js versions recently that had some similar symptoms, you should try upgrading,

**Comment by kdy1** [comment]
I think we should not inline the path into the string, or we should replace `\` with `\\` on windows. cc @devjiwonchoi

**Comment by faisalrehmanlums** [comment]
> What node.js version are you using (please fill out the entire issue template next time)? There was a bug in some recent Node.js versions recently (mainly 22.7.0) that had some similar symptoms, you should try upgrading if you are using that version.

I'm using node verion `v20.18.0` with npm version `10.9.0`

**Comment by faisalrehmanlums** [comment]
I have installed the canary version but still issue not resolved. Here is my package.json screenshot with error.

![image](https://github.com/user-attachments/assets/75c86926-9436-48e6-8327-adcccaa84af0)

cmd is 

![image](https://github.com/user-attachments/assets/3f936cfa-7749-40a7-baaf-e177a556e9db)

**Comment by Sayakie** [comment]
@devjiwonchoi, I suppose to webpack loader should be fix as well:
https://github.com/vercel/next.js/blob/79bc150e95d904579e6fd608aa2646bf4111ada8/packages/next/src/build/webpack/loaders/next-metadata-route-loader.ts#L108

**Comment by devjiwonchoi** [comment]
@Sayakie Thank you! Could you add the `next info` as well? I wasn't able to reproduce this issue on my VM, which I think it slipped.

**Comment by Sayakie** [comment]
FYI, here is my development environment:
```yaml
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 23855
  Available CPU cores: 12
Binaries:
  Node: 22.9.0
  npm: N/A
  Yarn: N/A
  pnpm: 9.12.0
Relevant Packages:
  next: 15.0.1 // Latest available version is detected (15.0.1).
  eslint-config-next: 14.2.13
  react: 19.0.0-rc-45804af1-20241021
  react-dom: 19.0.0-rc-45804af1-20241021
  typescript: 5.6.2
Next.js Config:
  output: N/A
```

`next dev --turbo` is working healthy but either `next dev` or `next build` throws the same error.

**Comment by faisalrehmanlums** [comment]
I have tried with latest canary version but still same issue following is my system info

![image](https://github.com/user-attachments/assets/9374cb33-4a65-4e3c-9898-faa64422ee83)

Same ERROR on browser:

![image](https://github.com/user-attachments/assets/cd79cb02-2504-4822-999c-929542c93856)

**Comment by devjiwonchoi** [comment]
@faisalrehmanlums Hi, https://github.com/vercel/next.js/pull/71673 hasn't been shipped yet, expected to be at `15.0.1-canary.4`.

**Comment by Rakvadium** [comment]
> @faisalrehmanlums Hi, #71673 hasn't been added to the release yet, ~expected to be at `15.0.1-canary.4`~.
> 
> Could you try `v15.0.2-canary.0`? Thank you!

I just tried this, not working.

**Comment by dualdetail** [comment]
I get this issue when I run dev or build. If you run dev you gotta load a page to see the bug propagate

**Comment by devjiwonchoi** [comment]
@dualdetail Since I cannot reproduce the case, it isn't easy to fix it confidently.
Could you confirm the `npx create-next-app@15.0.2-canary.0` does not work?

https://github.com/user-attachments/assets/ab93e716-f51a-4c3b-a2db-dabbdc6457e0

```
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Home
  Available memory (MB): 4087
  Available CPU cores: 6
Binaries:
  Node: 20.18.0
  npm: N/A
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.0.2-canary.0 // There is a newer canary version (15.0.2-canary.4) available, please upgrade!
  eslint-config-next: 15.0.2-canary.0
  react: 19.0.0-rc-69d4b800-20241021
  react-dom: 19.0.0-rc-69d4b800-20241021
  typescript: 5.6.3
Next.js Config:
  output: N/A
 ⚠ There is a newer canary version (15.0.2-canary.4) available, please upgrade!
   Please try the latest canary version (`npm install next@canary`) to confirm the issue still exists before creating a new issue.
   Read more - https://nextjs.org/docs/messages/opening-an-issue
```

**Comment by dualdetail** [comment]
The npx create next app works and I was also able to get the turbo repo basic example updated and working. Let me try to work and see if I can figure out whats going on. I don't understand why it's breaking on my mono repo but not others just yet

**Comment by Sayakie** [comment]
`npx rimraf .next` and then running next server should be working.

**Comment by devjiwonchoi** [comment]
@dualdetail Could you try removing `node_modules/` (the root one as well) & `.next/`?

**Comment by Charles0123** [comment]
I deleted favicon.ico and it returned to normal operation.

**Comment by dualdetail** [comment]
I am pretty confused, I can only get the icons to work using the --turbo flag and refactoring a bit. Similar to what Sayakie mentioned a while ago. I did try to remove all node_modules and .next folders and also recloned but both still fail on build. I did notice that the nextjs docs mention turbo not being experimental anymore, but it's still a experimental option in the next.config.ts. If anyone can confirm this then I at least know my package isn't bugged or anything. I think I'll try messing around with my next config to see if maybe the error lies there.

**Comment by Rakvadium** [comment]
> I deleted favicon.ico and it returned to normal operation.

This is also what "fixed" it for me. Should definitely not run into that error for having a favicon.ico file...

**Comment by PahesebPJ** [comment]
> > I deleted favicon.ico and it returned to normal operation.
> 
> This is also what "fixed" it for me. Should definitely not run into that error for having a favicon.ico file...

Sure, confirm also I deleted favicon.ico and worked again.

**Comment by dualdetail** [comment]
I've been going crazy, but I just decided to mess with the dist that I have (15.0.2-canary.7) and I just modified the code and got it to work properly. I had to run a replaceAll on the resource path to adjust any \ to \\ (also what Sayakie mentioned earlier) which fixed my problems. For whatever reason the path.default.posix.normalize(resourcePath) does not fix the path for me at all (I'm using Windows 11 pro). I'm not sure why normalize doesn't do jack, but the printed path is the same as what comes in originally.

**Comment by dualdetail** [comment]
Here's my next info, I can also paste in the distribution code if needed but it's exactly the same in the working and non-working instances. I still don't quite understand why it's not working specifically for my repo only, but I was able to get it fixed with a code change.

![Screenshot 2024-10-26 215322](https://github.com/user-attachments/assets/165a4191-0087-4eb5-8748-936becb2a135)

**Comment by elitalpa** [comment]
## Solution
I have a very similar issue but the error message is `Module parse failed: Octal literal in strict mode (11:75)`.

I **found the solution** while playing with the dist file (./node_modules/next/dist/build/webpack/loaders/next-metadata-route-loader.js).
The build error seems to be caused by `ResourcePath` inside `throw new Error()`.
Wrapping it with `JSON.stringify(ResourcePath)` fixes the error, like this :
```js
    throw new Error('File size for ${imgName} image "${JSON.stringify(resourcePath)}" exceeds ${fileSizeLimit}MB. ' +
    \`(Current: \${fileSizeInMB.toFixed(2)}MB)\n\` +
    'Read more: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image#image-files-jpg-png-gif'
    )
```

- Same solution seems to already be used elsewhere in the same file :
```js
throw new Error('Default export is missing in ${JSON.stringify(resourcePath)}')
```

## About the error
What I found about the error :
- The error seems to be caused by backslashes (`\`) which seem to be interpreted as escape characters.
  - Backslashes are used only on Windows for paths, which explains why there is no issue on other Operating Systems like Linux which uses forward slashes (`/`).
- Also, the error seems to be triggered only if one of the directories have a name that begins with certain characters.
  - Like beginning with a number (path example : `C:\Users\eli\Documents\01-next-app` where the `01-next-app` directory begins with `01`).
  - Which explains why I didn't get exactly the same error message and why others did not get the error at all.

## Reproducing the error

How I got the error :
- on Windows 10 or 11 (tried on Linux and had no error)
- using `npx create-next-app@latest` (next 15.0.1) and webpack with all the default options (TypeScript : yes, ESLint : yes, Tailwind CSS : yes, src/ : yes, App Router : yes, Turbopack : no,  customize the import alias : no).
- the name of one of the directories begins with a number
- running the app with `npm run dev` (next dev)
- refreshing the page a few times (or using Ctrl + F5 once) makes the build error appear (does not appear on the first load)

No error in these cases :
- removing the favicon.ico file 
- using Turbopack (next dev --turbo)
- if you have luck and your directory names don't begin with certain characters like numbers

---

Hope this helps ;)

**Comment by devjiwonchoi** [comment]
Could you guys all try the `15.0.2-canary.10`? Hope this is our final fix. Kudos to @elitalpa for the PR!

**Comment by devjiwonchoi** [comment]
Hey everyone, v15.0.2 is out with the fix. Please give it a try and lmk!
