### ISSUE TITLE
ReferenceError: e is not defined error occurs when running next dev --turbo

### ISSUE THREAD

**Issue by y-hsgw** [vercel/next.js#72232]
### Link to the code that reproduces this issue

https://github.com/y-hsgw/with-urql

### To Reproduce

When using` next dev --turbo` with a Next.js application, the following error message appears:
```sh
ReferenceError: e is not defined
    at Module.Kind (/path/to/.next/server/chunks/ssr/node_modules_xyz.js:1376:18)
    at Kind (turbopack://[project]/node_modules/@urql/core/src/gql.ts:84:30)
    ...
```

The application works without issues when running the `next dev` command.

### Current vs. Expected behavior

bug screenshot: 

![スクリーンショット 2024-11-03 12 36 54](https://github.com/user-attachments/assets/6f936880-4e92-4f5a-8f73-2852cd829dd8)

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:26 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 22.10.0
  npm: 10.9.0
  Yarn: 4.5.1
  pnpm: N/A
Relevant Packages:
  next: 15.0.2 // Latest available version is detected (15.0.2).
  eslint-config-next: N/A
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 5.6.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

I also submitted an issue to urql, but they responded that it was an issue on the Next.js side.

https://github.com/urql-graphql/urql/issues/3704

**Comment by TheFabi8A** [comment]
In the 15.0.2 version --turbo command has replaced to --turbopack #71730

**Comment by y-hsgw** [comment]
The same issue occurs with the --turbopack command as well.

**Comment by apostolos** [comment]
I'm getting the same error with `gql.tada`.

I think the problem is related to `@0no-co/graphql.web` v1.0.10+ which `urql` is also using internally.

If I pin `@0no-co/graphql.web` to v1.0.9, it works fine.

One of the following PRs is introducing the problem:
- https://github.com/0no-co/graphql.web/pull/38
- https://github.com/0no-co/graphql.web/pull/39

**Comment by E3FxGaming** [comment]
Through bisection i figured out that it's a problem with

- https://github.com/0no-co/graphql.web/pull/38

Specifically [these five lines](https://github.com/0no-co/graphql.web/blob/121a9e8cd1cd9d083fcec575917a46e5cf761ac7/src/parser.ts#L507-L511) that introduce a setter cause the problem.

Removing those lines even in the current master branch HEAD of the /0no-co/graphql.web project and building the project results in a `dist` result that doesn't throw an error when used with tubopack.

I assume the broader problem is that the [document function](https://github.com/0no-co/graphql.web/blob/47ea6137d8ee01cbb1efd4e3bd1aa6e8b3fb29fd/src/parser.ts#L486) returns [ast.DocumentNode](https://github.com/0no-co/graphql.web/blob/47ea6137d8ee01cbb1efd4e3bd1aa6e8b3fb29fd/src/ast.ts#L86), which in turn uses a custom [Or type](https://github.com/0no-co/graphql.web/blob/47ea6137d8ee01cbb1efd4e3bd1aa6e8b3fb29fd/src/types.ts#L1) to express that it's either their own [DocumentNode](https://github.com/0no-co/graphql.web/blob/47ea6137d8ee01cbb1efd4e3bd1aa6e8b3fb29fd/src/ast.ts#L88-L92) or a [DocumentNode from graphql-js](https://github.com/graphql/graphql-js/blob/e9b6b626f6f6aa379bb8f8c48df40d0c02a26082/src/language/ast.ts#L301-L305).

Both of those DocumentNode have an optional property `readonly loc?: Location;`, which the defined getter and setter don't refer to though, instead they work with this [scoped variable loc from the document function](https://github.com/0no-co/graphql.web/blob/47ea6137d8ee01cbb1efd4e3bd1aa6e8b3fb29fd/src/parser.ts#L503).

The combination of getter and setter existing for an (optional) property that is otherwise never used, in combination witth the getter and setter not referring to the actual property of ast.DocumentNode is probably something Turbopack can't handle.

**Comment by E3FxGaming** [comment]
Alright, looked into this some more. I'll summarize my findings and then we can maybe discuss where this should be reported, since I don't believe it's something that Turbopack can fix/should attempt to fix.

I'll be referring to the following code snippets (all links are permanent links to the current head-commits on their respective master/main branch, as of writing this):

- [DocumentNode](https://github.com/graphql/graphql-js/blob/831c1211d7a88bed1758d5c33416514947247241/src/language/ast.ts#L311-L316) from graphql-js. This has gained a new property `tokenCount` yesterday which you can ignore for the purposes of this discussion. What's important is that it has 3 `readonly` fields, of which one, called `loc`, is optional.
- [DocumentNode](https://github.com/0no-co/graphql.web/blob/47ea6137d8ee01cbb1efd4e3bd1aa6e8b3fb29fd/src/ast.ts#L86-L93) from graphql.web is funamentally identical to the graphql-js, version. It's just a type definition that says `DocumentNode` can either be of the graphql-js variety or of the graphql.web variety.
- [DocumentNode](https://github.com/urql-graphql/urql/blob/cf43315c40f9d40d963b401c1b505724154b552e/packages/core/src/utils/graphql.ts#L10-L12) from urql. Their type definition says DocumentNode is of the DocumentNode type from graphql.web, but not of the graphql-js type.

- [parse](https://github.com/0no-co/graphql.web/blob/47ea6137d8ee01cbb1efd4e3bd1aa6e8b3fb29fd/src/parser.ts#L542-L549) from qraphql.web. This can take a string and parse it into a DocumentNode. Notably it can take `ParseOptions` which can tell the next method mentioned below that the `loc` property should remain undefined on the `DocumentNode`.
- [document](https://github.com/0no-co/graphql.web/blob/47ea6137d8ee01cbb1efd4e3bd1aa6e8b3fb29fd/src/parser.ts#L486-L530) from graphql.web. This takes an input string and a boolean that specifies whether no location information should be added and constructs a DocumentNode.

- [stringifyDocument](https://github.com/urql-graphql/urql/blob/cf43315c40f9d40d963b401c1b505724154b552e/packages/core/src/utils/request.ts#L46-L86) from urql. The premise of this method shouldn't introduce any problems: take a DocumentNode and turn it into a string. The problem that it introduces can be found in the method descriptions, which reads "When a DocumentNode is passed to this function, it caches its output by modifying the `loc.source.body` property on the GraphQL node.".

This IMHO is a flawed function, because it assumes there is a place in the `DocumentNode` where information can always be cached. It does a little checking with `!node.loc` but then throws all caution out the window with an assignment to a `(node as any).loc` cast. This initially worked fine: the `!node.loc` check correctly identified whether `DocumentNode` even has a `loc` and would block assignment if no such property existed.

It worked until it did not work anymore: [This pull request](https://github.com/0no-co/gql.tada/pull/396) added a getter to `DocumentNode` for the Ono-co/gql.tada GraphQL query engine, which got [backported  to graphql.web last week for compatibility reasons](https://github.com/0no-co/graphql.web/pull/38).

Having a getter for a potentially undefined property causes problems, especially if you use "property is accessible" as an indicator for "property is assignable". And so it crashed, resulting in [this gql.tada issue](https://github.com/0no-co/gql.tada/issues/398), where the stacktrace indicates that it crashed exactly in `stringifyDocument`.

All of this of course completely ignores that `loc` was originally meant to be `readonly`. If it exists fine, you can alter the properties of `Location` assigned to `loc`, since those aren't `readonly`, but otherwise you probably shouldn't mess with caching information in an undefined variable.

Anyways, instead of overthinking this entire situation [adding a setter](https://github.com/0no-co/gql.tada/pull/400) was the chosen solution that worked for them, but that now just propagates the issue to turbopack users. Turbopack (rightfully) assumes `readonly` properties shouldn't have a setter and thus, during compilation, apparently discards that function. When it comes to putting the compilation result back together in the browser of the user, the "ReferenceError: e is not defined" error from the title of this issue gets thrown.

How I would fix this problem: roll back the introduction of the setter and getter and improve the stringify method in two ways:

- improve the detection of whether `loc` is actually not undefined.
- when loc is defined, alter the properties of the existing `Location` instead of assigning a new `Location` to the originally `readonly` property. This would get rid of the `(node as any)` cast too.

Something I have not fully understood yet is the entire `graphql-tag` situation described in the [pull request that introduced the getter](https://github.com/0no-co/gql.tada/pull/396), but maybe they could fix the problem on their `graphql-tag` end in a different way that doesn't involve changes to gql.tada (and by extension graphql.web).

Overall there are A LOT of parties/people involved in this entire situation and turbopack users are simply on the receiving end of an unfortunate situation. Following the chain of dependencies I believe a good place to start would be reporting the problem to urql, who could then decide whether this is something they would want to improve. This time it's turbopack, but next time it could be some other dependency/project that runs into trouble with urql.

[Reporting an issue to urql](https://github.com/urql-graphql/urql/issues/new?assignees=&labels=&projects=&template=bug_report.yaml) involves creating a reproduction, which I wouldn't mind doing but I first wanted to hear the opinions of other people here.

**Comment by gdoteof** [comment]
I just ran into this with `@cetusprotocol/cetus-sui-clmm-sdk` , turboback dev works fine without this import but breaks with  same

```

 ⨯ ReferenceError: e is not defined
    at Module.Kind (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/node_modules__pnpm_dd7c97._.js:13314:18)
    at graphql (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/node_modules__pnpm_dd7c97._.js:14241:299)
    at instantiateModule (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at instantiateModule (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at instantiateModule (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at instantiateModule (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at instantiateModule (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/src/lib/cetus_slice.ts [app-ssr] (ecmascript) (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[root of the server]__633b27._.js:140:370)
    at instantiateModule (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/src/lib/store.ts [app-ssr] (ecmascript) (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[root of the server]__633b27._.js:184:129)
    at instantiateModule (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at esmImport (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:132:20)
    at [project]/src/app/StoreProvider.tsx [app-ssr] (ecmascript) (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[root of the server]__633b27._.js:208:123)
    at instantiateModule (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:644:12)
    at commonJsRequire (/home/geoff/proj/allocate_capital/capital-allocator/.next/server/chunks/ssr/[turbopack]_runtime.js:147:20)

**Comment by nphmuller** [comment]
This is really weird. I'm also having this same issue with @0no-co/graphql.web

It seems the following code from `node_modules/@0no-co/graphql.web/dist/graphql.web.mjs` gets transpiled strangely.

node_modules/@0no-co/graphql.web/dist/graphql.web.mjs:
``` js
var e = {
  NAME: "Name",
  DOCUMENT: "Document",
  ... etc ...
};

export { c as BREAK, GraphQLError, e as Kind, ... etc ... };
```

Transpiled file .next/server/chunks/ssr/node_modules_d78758._.js:
``` js
__turbopack_esm__({
    "BREAK": (()=>c),
    "GraphQLError": (()=>GraphQLError),
    "Kind": (()=>e),
    ... etc ...
});
var e1 = {
    NAME: "Name",
    DOCUMENT: "Document",
    ... etc ...
};
```

As you can see, "Kind" referes to the var `e`, but the var is actually named `e1` after transpilation.

When I change the var name in `node_modules/@0no-co/graphql.web/dist/graphql.web.mjs` from `e` to something else like `foo`, everything just suddenly works. It seems that there might be a bug in fixing name collisions during transpilation?

**Comment by nphmuller** [comment]
Only the esm export of @0no-co/graphql.web has the issue above. Is there a way to force turbopack to choose the cjs output for a package? 

The only way I get it working is via the patch below (using https://www.npmjs.com/package/patch-package):

``` patch
diff --git a/node_modules/@0no-co/graphql.web/package.json b/node_modules/@0no-co/graphql.web/package.json
index bd060d6..99b7d28 100644
--- a/node_modules/@0no-co/graphql.web/package.json
+++ b/node_modules/@0no-co/graphql.web/package.json
@@ -16,8 +16,7 @@
   "exports": {
     ".": {
       "types": "./dist/graphql.web.d.ts",
-      "import": "./dist/graphql.web.mjs",
-      "require": "./dist/graphql.web.js",
+      "default": "./dist/graphql.web.js",
       "source": "./src/index.ts"
     },
     "./package.json": "./package.json"

```

**Comment by kdy1** [comment]
@nphmuller Thank you so much for the investigation!
I'll fix it soon.

**Comment by carlbarrdahl** [comment]
@kdy1 
Thanks for looking into this! Any updates?

**Comment by kdy1** [comment]
Well, I'm OoO until 1/1

**Comment by Mnigos** [comment]
any updates? @kdy1

**Comment by kdy1** [comment]
I'll work on this issue (and swc/turbopack bufixes) starting from the tomorrow.

**Comment by arielweinberger** [comment]
@kdy1 It's been a bit over a month since your initial response to this thread. We have a bunch of users who integrate with Next.js and urql is one of our dependencies, which means most new users get this `e is not defined` error. Do you have any updates please? Or any quick hacks/mitigation steps we can do on our end?

**Comment by kdy1** [comment]
No. I'm busy with other tasks.

**Comment by suhasdeshpande** [comment]
Would love to help or get this fixed!

**Comment by tylerslaton** [comment]
Any guidelines for how contributors can help fix this? My team is really wanting to make some progress here, we're happy to help in whatever way that we can.

**Comment by kdy1** [comment]
@tylerslaton You would need to define `exports: FxHashMap<RcStr, Id>` in `EvalContext`, and use those `Id`s from `impl CodeGenerateable for EsmExports`


See https://github.com/vercel/next.js/pull/73544/files

**Comment by arielweinberger** [comment]
@kdy1 I see that this Draft PR points to this issue (72232). Is it planned to be merged?

**Comment by ataibarkai** [comment]
To add some color here, this is impacting any package that uses either of those 
Anyone using [`urql`](https://github.com/urql-graphql/urql) or [`gql.tada`](https://github.com/0no-co/gql.tada) **(500K+ weekly installs)**

Furthermore `turbo` is now the default setting with `Next.js` 15 and above.
if users _previously_ picked `no` on the `turbo` setting, the cli seems to remember that so they are not experiencing issues on subsequent installs.
But e.g. any first-time Next.js user (or a user on a new machine) will see broken behavior on the default path for lots of packages.

**Comment by drewcook** [comment]
Just adding onto the fact that in a default Next.js app as of writing this, using `gql.tada`, and using `turbo`. the error exists.

The temporary fix is changing the dev command from: `"dev": "next dev --turbopack"` to `"dev": "next dev"` to allow it to compile using Webpack instead.

Using `Next v15.1.6`

**Comment by gluonfield** [comment]
Just came across this, any progress on the solution @suhasdeshpande @kdy1 ?

**Comment by evsasse** [comment]
Was testing this again with `v15.2.2-canary.3`, which included the fixes on @kdy1 PR...

But still seems to be giving off an error on the same vibe 😕.

![Image](https://github.com/user-attachments/assets/b03117c9-5ba4-46a3-8e3c-a9e5cc9b651f)

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020
  Available memory (MB): 32768
  Available CPU cores: 12
Binaries:
  Node: 20.11.1
  npm: 10.2.4
  Yarn: N/A
  pnpm: 9.13.0
Relevant Packages:
  next: 15.2.2-canary.3 // Latest available version is detected (15.2.2-canary.3).
  eslint-config-next: 14.2.15
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 4.9.5
Next.js Config:
  output: N/A
```

**Comment by nowlena** [comment]
Issue still persists after updating to Next `15.2.2` and  `gql.tada`

**Comment by fresonn** [comment]
> Issue still persists after updating to Next `15.2.2` and `gql.tada`

and 15.2.3 too

**Comment by kdy1** [comment]
<img width="1840" alt="Image" src="https://github.com/user-attachments/assets/b3118139-8ba3-4e3a-b3f1-9a7dd208f965" /> Ah this was fixed. `15.2.x` does not include this patch

**Comment by kdy1** [comment]
If you think this error still occurs, please create another issue with a working minimal reproduction. The reproduction in the issue body is now working.

**Comment by kdy1** [comment]
@fresonn Please file a new issue and mention me from there. It's a different issue, and I need a new reproduction

**Comment by wfl-junior** [comment]
> Only the esm export of @0no-co/graphql.web has the issue above. Is there a way to force turbopack to choose the cjs output for a package?
> 
> The only way I get it working is via the patch below (using https://www.npmjs.com/package/patch-package):
> 
> diff --git a/node_modules/@0no-co/graphql.web/package.json b/node_modules/@0no-co/graphql.web/package.json
> index bd060d6..99b7d28 100644
> --- a/node_modules/@0no-co/graphql.web/package.json
> +++ b/node_modules/@0no-co/graphql.web/package.json
> @@ -16,8 +16,7 @@
>    "exports": {
>      ".": {
>        "types": "./dist/graphql.web.d.ts",
> -      "import": "./dist/graphql.web.mjs",
> -      "require": "./dist/graphql.web.js",
> +      "default": "./dist/graphql.web.js",
>        "source": "./src/index.ts"
>      },
>      "./package.json": "./package.json"

Issue still happening in `next` version `15.3.0`, using `gql.tada`, but the path above is a solution
