### ISSUE TITLE
As of [15.2.0-canary.57] throws TypeError: Cannot read properties of undefined (reading 'stack')

### ISSUE THREAD

**Issue by talatkuyuk** [vercel/next.js#76395]
### Link to the code that reproduces this issue

https://github.com/talatkuyuk/next15-canary-bug-reproduction

### To Reproduce

The app which I provided its link is a bug reproduction for **`next@15.2.0-canary.57`** and **still continues** in **`next@15.2.0-canary.70`** which is latest canary.

It throws the error below in only development mode, not in production.

The error occurs in the nextjs page (MDX article) related with importing a `.mjs` react component into MDX. I put another article page to show importing a module/function in MDX works well without problem.

```bash
TypeError: Cannot read properties of undefined (reading 'stack')
    at stringify (<anonymous>)
    at stringify (<anonymous>) {
  digest: '3183793578'
}
```

Actually, there is no problem with the Next.js versions below (All, I tested).  Importing a `.mjs` react component into MDX works well.

- `next@15.1.7`
- `next@15.2.0-canary.0`
- `next@15.2.0-canary.10`
- `next@15.2.0-canary.20`
- `next@15.2.0-canary.30`
- `next@15.2.0-canary.40`
- `next@15.2.0-canary.50`
- `next@15.2.0-canary.56`

### Step to produce the error

`npm run dev`--> open browser and click to articles, and see the error in development mode.

`npm run build` and `npm run start` --> open browser and click the articles, see there is NO error in production mode.

Then,  install the previous canary version to test it.

```bash
npm i -S next@v15.2.0-canary.56
rm -rf .next && npm run dev
```

and see **there is NO error** in development and production modes.

Then, install the canary.57 again,

```bash
npm i -S next@v15.2.0-canary.57
rm -rf .next && npm run dev
```

and see **the TypeError** in development mode.

### What is `next-mdx-remote-client`

The **[`next-mdx-remote-client`](https://github.com/ipikuka/next-mdx-remote-client)** is a fork of **[`next-mdx-remote`](https://github.com/hashicorp/next-mdx-remote)**, having more features like **supporting import statements in MDX.**

It works well with all versions of `Next.js (13, 14, 15)` for one year almost.

### Log in the console related with the error

I put it in the end because it is long:

```bash
[Error] TypeError: Cannot read properties of undefined (reading 'stack')
resolveErrorDev
processFullStringRow
processFullBinaryRow
progress

The above error occurred in the <Unknown> component. It was handled by the <DevOverlayErrorBoundary> error boundary.
	onCaughtError (error-boundary-callbacks.js:53)
	logCaughtError (react-dom-client.development.js:8138)
	runWithFiberInDEV (react-dom-client.development.js:1474)
	(anonim işlev) (react-dom-client.development.js:8185)
	callCallback (react-dom-client.development.js:4841)
	commitCallbacks (react-dom-client.development.js:4861)
	runWithFiberInDEV (react-dom-client.development.js:1474)
	commitClassCallbacks (react-dom-client.development.js:11062)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12182)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12105)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12105)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12291)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12291)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12291)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12291)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12291)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12291)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12105)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12110)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12105)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12105)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12291)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12105)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12105)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12291)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12291)
	recursivelyTraverseLayoutEffects (react-dom-client.development.js:13296)
	commitLayoutEffectOnFiber (react-dom-client.development.js:12187)
	flushLayoutEffects (react-dom-client.development.js:17269)
	commitRoot (react-dom-client.development.js:17106)
	commitRootWhenReady (react-dom-client.development.js:16183)
	performWorkOnRoot (react-dom-client.development.js:16087)
	performWorkOnRootViaSchedulerTask (react-dom-client.development.js:17995)
	performWorkUntilDeadline (scheduler.development.js:36)
```

### Current vs. Expected behavior

Expecting no error, and show the article page without problem.

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 24.3.0: Thu Jan  2 20:22:00 PST 2025; root:xnu-11215.81.4~3/RELEASE_X86_64
  Available memory (MB): 16384
  Available CPU cores: 12
Binaries:
  Node: 18.20.5
  npm: 10.8.2
  Yarn: 1.22.22
  pnpm: 10.4.1
Relevant Packages:
  next: 15.2.0-canary.57 // There is a newer canary version (15.2.0-canary.70) available, please upgrade! 
  eslint-config-next: 15.1.7
  react: 19.0.0
  react-dom: 19.0.0
  typescript: 5.7.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Not sure

### Which stage(s) are affected? (Select all that apply)

next dev (local)

### Additional context

It throws the error in only development mode in local, not in production.

**Comment by eps1lon** [comment]
Thanks for the repro. 

Can you move `Bar.js` around so that it uses JSX and not `React.createElement`. This is essentially a limitation of MDX where it can't allow import of `react`. You have to use JSX directly.

**Comment by talatkuyuk** [comment]
Hi, @eps1lon.

In `next-mdx-remote-client`, a MDX content is compiled via `compile` of `@mdx-js/mdx`. And, the compiled source is evaluated and hydrated with **`Reflect.construct`**. The `@mdx-js/mdx` does the same thing but with **`new Function`**. Even `next-mdx-remote` does the same via `Reflect.construct`, but it doesn't support import declarations in MDX yet.

Both `new Function` and `Reflect.construct` execute JavaScript code (*compiled MDX source*) **in isolation** from Next.js's Webpack or other bundlers. Therefore, **it does not trigger Webpack’s built-in handling of static assets and other than .js files (like .png and .jsx files).**

Don't think the mechanism is the same with `next/mdx` which uses custom MDX bundler in the Next.js.

So, whenever we want to import a module / component into MDX content via import declarations, **it should be a plain javascript, not .jsx,** in `next-mdx-remote-client`.

Actually, importing a component/module with plain javascript in MDX would **work well** with **all Nextjs versions 13, 14, 15** till *`15.2.0-canary.57`*. The problem arises in only development environment not in production.

I couldn't figure out what caused in Next.js the error from the log in the console. Something happened in the version *`15.2.0-canary.57`*.

**Comment by eps1lon** [comment]
> I couldn't figure out what caused in Next.js the error from the log in the console. Something happened in the version 15.2.0-canary.57.

It's a new feature in React that surfaces these issues where different versions of React are used such is the case with `next-mdx-remote-client`. Best to file a bug report against that package since you can't dynamically eval code with (dynamic) import statements since those won't be subject to bundling the right package.

**Comment by talatkuyuk** [comment]
Thank you opening an issue in `next-mdx-remote-client` whose owner/author is me. I faced with with the issue while some doing tests. But, I think **the issue is not related with that package at all.** The issue is related what happened in `next@15.2.0-canary.57`. Importing a `.mjs` module in MDX via `next-mdx-remote-client` was working (13, 14, 14.2.24, 15, 15.1.7) with all versions of `next` up to `next@15.2.0-canary.57`.

> React that surfaces these issues where different versions of React are used such is the case with `next-mdx-remote-client`

`next-mdx-remote-client` **does not use its own `react` version**, the `react` is peerDependency in that package meaningly the package doesn't install `react` itself. **I strongly suppose the issue is not related with it.**

And **the issue continues** in **`next@15.2.0`** which landed today.

**Comment by eps1lon** [comment]
> next-mdx-remote-client does not use its own react version, the react is peerDependency in that package meaningly the package doesn't install react itself. I strongly suppose the issue is not related with it.

It does use the one installed though when you `import * as React from 'react'` in a file imported from `.mdx`. Basically any code that does `eval('import("react")')` is doing the wrong thing. `Reflect.construct` has the same issue.

**Comment by talatkuyuk** [comment]
Hi @eps1lon, thank you for reply, and for taking your time to solve the problem.

Are you saying that the problem is not caused by a change in `15.2.0-canary.57`, but that there is an inherent situation in `Reflect.construct` regarding the import of the `react` within?

**Even if such a situation is true, I'm trying to understand why the same problem did not occur in previous `next` versions.** In all previous versions of **`next`**, there was no problem and the mdx compiled source is being able to be hydrated via `Reflect.construct` while mdx source is importing a `.mjs` react component. (in app router, not pages router)

- next@13 --> there is no problem
- next@14 --> there is no problem
- next@14.2.24 (latest next@14) --> there is no problem
- next@15.1 --> there is no problem
- next@15.1.7 --> there is no problem
- next@15.2.0-canary.0 --> there is no problem
- next@15.2.0-canary.10 --> there is no problem
- next@15.2.0-canary.20 --> there is no problem
- next@15.2.0-canary.30 --> there is no problem
- next@15.2.0-canary.40 --> there is no problem
- next@15.2.0-canary.50 --> there is no problem
- next@15.2.0-canary.56 --> there is no problem
- next@15.2.0-canary.56 --> there is no problem
- **next@15.2.0-canary.57 --> The issue has started to appear.**
- next@15.2.0 --> The issue still occurs

If your diagnosis was correct, **why does the issue NOT occur in production** and the error occurs only in development environment?

Evaluation and hydration of compiled source in such a case in `next-mdx-remote-client/rsc` **occurs in server side.** It doesn't use dynamic import `import()`. And, the importing the module/component does not occur in the client side in MDX evaluation, **but in rsc environment.** 

In `Next.js`, the **"Dev Overlay"** is an interactive error overlay that helps developers identify and debug issues while running the app in development mode (next dev). I think the issue may be related with **`dev overlay`**.  Because I see some commits about `dev overlay` in `next@15.2.0-canary.57`. For example, the `dev overlay` is enabled by default. I see also a commit about `fix: call stack ...`  [See all commits (changes) in that version](https://github.com/vercel/next.js/releases/tag/v15.2.0-canary.57). (it is so similar with **TypeError: Cannot read properties of undefined (reading 'stack')**)

I need to get the issue solved. May other expertises also see the issue? @ztanner @devjiwonchoi

**Comment by eps1lon** [comment]
> Are you saying that the problem is not caused by a change in 15.2.0-canary.57, but that there is an inherent situation in Reflect.construct regarding the import of the react within?

Yes. The fault was always there. We do not support mixing different versions of React. You just didn't notice it since the existing codepaths avoided the fault.

**Comment by talatkuyuk** [comment]
@eps1lon Can you answer these question as well:
1. why previous canary versions and stable versions don't throw the issue?
2. why the issue doesn't happen in production? Only in development? ***(If the problem is as you explained, shouldn't it at least give the same error in production mode?)***

> We do not support mixing different versions of React.

Fine. But, `next-mdx-remote-client` and `mdx-js/mdx` doesn't install `react` because of peerDependency. Where the different `react` version come from ?

> Different react in client side cause the problem.

Fine. But, `App > page.tsx > MDXRemote > Bar.mjs` none of them is client component in [the app](https://github.com/talatkuyuk/next15-canary-bug-reproduction). **They are all react server component.** They all use the react in server side. 

**In order to prove the importing react is not the issue,** [I added another commit in the app](https://github.com/talatkuyuk/next15-canary-bug-reproduction/commit/c5214cb12272397e881f5fc6b2759d8d91b4b548). Imported `random` function in MDX ([see the mdx document](https://raw.githubusercontent.com/talatkuyuk/next15-canary-bug-reproduction/refs/heads/main/data/article-import-a-module.mdx)) still works even if it has *meaningless* but *purposeful* `import React from "react";` inside. Importing `Bar.mjs` should have been work as well. 

I am trying to understand how to solve the issue and `next-mdx-remote-client` as an open source project continues to give **the developers be able to import react components in MDX apart from supplying mdx components as props to `MDXRemote`**. Thanks.

**Comment by activemonkeys** [comment]
Interesting conversation. For what it's worth, I'm not using "next-mdx-remote-client" but ""next-mdx-remote". Together with the upgrade to Next 15.2.0 I also upgraded "next-mdx-remote" to version 5.0.0. Since then I'm also getting in development mode these errors:

**Comment by activemonkeys** [comment]
Interesting conversation. For what it's worth, I'm not using "next-mdx-remote-client" but ""next-mdx-remote". Together with the upgrade to Next 15.2.0 I also upgraded "next-mdx-remote" to version 5.0.0. Since then I'm also getting in development mode these errors:

 ⨯ [TypeError: Cannot read properties of undefined (reading 'stack')] {
  digest: '890473477'

In production, thes errors don't occur. 

Basically all is similar to the behaviour described above for the "next-mdx-remote-client".

**Comment by FluroAsh** [comment]
Same as the others, I'm also getting the same behavior described above with [contentlayer2](https://github.com/timlrx/contentlayer2), on any versions above `15.2.0-canary.56`. 

Production builds run fine, only getting this error in dev.

**Comment by DennieMello** [comment]
I have a similar problem with markdown-to-jsx

**Comment by psdev0** [comment]
In my case, I'm having same bug but that's specific to next-seo: https://github.com/garmeeh/next-seo/issues/1495

**Comment by talatkuyuk** [comment]
>The affected library need to pass in the React module into the evaluated code instead of having the evaluated code import React which wouldn't be affected by bundlers.

I've passed the `React` module into the evaluated code in `next-mdx-remote-client` canary version. I made the `React` is available in the imported components via **[`recma-mdx-import-react`](https://github.com/ipikuka/recma-mdx-import-react)** in a hacky way. 

You can have a look for more explanation here https://github.com/ipikuka/next-mdx-remote-client/issues/9#issuecomment-2707458632.

I don't know how other libraries suffers from the issue, it may provide an inspiration for further solution.

**Comment by activemonkeys** [comment]
Thanks @talatkuyuk, within my own project I solved it without an external package. This is the code I'm using that works with Next.js 15.2.0: A React component that safely renders MDX content in Next.js applications by explicitly passing the React runtime to avoid version conflicts that cause errors in Next.js 15.2.0+. Maybe this will be helpful to you...

```
/**
 * CustomMDX Component
 * 
 * This component renders MDX content in a Next.js application using the @mdx-js/mdx library.
 * It avoids the common issue found in Next.js 15.2.0+ where MDX evaluation causes React version conflicts
 * by explicitly passing the React runtime to the MDX evaluator.
 */

import * as React from 'react';
import * as runtime from 'react/jsx-runtime';
import {evaluate} from '@mdx-js/mdx';
import {components} from './components';

/**
 * Props for the CustomMDX component
 * 
 * @property {string} source - The MDX content as a string to be rendered
 * @property {Record<string, React.ComponentType<any>>} [additionalComponents] - Optional additional components 
 * to be made available to the MDX content
 */
interface CustomMDXProps {
  source: string;
  additionalComponents?: Record<string, React.ComponentType<any>>;
}

/**
 * Renders MDX content with provided components
 * 
 * This component evaluates MDX source content and renders it with the provided components.
 * It passes the React runtime directly to the MDX evaluator to avoid React version conflicts,
 * which is a common issue in Next.js 15.2.0+ with MDX libraries that use dynamic evaluation.
 * 
 * @param {CustomMDXProps} props - The component props
 * @returns {JSX.Element} The rendered MDX content or an error message if rendering fails
 */
export default async function CustomMDX({
  source,
  additionalComponents,
}: CustomMDXProps) {
  try {
    // Evaluate the MDX content with the React runtime
    // This approach prevents the "Cannot read properties of undefined (reading 'stack')" error
    // by explicitly providing the React runtime instead of letting MDX import it dynamically
    const {default: MDXContent} = await evaluate(source, {
      ...runtime,
      // Explicitly pass React to ensure consistent versioning
      React,
    });
    
    // Merge default components with any additional components provided
    const mergedComponents = {
      ...components,
      ...(additionalComponents || {}),
    };
    
    return <MDXContent components={mergedComponents} />;
  } catch (error) {
    console.error('Error rendering MDX:', error);
    return (
      <div>An error occurred while rendering the content.</div>
    );
  }
}
```

**Comment by talatkuyuk** [comment]
Hi @activemonkeys,

Your solution doesn't touch the issue. **Passing `React` into `evaluate` of `@mdx-js/mdx` is affectless, because the `evaluate` accepts explicitly and only `{Fragment, baseUrl, jsx, jsxDEV, jsxs, useMDXComponents}` as runtime options.** [check here](https://github.com/mdx-js/mdx/blob/84ec66ef529496535dc26ba5a8c3d55c85d78f25/packages/mdx/lib/util/resolve-evaluate-options.js#L85)

And, typescript throws an error `Object literal may only specify known properties, and 'React' does not exist in type 'Readonly<EvaluateOptions>'.ts(2353)` and warning us appropriately. You can disregard the error, and pass `React` into `evaluate` explicitly, but this doesn't change anything.

Meaningly, the `React` which passed into `evaluate` of `@mdx-js/mdx` is doing nothing.

**Comment by activemonkeys** [comment]
@talatkuyuk, thanks for the insightful feedback. 

My solution works within a fairly specific set of constraints that might not be applicable to everyone. Specifically, I'm taking advantage of Next.js's App Router and Server Components architecture. This allows me to perform the entire MDX evaluation on the server, which inherently avoids the client-side React versioning and bundling issues that seem to be at the root of the reported problems. The use of 'baseUrl' also becomes unnecessary as everything is being rendered on the server side without further processing on the client side.

Furthermore, I'm carefully managing the complexity of my MDX content. I am not using dynamic import statements within the MDX. I mostly rely on passing pre-imported, server-side React components to the <MDXContent> component via the components prop, and not through imports within the MDX content. The use of useId() within MDX-components also doesn't occur.
Therefore, it seems that my scenario effectively operates within a "clean room," avoiding the conditions that trigger the React version conflicts. While my current approach works for this use case, I recognize that it's not a general solution for all MDX implementations.

**Comment by timtbdev** [comment]
I remember when Next.js upgraded from 14 to 15, I had a similar issue with Contentlayer, so I switched to next-mdx-remote. Now it’s happening again. Maybe we should move to a headless CMS or an API-based solution.

**Comment by aymericzip** [comment]
I encountered the same error while using [Intlayer](https://github.com/aymericzip/intlayer), an i18n solution.  

### Context  

In my case, the function `rendererIntlayerNode` was constructing React components to be injected into my components via the `useIntlayer()` hook.  

#### Code usage example:  
```tsx
import { useIntlayer } from 'next-intlayer/server';

export const HomeContent = () => {
  const { myContent, myAriaLabel } = useIntlayer('home-content');

  return <p aria-label={myAriaLabel.value}>{myContent}</p>;
};
```
- **Type of `myAriaLabel`**: `ReactNode`  
- **Type of `myAriaLabel.value`**: `string`  

This was causing the error **`TypeError: Cannot read properties of undefined (reading 'stack')`** starting from Next.js `v15.2.0`.  

---

### Fix  

I'm not exactly sure why spreading a `ReactElement` started causing issues in `v15.2.x`, but the intention was to expose an additional attribute (`value`) to the component.  

#### **Base code (before fix)**:
```tsx
import type { NodeProps } from '@intlayer/core';
import {
  type PropsWithChildren,
  type ReactNode,
  type ReactElement,
  isValidElement,
} from 'react';

export type IntlayerNode<T = NodeProps['content']> = ReactNode & {
  value: T;
};

export const rendererIntlayerNode = <
  T extends number | string | boolean | undefined | null,
>({
  value,
  children,
}: PropsWithChildren<{
  value: T;
}>): IntlayerNode => {
  // If children is not a valid ReactElement, wrap it in a fragment
  const element: ReactElement<any> = isValidElement(children) ? (
    children
  ) : (
    <>{children}</>
  );

  // Add the "value" extra property to the element
  return { ...element, value };
};
```

#### **Fixed code**:
```tsx
import { type PropsWithChildren, type ReactNode, type ReactElement, isValidElement } from 'react';

type IntlayerNode<T> = ReactNode & { value?: T };

export function rendererIntlayerNode<
  T extends number | string | boolean | undefined | null,
>({ value, children }: PropsWithChildren<{ value: T }>): IntlayerNode<T> {
  // If children is not a valid ReactElement, wrap it in a fragment
  const element: ReactElement<any> = isValidElement(children) ? (
    children
  ) : (
    <>{children}</>
  );

  // Use Proxy to prevent direct mutation while allowing access to `.value`
  return new Proxy(element as ReactElement, {
    get(target, prop, receiver) {
      if (prop === 'value') {
        return value;
      }
      return Reflect.get(target, prop, receiver);
    },
  }) as IntlayerNode<T>;
}
```

You can check out the [commit](https://github.com/aymericzip/intlayer/commit/c32ff1bc9942f9f030dee769f13d7d6926bca26c) for reference.  

---

I hope this helps!

**Comment by ryantbrown** [comment]
Is there an update on this?

- it is not happening due to mixed React versions 
- it is not happening due to `React.` or `* as React` imports
- it has not been fixed in `canary-3-6`, https://github.com/aymericzip/intlayer/issues/103#issuecomment-2711308194

**Comment by aymericzip** [comment]
Hi @talatkuyuk,  

Thank you for your insights.  

Regarding `cloneElement`, I was limited by its compatibility with the new Lynx framework.  

Additionally, `return React.cloneElement(element, { value })` makes `value` accessible as `element.props.value` rather than `element.value`, which is what I intended

--- 

I agree that this is not understandable

**There may be multiple reasons causing this error**. However, for those who want to reproduce the issue:  

```tsx
// src/app/page.tsx
const MyComponent = () => {
  return <div>Test</div>;
};

const myElement = <MyComponent />;

const Page = () => {
  return <>{{ ...myElement }}</>; // TypeError: Cannot read properties of undefined (reading 'stack') at stringify (<anonymous>) { digest: '274730797'
};

// With async page ↓

// const Page = async () => {
//   return <>{{ ...myElement }}</>; //  [cause]: [TypeError: Cannot read properties of undefined (reading 'stack')] { digest: '1675862269' }
// };

export default Page;
```

**Comment by jpmonette** [comment]
This workaround solved it for me:

```ts
const nextConfig = {
  transpilePackages: ["next-mdx-remote"],
};
```

**Comment by l00sed** [comment]
> This workaround solved it for me:
> 
> const nextConfig = {
>   transpilePackages: ["next-mdx-remote"],
> };

That fixed the identified issue for me— using `next-mdx-remote`, but I'd like to understand what this setting actually does. Is there a downside to including packages here? The [documentation](https://nextjs.org/docs/app/api-reference/config/next-config-js/transpilePackages) is a little lacking...

**Comment by eps1lon** [comment]
Fixed in `next-mdx-remote-client@2.1.0`.

**Comment by edwardshturman** [comment]
Can confirm without using the `transpilePackages` workaround this is still an issue with `next-mdx-remote` at `5.0.0` and `next` at `15.3.0-canary.9`

**Comment by kovrichard** [comment]
> Fixed in `next-mdx-remote-client@2.1.0`.

It worked for me in the following scenario:
- `next-mdx-remote-client@2.1.1`
- `next@15.2.0`

My code was previously using:

```typescript
import { compileMDX } from "next-mdx-remote/rsc";

// ...

const { content } = await compileMDX({ /* ... */ });
```

I changed it to:

```typescript
import { evaluate } from "next-mdx-remote-client/rsc";

// ...

const { content } = await evaluate({ /* ... */ });
```

This new package works
- in dev mode with `next dev --turbopack`
- in a local build with `next build` followed by `next start`
- when deployed to Vercel

**Comment by AntoineKM** [comment]
I switched from next-mdx-remote to next-mdx-remote-client, and i still have the same issue 👀
