### ISSUE TITLE
Build fails on Next.js 15.4.5 with TypeError: Cannot read properties of null (reading 'useContext') during prerendering of /404

### ISSUE THREAD

**Issue by jsdev-robin** [vercel/next.js#82366]
### Link to the code that reproduces this issue

https://github.com/vercel/turborepo/tree/main/examples/with-tailwind

### To Reproduce

1. Use Next.js 15.4.5
2. Run npm install
3. Run next build
4. You will see:

`TypeError: Cannot read properties of null (reading 'useContext')
    at p (...\.next\server\pages\_error.js:19:2590)
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
Export encountered an error on /_error: /404, exiting the build.
⨯ Next.js build worker exited with code: 1 and signal: null
`

### Current vs. Expected behavior

next build should complete successfully and statically export all pages including /404 and /_error.

Actual:
Build fails with a runtime error during prerendering.

### Provide environment information

```bash
Operating System: Windows 11 64-bit
Node.js Version: 20.12.2
npm Version: 10.5.0
Package Manager: npm
Next.js Version: 15.4.5
Hosting: Local
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next build (local)

### Additional context

Suspected root cause: useContext called on null during _error.js or /404 rendering in static export

auto-install-peers warning likely unrelated, but present

I tested disabling the _error.tsx file, and build succeeds

Disabling "output": "standalone" does not fix the issue

<sub>[NEXT-4720](https://linear.app/vercel/issue/NEXT-4720/build-fails-on-nextjs-1545-with-typeerror-cannot-read-properties-of)</sub>

**Comment by eps1lon** [comment]
I can't repro with
```console
$ npx create-turbo@latest -e with-tailwind
$ npm install
$ npm run build
```
on the same Node.js version and ` Microsoft Windows 11 Pro N 10.0.26100 N/A Build 26100`

@jsdev-robin Were these the exact steps you tried to reproduce with? 

The example doesn't use Turbopack builds and I had no issues building with Turbopack so I'm removing the Turbopack label.

**Comment by jsdev-robin** [comment]
> I can't repro with
> ```console
> $ npx create-turbo@latest -e with-tailwind
> $ npm install
> $ npm run build
> ```
> 
> @jsdev-robin Were these the exact steps you tried to reproduce with? 
> 
> The example doesn't use Turbopack builds and I had no issues building with Turbopack so I'm removing the Turbopack label.

Yes, I followed exactly these steps:

npx create-turbo@latest -e with-tailwind
npm install
npm run build

However, I encountered the issue when building with Turbopack. It seems that while the example itself may not use Turbopack, in my local setup Turbopack was enabled, which could be causing the difference in results.

**Comment by jsdev-robin** [comment]
![20250811_152728.jpg](https://github.com/user-attachments/assets/efa41224-156d-494d-8a7b-459c4f35f6fd)

**Comment by eps1lon** [comment]
I also tried with Turbopack and it did work. Please include a repro with the code you have locally. It's not clear where you added the `--turbopack` flag. Could also be an issue with your lockfile which is why a cloneable repro of your code is so important.

**Comment by jsdev-robin** [comment]
> I also tried with Turbopack and it did work. Please include a repro with the code you have locally. It's not clear where you added the `--turbopack` flag. Could also be an issue with your lockfile which is why a cloneable repro of your code is so important.

This issue occurs with npm, but not with pnpm. In the project, the default two apps web and docs build successfully with npm. However, when a new app is installed, this issue appears. After installing a new app using npx create-next-app@latest apps/new-app, running the build command results in an error.

**Comment by icyJoseph** [comment]
Mmm I was able to get some similar error message, all I did was cd into apps, and `create-next-app` a new project. Then back up to the root, and `npm run build` errored - I ran `npm dedupe` at the root and it worked again 🤔 -

_I think_ the problem is that the create-next-app has a pinned dep to 19.1.0 react and react-dom - cuz installing 19.1.1 kind works too, but I am guessing at this point. Please do make a repository - including lock file - with a broken state.

**Comment by jsdev-robin** [comment]
> Mmm I was able to get some similar error message, all I did was cd into apps, and `create-next-app` a new project. Then back up to the root, and `npm run build` errored - I ran `npm dedupe` at the root and it worked again 🤔 -
> 
> _I think_ the problem is that the create-next-app has a pinned dep to 19.1.0 react and react-dom - cuz installing 19.1.1 kind works too, but I am guessing at this point. Please do make a repository - including lock file - with a broken state.

Bro, I’ve already fixed it. Thanks a lot for your feedback!

**Comment by ukcw** [comment]
hey, how did you fix this?

**Comment by jsdev-robin** [comment]
> hey, how did you fix this?

I used pnpm instead of npm because it is recommended for monorepos and maintains the lockfile more efficiently.

**Comment by andrewpeters9** [comment]
FYI, upgrading to `15.5.1-canary.4` fixed this issue for me

**Comment by Vercjames** [comment]
Error persists. Next 15.5.3. Fresh npmx create-next-app.

npx create-next-app@latest
✔ What is your project named? … my-test
✔ Would you like to use TypeScript? … No / Yes
✔ Which linter would you like to use? › ESLint
✔ Would you like to use Tailwind CSS? … No / Yes
✔ Would you like your code inside a `src/` directory? … No / Yes
✔ Would you like to use App Router? (recommended) … No / Yes
✔ Would you like to use Turbopack? (recommended) … No / Yes
✔ Would you like to customize the import alias (`@/*` by default)? … No / Yes


[TypeError: Cannot read properties of null (reading 'useContext')]
Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
[TypeError: Cannot read properties of null (reading 'useContext')]
Export encountered an error on /_error: /404, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null

**Comment by icyJoseph** [comment]
Unfortunately this doesn't happen to everybody, it is actually not really clear what's happening...

@Vercjames which React and React-DOM versions do yo have?

**Comment by LindaJatique** [comment]
It happens to me the error is just strange

**Comment by jsdev-robin** [comment]
> It happens to me the error is just strange

Use pnpm, it will fix the issue.

**Comment by LindaJatique** [comment]
> > It happens to me the error is just strange
> 
> Use pnpm, it will fix the issue.

i already use pnpm ....... i am on a pnpm monorepo

**Comment by icyJoseph** [comment]
mmm try deduping your dependencies, run `pnpm dedupe --check` first for a dry run.

**Comment by jsdev-robin** [comment]
> > > It happens to me the error is just strange
> > 
> > 
> > Use pnpm, it will fix the issue.
> 
> i already use pnpm ....... i am on a pnpm monorepo

If pnpm doesn’t fix this issue, then it’s not pnpm’s fault—you probably have a misconfiguration in your setup.

**Comment by ObinnaAka** [comment]
Updating to next@15.6.0-canary.44 helped with this. Based on the commit from [0xNedAlbo](https://github.com/0xNedAlbo) [ef763ae](https://github.com/0xNedAlbo/duncan-ui/commit/ef763ae2305c7048283f8c87d106ae7991d9bcc3)

Seems like it was a bug in the Next framework.

**Comment by staszek998** [comment]
Updating the `next` package to the `15.6.0-canary.X` version fixed the issue for me as well. I first tried `15.6.0-canary.44`, as mentioned by @ObinnaAka in the previous comment (thank you!), and once I confirmed it worked, I upgraded to the latest canary release — `15.6.0-canary.57` — which also works perfectly! 🥳  

So I'd say it might be safe to assume that any release after `15.6.0-canary.44` (including `15.6.0-canary.45`, `15.6.0-canary.57`, `15.6.0`, `15.7.0`, etc.) should work fine as well 🙂

**Comment by jsdev-robin** [comment]
@staszek998 You're right — the canary version may have fixed the issue for now, but using canary builds in production isn’t recommended. Canary releases are experimental and may include untested changes that could break unexpectedly in future updates.

I’m only using it temporarily to verify the fix and confirm stability. Once the official stable version (e.g., 15.6.0 or newer) includes the same patch, I’ll switch back to that to ensure long-term reliability and predictable behavior in production.
