### ISSUE TITLE
Turbopack file tracing includes repository root: can’t access reasons during real build

### ISSUE THREAD

**Issue by gadcam** [vercel/next.js#84960]
### Link to the code that reproduces this issue

https://github.com/gadcam/next.js

### To Reproduce

Run: `npx next build --turbopack`

Inspect generated trace files: `**/*.js.nft.json`

Observe that, for certain `page.ts` files, file tracing appears to include the entire repository root.

### Actual behavior

File tracing includes the repo root (e.g., README.md, Makefile, etc.) for some pages, leading to oversized Serverless Functions.

During a real Next/Turbopack build, I cannot surface the reasons map from nodeFileTrace, so I can’t understand why these files are pulled in.

### Expected behavior

File tracing should not include unrelated files from the repository root for these entries.

There should be a supported way to inspect the reasons map (or equivalent) in the real build pipeline to explain why each file is traced.

### Example of output
```json
{
  "version": 1,
  "files": [
    "../../../../../../Makefile",
    "../../../../../../README.md",
    "../../../../../../components.json",
    "...",
    "../../../../chunks/ssr/src_messages_fr_json_3c6a9a9a._.js",
    "./page/react-loadable-manifest.json",
    "./page_client-reference-manifest.js"
  ]
}
```

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 16093
  Available CPU cores: 16
Binaries:
  Node: 22.20.0
  npm: 11.6.2
  Yarn: N/A
  pnpm: N/A
Relevant Packages:
  next: 15.5.5 // Latest available version is detected (15.5.5).
  eslint-config-next: 15.5.5
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Turbopack

### Which stage(s) are affected? (Select all that apply)

next build (local), Vercel (Deployed)

### What I tried

1) Running `@vercel/nft` directly
Result: this traces far fewer files than the real Next/Turbopack build, so it doesn’t mirror real build conditions and doesn’t explain the oversized output.
<details>

<summary>The script</summary>

```js
#!/usr/bin/env node
import { nodeFileTrace } from '@vercel/nft';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function printStack(file, reasons, stdout, cwd, depth = 0) {
  const indent = '  '.repeat(depth);
  stdout.push(`${indent}${file}`);

  const reason = reasons.get(file);

  if (
    !reason ||
    !reason.parents ||
    (reason.type.length === 1 &&
      reason.type.includes('initial') &&
      reason.parents.size === 0)
  ) {
    return;
  }

  // Show why this file was included
  const types = Array.from(reason.type).join(', ');
  stdout.push(`${indent}  └─ Reason: ${types}`);

  for (let parent of reason.parents) {
    printStack(parent, reasons, stdout, cwd, depth + 1);
  }
}

async function main() {
  const files = [
    path.join(__dirname, '.next/server/app/[locale]/PATH_TO_MY_PAGE/page.js'),
  ];

  console.log(`Tracing files:\n${files.join('\n')}\n`);

  try {
    const { fileList, reasons } = await nodeFileTrace(files, {
      base: process.cwd(),
      processCwd: process.cwd(),
      mixedModules: true,
      conditions: ['node', 'import', 'require', 'default', 'module', 'production'],
      ignore: [
        '**/*.map',
        '**/node_modules/.bin/**',
        '**/.next/cache/**',
        '**/next/dist/**',
      ],
      exportsOnly: true,
    });

    console.log('Traced files with dependency chains:');
    console.log('=====================================\n');

    for (const file of fileList) {
      console.log(`📁 ${file}`);
      const stack = [];
      printStack(file, reasons, stack, process.cwd());

      // Remove the first line since we already printed the file name
      stack.shift();

      if (stack.length > 0) {
        console.log('Dependencies:');
        console.log(stack.join('\n'));
      } else {
        console.log('  └─ Entry point (no dependencies)');
      }
      console.log('');
    }

    console.log(`Total: ${fileList.size} files`);
  } catch (err) {
    console.error('Error while tracing files:', err);
    process.exit(1);
  }
}

main();
```

</details>

2) Patching Next’s bundled `@vercel/nft`
I temporarily patched `node_modules/next/dist/compiled/@vercel/nft/index.js` to write out {file, types, parents} for each entry in r.fileList:
Result: in a real build, the debug output only shows entries under `node_modules`. I don’t see the application files or repo-root files that appear in `*.js.nft.json`, so I still can’t identify the chain of inclusion.

<details>

<summary>The patch to `nodeFileTrace`</summary>

```js
const s = {
  fileList: r.fileList,
  esmFileList: r.esmFileList,
  reasons: r.reasons,
  warnings: r.warnings,
};

const path = (() => {
  try { return require('path'); } catch (_) { return eval('require')('path'); }
})();

let fs;
try {
  // Prefer normal require when available
  if (typeof require === 'function') {
    fs = require('fs');
  } else {
    // Fallback to eval('require') which avoids static analysis by bundlers
    fs = eval('require')('fs');
  }
} catch (err) {
  // Last-ditch async fallback if running in ESM async context
  try {
    // This requires the surrounding function to be async. Use only if safe.
    // const mod = await import('fs'); fs = mod.default || mod;
    fs = null;
  } catch (e) {
    fs = null;
  }
}

try {
  const out = []; // build your 'out' array earlier as before
  for (const file of r.fileList) {
    const reason = r.reasons.get(file);
    const types = reason ? Array.from(reason.type).join(', ') : '(no reason)';
    const parents = reason && reason.parents ? Array.from(reason.parents) : [];
    out.push({ file, types, parents });
  }

  if (fs) {
    const outFile = path.join(process.cwd(), '.next', 'nft-debug.json');
    // ensure dir exists
    try { fs.mkdirSync(path.dirname(outFile), { recursive: true }); } catch (_) {}
    fs.writeFileSync(outFile, JSON.stringify(out, null, 2));
    console.log('NFT debug written to:', outFile);
  } else {
    // If fs is not available, emit a small signal to the console with summary info
    // Avoid printing the entire trace to stdout to prevent blocking
    console.error('fs not available in this context. First 20 traced files:');
    console.error(out.slice(0, 20).map(o => `${o.file} -> ${o.types}`).join('\n'));
  }
} catch (e) {
  try { console.error('Failed to write nft debug:', e && e.stack ? e.stack : String(e)); } catch (_) {}
}
  return s;
}
```

</details>

### Questions / help requested

How can I surface the reasons map during a real Next/Turbopack build?
Is there a supported hook/flag to dump trace reasons (per entry) that mirrors the production build?

If this isn’t possible today, what would you recommend adding (CLI flag, env var, or debug callback) so we can reliably get:
- the traced file list and
- the reasons/parent chain for each file

I’d be happy to contribute documentation or even a small patch to improve the debug tooling, if that’s within reach for contributors.

**Comment by gadcam** [comment]
Also note that building without `--turbopack` gives `*.nft.json` without the root folder files

**Comment by mischnic** [comment]
Turbopack doesn't use `@vercel/nft` anymore. It's implemented in rust now.

The best way to debug this right now running `NEXT_TURBOPACK_TRACING=1 next build --turbopack` and using `next internal trace .next/trace-turbopack` to view it on https://trace.nextjs.org/
Search for `trace file` and `trace directory` to find the related parts. 
There are also various improvements in the v16 canary relasese that aren't (yet) released in 15.

**Comment by gadcam** [comment]
@mischnic Thank you for the command to run!
I will test it now.

I ended up doing a "dichotomy" deleting files and checking `*.nft.json` impact.
Apparently the culprit could be that in `src/app/global-error.tsx` I was importing
```ts
import { reportError } from '@/lib/reportError';
```
where reportError is
```ts
import { captureException } from '@sentry/nextjs';

export function reportError<T>(error: T) {
  captureException(error);
}
```
With `@sentry/nextjs` up-to-date.

The weird thing being that locally I can see `*.nft.json` being fixed but trying to deploy it to Vercel I still have the same issue.

I will keep you posted.

**Comment by mischnic** [comment]
At least one case of entry was fixed in https://github.com/vercel/next.js/pull/83452
That will be backported to v15 today, hopefully

**Comment by gadcam** [comment]
Glad to hear that :)
There is indeed in this package at least a nice
```js
fs.readFileSync(path.join(process.cwd(), ...pathSegments), 'utf-8')
```
However, I am not sure this fix is enough for this specific case.

I did the following
```sh
$ npm i next@16.0.0-canary.9 --force
...
$ rm -Rf .next
$ npx next build --turbopack
...
```
The build did not complete but it went far enough so that I could see in `*.nft.json` files that the problem is still here.

**Comment by mischnic** [comment]
Can you share the .next/trace-turbopack file?

Otherwise you can look at it yourself, using the instructions above.
If you search for the file that you think shouldn't be in the nft list, then it might also show you which files ends up pulling that in.

**Comment by gadcam** [comment]
I installed 15.5.6 and did a new build.

If I can avoid sharing the full trace I would rather avoid doing it or share it privately at least.

I can do 3 observations based on the trace file

1. `trace file` gives not result.

2. Looking for `trace directory` indeed point only to one file in my project `[project]/src/lib/reportError.ts [app-ssr] (ecmascript)`.

Here we have 2 path, both pointing in the end to `@opentelemetry/instrumentation/build/esm/platform/node/instrumentation.js`

<details><summary>node_modules/@opentelemetry/instrumentation/build/esm/platform/node/instrumentation.js</summary>
Span Attributes:
name	[project]/node_modules/@opentelemetry/instrumentation/build/esm/platform/node/instrumentation.js [app-ssr] (ecmascript)
Path trace:

    page endpoint HTML /_error
        page client side rendering
            module graph for app
                module [project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/[locale]/conditions/page { GLOBAL_ERROR_MODULE => "[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_0 => "[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_1 => "[project]/src/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_2 => "[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_3 => "[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)", MODULE_4 => "[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)", MODULE_5 => "[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_6 => "[project]/src/app/[locale]/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_7 => "[project]/src/app/[locale]/conditions/page.tsx [app-rsc] (ecmascript, Next.js Server Component)" } [app-rsc] (ecmascript)
                    module [project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)
                        chunkable reference
                            module [project]/src/app/global-error.tsx [app-rsc] (ecmascript)
                                module [project]/src/app/global-error.tsx [app-rsc] (client reference proxy)
                                    chunkable reference
                                        module [project]/src/app/global-error.tsx [app-ssr] (ecmascript)
                                            module [project]/src/lib/reportError.ts [app-ssr] (ecmascript)
                                                module [project]/node_modules/@sentry/nextjs/build/cjs/index.server.js [app-ssr] (ecmascript)
                                                    module [project]/node_modules/@sentry/node/build/cjs/index.js [app-ssr] (ecmascript)
                                                        module [project]/node_modules/@sentry/node/build/cjs/integrations/tracing/postgresjs.js [app-ssr] (ecmascript)
                                                            module [project]/node_modules/@opentelemetry/instrumentation/build/esm/index.js [app-ssr] (ecmascript)
</details>

<details><summary>node_modules/@prisma/instrumentation/node_modules/@opentelemetry/instrumentation/build/esm/platform/node/instrumentation.js</summary>
name	[project]/ [app-ssr] (ecmascript)
Path trace:

    page endpoint HTML /_error
        page client side rendering
            module graph for app
                module [project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/[locale]/conditions/page { GLOBAL_ERROR_MODULE => "[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_0 => "[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_1 => "[project]/src/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_2 => "[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_3 => "[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)", MODULE_4 => "[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)", MODULE_5 => "[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_6 => "[project]/src/app/[locale]/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_7 => "[project]/src/app/[locale]/conditions/page.tsx [app-rsc] (ecmascript, Next.js Server Component)" } [app-rsc] (ecmascript)
                    module [project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)
                        chunkable reference
                            module [project]/src/app/global-error.tsx [app-rsc] (ecmascript)
                                module [project]/src/app/global-error.tsx [app-rsc] (client reference proxy)
                                    chunkable reference
                                        module [project]/src/app/global-error.tsx [app-ssr] (ecmascript)
                                            module [project]/src/lib/reportError.ts [app-ssr] (ecmascript)
                                                module [project]/node_modules/@sentry/nextjs/build/cjs/index.server.js [app-ssr] (ecmascript)
                                                    module [project]/node_modules/@sentry/node/build/cjs/index.js [app-ssr] (ecmascript)
                                                        module [project]/node_modules/@sentry/node/build/cjs/integrations/tracing/prisma.js [app-ssr] (ecmascript)
                                                            module [project]/node_modules/@prisma/instrumentation/dist/index.js [app-ssr] (ecmascript)
                                                                module [project]/node_modules/@prisma/instrumentation/node_modules/@opentelemetry/instrumentation/build/esm/index.js [app-ssr] (ecmascript)
</details>

I can see in this file there is this.
Could it be the code triggering the bug ?
```ts
    InstrumentationBase.prototype._extractPackageVersion = function (baseDir) {
        try {
            var json = readFileSync(path.join(baseDir, 'package.json'), {
                encoding: 'utf8',
            });
            var version = JSON.parse(json).version;
            return typeof version === 'string' ? version : undefined;
        }
        catch (error) {
            diag.warn('Failed extracting version', baseDir);
        }
        return undefined;
    };
```

3. However when I am looking for a documentation file that should not be included to the function I only find this path
<details><summary>[project]/styles/globals.css</summary>
Path trace:

    page endpoint HTML /_error
        page client side rendering
            module graph for app
                module [project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/[locale]/eurogames/page { GLOBAL_ERROR_MODULE => "[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_0 => "[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_1 => "[project]/src/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_2 => "[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_3 => "[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)", MODULE_4 => "[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)", MODULE_5 => "[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_6 => "[project]/src/app/[locale]/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_7 => "[project]/src/app/[locale]/eurogames/page.tsx [app-rsc] (ecmascript, Next.js Server Component)" } [app-rsc] (ecmascript)
                    module [project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/[locale]/eurogames/page { GLOBAL_ERROR_MODULE => "[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_0 => "[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_1 => "[project]/src/app/error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_2 => "[project]/src/app/not-found.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_3 => "[project]/node_modules/next/dist/client/components/builtin/forbidden.js [app-rsc] (ecmascript, Next.js Server Component)", MODULE_4 => "[project]/node_modules/next/dist/client/components/builtin/unauthorized.js [app-rsc] (ecmascript, Next.js Server Component)", MODULE_5 => "[project]/src/app/global-error.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_6 => "[project]/src/app/[locale]/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)", MODULE_7 => "[project]/src/app/[locale]/eurogames/page.tsx [app-rsc] (ecmascript, Next.js Server Component)" } [app-rsc] (ecmascript) <locals>
                        module [project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js Server Component)
                            chunkable reference
                                module [project]/src/app/layout.tsx [app-rsc] (ecmascript)
                                    module [project]/styles/globals.css [app-client] (css, css client reference)
                                        chunkable reference
                                            module [project]/styles/globals.css [app-client] (css)
</details>

Does it help to understand the issue ?

**Comment by gadcam** [comment]
I would lean on the `globals.css` option as after patching the two versions of `_extractPackageVersion` I still get the issue.
And looking into the details of `globals.css` I can see the files being pulled clearly whereas in `@opentelemetry/instrumentation` I can only see things like
- `pattern: (<dynamic> '/package.json' | <dynamic> 'package.json')`
- `pattern: ('/etc/' <dynamic> | '/etc' <dynamic>)`

and the resulting reads are not worrying.

**Comment by gadcam** [comment]
Apparently having `@import 'tailwindcss';` in the `global.css` is enough so that `parse_css` read the files.
And if I remove this line, locally the files are not read or added to the functions.
EDIT: Changing it into `@import 'tailwindcss' source('../src');` ensure the files are not read but does not fix the issue.

In Vercel the build still fails.

Sometimes I saw this in my tests but I am unsure when it happens or not
`('/ROOT/' <dynamic> | '/ROOT' <dynamic>)`
```
Path trace:

    page endpoint HTML /_error
        page client side rendering
            module graph for app
                module [project]/instrumentation.ts [instrumentation] (ecmascript)
                    module [project]/node_modules/@sentry/nextjs/build/cjs/index.server.js [instrumentation] (ecmascript)
                        module [project]/node_modules/@sentry/nextjs/build/cjs/config/withSentryConfig.js [instrumentation] (ecmascript)
```

I will try to understand what could be the difference between Vercel and locally

**Comment by mischnic** [comment]
You can send me a DM here if you want to share it privately: https://x.com/mischnic

> `('/ROOT/' <dynamic> | '/ROOT' <dynamic>)`

That would definitely cause everything to be included. But with 15.5.6, the sentry npm package shouldn't be able to pull in all of your app's project code anymore.

**Comment by gadcam** [comment]
Locally I can not reproduce (anymore?) with 15.5.6.
I finally succeeded to build with 15.5.6.
But only after another build where I deleted old unused files in `public/assets`.
I'm starting to guess if it is not the step `Collected static files` that load some more things into the function.
The weird thing being that according to Vercel my heaviest function now weights 151.0 MB.
Which is far from the limit.

```
Traced Next.js server files in: 1.224s
Created all serverless functions in: 1.780s
Collected static files (public/, static/, .next/static): 76.792ms
Build Completed in /vercel/output [6m]
Deploying outputs...
Deployment completed
Creating build cache...
Created build cache: 34.177s
Uploading build cache [354.61 MB]
Build cache uploaded: 5.938s
```

What would you suggest to do next to investigate this ?

**Comment by mischnic** [comment]
Are you using Turbopack Builds on Vercel?
If you see `Collected static files`, then you don't.
That would be one potential difference then
> I will try to understand what could be the difference between Vercel and locally

**Comment by gadcam** [comment]
Is "Turbopack Builds" a specific feature to enable in Vercel ?
Or the fact that we use the `--turbopack` flag enable Turpoback build as locally ?

The exact command that we use is (copy pasted from build logs)
```sh
cross-env NODE_OPTIONS=--max-old-space-size=6144 prisma generate && next build --turbopack
```

**Comment by mischnic** [comment]
No, when deploying to Vercel, it also merely executes `next build` and then uploads the static assets and serverless functions in the `.next` folder.
So you should be able to replicate this locally as well

**Comment by BlvckParrot** [comment]
I can confirm it is still happening in 16.0.7. In my case the whole root folder - all files are copied duplicated unmodified in .next/standalone. Also in .next/standalone/node_modules there is whole typescript, which I would say is not runtime dependency.

_Edit by maintainer bot: Comment was **automatically** minimized because it was considered unhelpful. (If you think this was by mistake, let us know). Please only comment if it adds context to the issue. If you want to express that you have the same problem, use the upvote 👍 on the issue description or subscribe to the issue for updates. Thanks!_

**Comment by marcoshernanz** [comment]
Thanks for working through this with us. The dependency-driven `process.cwd()` case was addressed by #83452 and released in 15.5.6, after which the original issue was no longer reproducible locally. Current releases also provide source-level warnings and tracing tools for whole-project filesystem traces. Since there is no current reproduction, I’m going to close this. If it still occurs on the latest release, please open a new issue with a minimal reproduction and the relevant trace details.
