### ISSUE TITLE
`loading.js` sometimes causes soft-navigation to get stuck and not render the new page, despite receiving it from the server

### ISSUE THREAD

**Issue by mogzol** [vercel/next.js#86151]
### Link to the code that reproduces this issue

https://github.com/mogzol/next-stuck-navigation-repro

Relevant components:
- [RefreshButton.tsx](https://github.com/mogzol/next-stuck-navigation-repro/blob/main/src/components/RefreshButton.tsx) - Calls `router.refresh()` to trigger the soft refresh that sometimes gets stuck
- [page.tsx](https://github.com/mogzol/next-stuck-navigation-repro/blob/main/src/app/page.tsx) - Renders the refresh button as well as several slow client components that increase page size and render time
- [loading.tsx](https://github.com/mogzol/next-stuck-navigation-repro/blob/main/src/app/loading.tsx) - The page's loading UI. This file existing causes the issue to occur. The actual contents of the loading UI don't seem to matter, just whether it exists or not.

### To Reproduce

1. Start the application **in production mode** (`npm run build && npm run start`)
2. Open the page in your browser and press the "Refresh" button on the page to trigger a soft refresh (calls `router.refresh()`)
3. Observe that sometimes the new page never loads, and the loading indicator stays visible indefinitely.
    - The request for the new page still completes successfully in the network monitor
    - Changing network request throttling can make this issue more or less likely ("Fast 4G" almost always triggers it, "Slow 4G" never does)
    - Changing the `GARBAGE_ITEMS` environment variable before starting the app also makes the issue more or less likely
        - `GARBAGE_ITEMS=10 npm run start` - Almost never has the issue
        - `GARBAGE_ITEMS=100 npm run start` - Almost always has the issue
    - Removing the `loading.tsx` file for the page makes the issue go away completely

Here's a screen recording showing the issue. The first couple refreshes work fine, but then it gets stuck on the third one. Then after performing a full page reload, it gets stuck again on the first refresh. Then after changing the network request throttling to "Slow 4G", the issue goes away.

https://github.com/user-attachments/assets/6ec273db-20b8-4f97-9310-04c8e13aa007

### Current vs. Expected behavior

I would expect the soft refresh to always work, and never get stuck. Currently, if a page has a `loading.js` file, it randomly gets stuck. It seems that this is more likely if your page has client components that take a while to render.

### Provide environment information

```bash
Operating System:
  Platform: win32
  Arch: x64
  Version: Windows 11 Pro
  Available memory (MB): 32673
  Available CPU cores: 24
Binaries:
  Node: 24.11.1
  npm: 11.6.2
  Yarn: 1.22.22
  pnpm: 10.7.1
Relevant Packages:
  next: 16.0.3 // Latest available version is detected (16.0.3).
  eslint-config-next: N/A
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
Next.js Config:
  output: N/A
```

I also tested this on macOS and confirmed it occurs there. I have tested both Chrome and Firefox and the issue occurs in both.

### Which area(s) are affected? (Select all that apply)

Linking and Navigating

### Which stage(s) are affected? (Select all that apply)

next start (local), Other (Deployed)

### Additional context

I have been able to reproduce this issue on both Next.js 15 and Next.js 16, I'm not sure when it was introduced. As mentioned above, it only seems to happen on pages that have a `loading.tsx` file. I haven't been able to reproduce it for pages that don't have a loading UI.

**Comment by mogzol** [comment]
Updated the title and description a bit to make it more clear that this seems to be caused by a page having a loading UI (`loading.js`, `loading.tsx`, etc.). I don't 100% know that the loading UI is actually the issue, but it's certainly a part of it since the issue goes away when I remove it.

EDIT: After more testing, I think that any Suspense boundaries can lead to this issue, not just the `loading.js` file.

**Comment by Akash0463** [comment]
Facing same issue after upgrading the next js version from 15 to 16, any solutions yet?

**Comment by mogzol** [comment]
Unfortunately no. I just removed all suspense boundaries from my app until a solution is found. Makes page load and UX a bit worse but at least the page doesn't randomly get stuck.

**Comment by shipleyc-zen** [comment]
I'm seeing the same thing, the weird part is that it is only affecting my higher environments. Locally I don't seem to be having an issue.

**Comment by EthicalJobsJesse** [comment]
We also are seeing a similar thing in very specific but reproducible scenario, only on prod builds, usually when there were a lot of server actions firing after a navigation completes (although we are on v14.2.32). One thing I ended up tracking down was the root ActionQueue Context and the appRouterState got out of sync with each other, and all Action Queue updates after that desync happened didn't update the appRouterState, so no browser navigation was ever triggered. All navigations (and I assume server action redirects) after this point fired off a network request to prefetch, but never actually navigated.

Are you able to add a soft navigation to the page as well, e.g. a Next Link or router.push to another part of the site, and see if the following values desync (in particularly the canonicalUrl)? If so it may be the same issue

ActionQueueContext: state
<img width="1232" height="391" alt="Image" src="https://github.com/user-attachments/assets/255d4e00-65a0-4f6d-96df-fa7d9c92bbac" />

appRouterState (comes from with Router Component)
<img width="1237" height="397" alt="Image" src="https://github.com/user-attachments/assets/ae8eb748-138d-4890-900c-97391a76ab20" />

I wasn't able to get to an underlying cause, and we ended up just doing a hacky monitor to see when these desync and force a hard browser navigation as it was so rare, but I'm happy to some more details if it turns out to be the same issue

**Comment by mogzol** [comment]
@EthicalJobsJesse Yeah any soft navigation causes the issue so I assume it is the same problem. My reproduction uses `router.refresh`, but if I change it to `router.push` or `router.replace` the exact same thing happens.

I would be interested to see how you are detecting when this happens if you don't mind sharing.

-----

EDIT: Actually I haven't been able to reproduce it when I `router.push` to a different page, only to the same URL, but obviously in that case `canonicalUrl` would be the same. But the `state.cache.navigatedAt` value does get desynced for me when the issue happens. Normally the action queue state and app router state always have the same `navigatedAt` value, but when the navigation gets stuck, the action queue state value is a more recent timestamp than the app router state.

**Comment by EthicalJobsJesse** [comment]
@mogzol I feel like it is the same underlying cause. The action queue does two updates when it's completed the task (navigate, server action, restore, etc): https://github.com/vercel/next.js/blob/6ebbe75d01906af5a1913b3d0c6d48ebdbfa3960/packages/next/src/client/components/app-router-instance.ts#L127. Line 127 sets the ActionQueueContext value. This is a mutable object (I'm assuming for performance), so by itself it doesn't trigger any re-renders or updates. Line 130 (https://github.com/vercel/next.js/blob/6ebbe75d01906af5a1913b3d0c6d48ebdbfa3960/packages/next/src/client/components/app-router-instance.ts#L130) applies the same result as the resolved promise value which is used for the appRouterState. So they are always meant to be in sync.

How the navigation works is when the navigation event is fired it will set the appRouterState to be a promise, and the use React.use on that promise to trigger suspense mode until that promise is resolved. This appRouterState is updated to a new unresolved promise each time a new action is added to the queue. In theory this should all work reliably, the ActionQueueContext is updated directly, then the appRouterState promise is resolved, the React.use now has a resolved value so continues onto the next part in which the comparison to the current browser url and next state is checked and any updates get applied.

What I've found in practice is when things desync the appRouterState promise for some reason doesn't actual get set in the Router any more. The promise should be set in here (https://github.com/vercel/next.js/blob/6ebbe75d01906af5a1913b3d0c6d48ebdbfa3960/packages/next/src/client/components/use-action-queue.ts#L56). And when I add logging, the setState function is being called, but it's just not within that hook (no hook re-renders occur). This means any event you fire off after that point creates a promise, but it's not actually hooked into anything. My best guess is some complex re-rendering/closure/mutable context thing where two copies of the setState function are made but one is no longer within React properly, but I don't know enough about React internals to go any deeper.

The strange thing for me is in my case if you let it run a little longer before navigating, most of the time it will correctly link the setState back into that hook. It's only for a short amount of time it's de-sync's things, which makes me think it's a more underlying issue with Next/React.

Not sure if that makes a whole lot of sense, let me know if there's any more details I can add to help clarify things.

**Comment by mogzol** [comment]
Interesting, thanks for the explanation, that does makes sense, I agree it is probably the same issue.

**Comment by karlkeefer** [comment]
Next 15 w/ App router reporting in. This bug has been making our integration tests flaky in a really-tough-to-debug way. We've since observed it several times in production as well. Now in the process of tearing out all the suspense boundaries to see if it helps! If not, @EthicalJobsJesse's hacky desync monitor might be in our future 🙈 

Thanks for the initial write-up and follow-ups @mogzol 🙇‍♂️

**Comment by dennischen0** [comment]
Also experiencing this on 15.5.15. Navigation gets stuck intermittently when using loading.jsx at the layout level. Removing the loading.jsx file resolves the issue. Looking forward to a fix!

**Comment by rgembalik** [comment]
Same here. Soft refreshes do not provide newest content while browser refresh does. The curl request for `rsc` content shows me that the latest data is present in the response - i.e. server produces good content, while client-side router does not use it. The same pattern works without issues on page that do not have `loading.tsx`. I would love to see some solution that do not rely on removing `loading.tsx` (or any other `Suspense` boundry). Additionally `isPending` on `useTransition` (if we used transition to detect when refresh finishes as it is common pattern around App Router refresh) stays set to `true` whenever this happens and never settles to `false`.

**Comment by rgembalik** [comment]
The most painful use case we've hit with this is our CMS integration's live preview:

- Editor makes a change
- A WebSocket receives a refresh signal
- The page calls `router.refresh()` to re-render with the new content

The code is too complex to reduce to a minimal example, but this is what eventually led us to this issue. The refresh works for a while, then suddenly stops. The transition gets stuck in a pending state, so no refresh completion is ever detected and we fall back to a timeout. Even after the timeout, content stops updating entirely. The only known fix is a full browser reload - which makes for a very poor live editing experience.

**Comment by daniellskelton** [comment]
This still seems to be an issue

I tested the reproduction with Next 16.2.6 and its still occurring - even without throttling connection.

**Comment by errmakov** [comment]
## Deterministic repro on 16.2.9 + React 19.2.7 (and 16.3.0-canary.67) — boundary is the gate

Public minimal reproduction: **https://github.com/errmakov/next-soft-nav-segment-drop-repro**

I hit this in a production app and reduced it to a clean room that reproduces **deterministically** (~100% per attempt, not a lottery) and isolates it to **two ingredients that must co-occur**. The thread already has the mechanism (the `ActionQueueContext` ↔ `appRouterState` desync @EthicalJobsJesse described); this adds a toggled factorial and the `$RC`/`$~` DOM signature from the auto-closed #94170.

### Two ingredients — the `loading.tsx` boundary is the gate

| `loading.tsx` boundary | Server Action in-flight during the nav | drops/attempt |
| --- | --- | --- |
| **ON** | **ON** | **~100%** (30/30) |
| **OFF** | ON | **0%** (0/30) |
| ON | only at cold start (long session, no reload) | ~0.4% (1/240) |

So — consistent with the title — the **loading boundary enables it**, but only when a Server Action settles *inside* the boundary-gated navigation window. In my repro that window exists right after a fresh load (a provider's slow fetch-on-mount actions are still resolving), so reloading before each navigation makes it fire every time — matching the OP's "after a reload it gets stuck again". Removing the boundary takes it to 0% but reintroduces the "URL never commits for the full server render" failure on `force-dynamic` routes, so it isn't a usable workaround.

What is **not** the lever (ruled out by measurement): network throttling (100% with throttle off), destination render/payload bulk (mogzol-style `GARBAGE_ITEMS` changed nothing), and *more* client churn (re-firing the provider actions every nav actually drove it to 0%).

### Measured (production build, `next build && next start`)

```
=== SEGMENT-DROP SAMPLE  ITER=25 ===
staff arrivals : ok=25 drop=0
sched arrivals : ok=0  drop=25
TOTAL navs=50 drops=25 (50.0%)
  #0  SCHED-DROP cls=SIG-A stale(staff@schedule) url=.../staff
  ... (every staff -> schedule navigation drops; staff navs, no boundary, all pass)
```

Surface here is **Signature A**: URL moves to `/staff/[id]/schedule`, the segment never renders, navigation bounces back to `/staff`. (The source app also showed **Signature B**: the `[id]` layout chrome renders but its `{children}` segment stays empty.)

### DOM / stream signature (the #94170 angle)

On a drop, the boundary opener is emitted as `$~` (postpone) instead of `$?`, and the `$RC` swap that should move the resolved subtree out of `<div id="S:N" hidden>` no-ops — the correct content is server-rendered and sitting in the hidden div, never swapped in. #94170 described exactly this but was auto-closed for lacking a public repro; the repo above is that missing repro.

On **`16.3.0-canary.67`** it still reproduces (~95%), and additionally logs, server-side:

```
⨯ Error: The destination stream closed early.
```

i.e. the server observing the client abandon the RSC stream for the dropped navigation.

### Notes

- Production only; does not reproduce in `next dev`.
- Reproduces at 100% with **no** network throttling; a `THROTTLE=fast4g` knob is included to match the OP's "Fast 4G almost always" observation.

Happy to adjust the repro (strip further, add an instrumented `onRouterTransitionStart` / route-mismatch trace from the new router-instrumentation hooks, or bisect the regression) if that helps triage.

**Comment by errmakov** [comment]
## Bisected: re-introduced in `15.5.1-canary.8` by #82674 ("optimize server action refresh logic")

Following up on the repro I posted (https://github.com/errmakov/next-soft-nav-segment-drop-repro) — I bisected against published canaries, with **React pinned to 19.2.7 throughout** (to remove it as a variable) and the deterministic repro as the good/bad oracle. The result is **non-monotonic**, which is the useful part:

| version (React 19.2.7) | repro |
| --- | --- |
| ≤ 15.1.x | broken |
| **15.2 – 15.5.1-canary.7** | **fixed** |
| **15.5.1-canary.8 → 16.2.9 (and 16.3.0-canary.67)** | **broken again** |

So it was fixed in 15.2 and **re-regressed at `15.5.1-canary.8`** (`15.5.1-canary.7` is the last good build). The only commit in `v15.5.1-canary.7...v15.5.1-canary.8` that touches the client router runtime is:

**#82674 — "optimize server action refresh logic"** (@ztanner)

It edits `client/components/app-router-instance.ts`, `router-reducer/reducers/server-action-reducer.ts`, `router-reducer/router-reducer-types.ts`, `server/app-render/action-handler.ts`, and adds the `action-discarding` e2e tests. That lines up exactly with the action-queue / discarded-pending-action path described earlier in this thread: when a navigation discards a pending Server Action, the discarded branch runs the remaining actions but the in-flight transition's `setState` can be left unresolved, so the boundary-gated segment never swaps in.

cc @ztanner — the repro flips deterministically across that PR (100% with the `loading.tsx` boundary on, 0% with it off), so it should be a quick confirm. Happy to help.

**Workaround for anyone blocked:** pin `next@15.5.0` (the last stable before #82674 — verified unaffected, 0/30 in the repro). Anything `15.5.1`+ carries the regression.

**Comment by mogzol** [comment]
@errmakov Thanks for the in depth reproduction and write up, I tried your reproduction and verified it does work on next@16.2.9 and not next@15.5.0, however, when I try my original reproduction, it does still occur on next@15.5.0, so maybe these are separate issues?

What also makes me think these are separate issues is that you mention that when the issue occurs, the new DOM content should exist within the `<!--$~-->` boundary, however in my reproduction, there are no DOM updates at all when navigation gets stuck, the new content does not exist anywhere in the DOM.

As a side note, I can no longer reliably reproduce my original reproduction when using "Fast 4G" (or any network throttling), but can reproduce it almost every time with no throttling. I'm on a different computer now though and a different browser version, so maybe something changed there.

**Comment by errmakov** [comment]
**Correction to my earlier mechanism — and a fix PR (#95188)**

I built a clean dist-patch harness (fresh prod build + marker-in-bundle verification on `next@16.2.9`) and need to correct the *mechanism* I gave above. The **bisect stands** — re-confirmed: `15.5.1-canary.7` = 0%, `.8` = 100%, vendored React identical across the boundary; and grafting canary.7's compiled client files onto canary.8 makes it clean. But the cause is **not** the refresh removal.

The regressing change in #82674 is the `runRemainingActions(actionQueue, setState)` call it added to the `if (action.discarded)` branch of `handleResult`. When a Server Action is discarded by a boundary-gated navigation that's still streaming, this fires a `setState` mid-transition and interrupts the destination segment's boundary completion → the segment drops. (Re-instating the eager refresh at any timing does *not* recover it; a `router.refresh()` that works on a boundary-free route still doesn't recover a boundary-gated one — so it was never the refresh.)

Fix in **#95188**: only run remaining actions when the discarded action actually revalidated, so non-revalidating discards no longer disturb the in-flight navigation. Keeps #82674's optimization + revalidation refresh (both `action discarding` tests pass); repro goes 100% → 0%.

@mogzol — thanks for testing. Agreed these look like **two separate issues**: this is the #82674 regression (clean on 15.5.0; destination content present in the hidden `$~` boundary, never swapped). Your original repro breaks on 15.5.0 too and shows *no* destination DOM — an older, distinct bug this PR doesn't address.

**Comment by errmakov** [comment]
The "soft navigation sometimes hangs forever on the loading indicator" variant reported here (the `router.refresh()` case, distinct from the discarded-action segment-drop covered by vercel/next.js#95188) turns out to be a **React** reconciler bug, not a Next.js one — and it's **already fixed upstream**.

### Root cause

Under a `<Suspense>` boundary, a transition that suspends on a **synchronously-resolving RSC/Flight wakeable** can leave its transition lane in a `suspended + warm (prewarmed) + un-pinged` state with **no scheduled callback**. React's ping is recorded with `root.pingedLanes |= root.suspendedLanes & pingedLane`, which is a no-op if the lane isn't *currently* in `suspendedLanes` — and Flight chunks resolve synchronously *during* the render phase, so the terminal ping can land in exactly that window. The resolved content is ready but never commits; the loading fallback stays up forever. (This is why it only reproduces in production builds — dev is slow enough that the wakeable resolves as a normal async microtask instead.)

This is the same family as **facebook/react#35821** ("useDeferredValue gets stuck with a stale value"), fixed by **facebook/react#36134** (merged 2026-03-24).

### It is not in any stable Next.js yet

Next.js vendors React, so the fix arrives via the bundled copy:

| Next.js | Vendored React | Affected? |
|---|---|---|
| 16.2.9 (latest **stable**) | `19.3.0-canary-3f0b9e61-20260317` | ❌ still affected (7 days before the fix) |
| 16.3.0-preview.0 | `19.3.0-canary-43bcbf80-20260603` | ✅ fixed |
| 16.3.0-preview.5 / canary | `19.3.0-canary-247fbb45-20260622` | ✅ fixed |

### A/B against @mogzol's repro

Same machine, same settings (`GARBAGE_ITEMS=300`, 6× CPU throttle, Fast 4G), only the Next version changed:

- **next@16.2.9** → stuck on the **first** refresh, permanently (loading indicator never clears).
- **next@16.3.0-preview.5** → 20/20 refreshes succeed, no stalls.

### What to do

Until Next.js 16.3.0 stable ships, upgrading to `next@16.3.0-preview` (or `next@canary`) picks up the fixed React and resolves this. Staying on the latest stable (16.2.x) will still hang.

A self-contained, Next-free reproduction of the underlying React bug (Vite + `react-server-dom-webpack`, no Next.js) is here for anyone who wants to verify the mechanism independently: https://github.com/errmakov/react-commit-stall-repro

**Comment by mogzol** [comment]
Thanks again @errmakov for looking into this! I can confirm using `16.3.0-preview.5` fixes the issue. I'm going to close this since the bug isn't in next.js and has already been fixed upstream in React.

**Comment by gaearon** [comment]
I think @errmakov is right there's two issues here:

- OP issue was resolved by https://github.com/react/react/issues/35821
- The bug from https://github.com/errmakov/next-soft-nav-segment-drop-repro is still unresolved, with repro and fix attempt in https://github.com/vercel/next.js/pull/95188

The second one is unsolved so let's leave this open for now. I don't think the fix in https://github.com/vercel/next.js/pull/95188 is right so I'm working to reduce it.

**Comment by gaearon** [comment]
Maybe fix for the second issue: https://github.com/vercel/next.js/pull/95391

**Comment by gaearon** [comment]
Full set of fixes for this is out in `16.3.0-canary.76`.
