### ISSUE TITLE
Safari 10 Support

### ISSUE THREAD

**Issue by Timer** [vercel/next.js#9851]
Do we want to support Safari 10? This browser is end-of-life but seems to still have a decent number of active users.

We've had at least two issues crop up about it (I've seen more that I don't have on hand):
Fixes https://github.com/zeit/next.js/issues/9782
Fixes https://github.com/zeit/next.js/issues/9827

This is due to Safari 10 incorrectly implementing `URL`, so Next.js wont work even if users polyfill support back. As a result, client-side transitions try to happen via server-side and fail:

![image](https://user-images.githubusercontent.com/616428/71531393-85161100-28bc-11ea-8b9d-ede2eb705c87.png)

Correct behavior (Safari 11+):
![image](https://user-images.githubusercontent.com/616428/71531417-93fcc380-28bc-11ea-9588-b58d280ee109.png)

**Comment by lachlanjc** [comment]
I ran into this the other day. I was trying to present a site I made on a school computer & all the links didn’t work at all—they didn’t even degrade as I expected to regular a tag behavior, they just didn’t work. Good to know why that was happening.

**Comment by KennyWho** [comment]
How to fix this problem temporarily?

**Comment by ahmadawais** [comment]
Just wanted to chime in here and share that I am having the same issue on iPhone 7/8 for a Next.js/Zeit based game we intend to launch mid January. The app just gets stuck and there isn't much there in the console to file an issue. It's most definitely an issue with routing though.

**Comment by KennyWho** [comment]
In our company's business project, We use next.js with version 9.16, some users report us to could not visit our web app, it makes me so depressed and it is a thorny issue. I try to fix it in my private NPM, I find building the next.js project so difficult.

**Comment by tpreusse** [comment]
We had to roll back from `9.1.6` to `9.1.4` after discovering that all links broke on iOS 10 (reported by users).

In dev I then got «Invalid href passed to router» in the simulator. Downgrading to `9.1.4` solved it:
https://github.com/orbiting/republik-frontend/commit/3aa7513599d45f2d92e5de7d649629c518412448

For us the links completely broke. Not falling back to server-side navigation. It might be a good idea to ensure that native a tag navigation still happens in production when Router throws an error. But would make it harder to detect it in dev 🤷‍♂ 

Move `preventDefault` after `Router` call?
https://github.com/zeit/next.js/blob/1546fcdcfd871cde1ffc0fce4ba9153c2786d0e2/packages/next/client/link.tsx#L189

We also use `next-routes`, maybe the combination had an impact but I don't think so.

**Comment by olpeh** [comment]
This is definitely a blocker for us and we are currently waiting for this to be implemented before upgrading. Hope you could prioritize this.

**Comment by carloscuesta** [comment]
We're using `9.2.0` and found the exact same problem. Can confirm that downgrading to `9.1.4` fixed the problem as @tpreusse points out 🙏

**Comment by timneutkens** [comment]
This issue is solved in 9.2.1

**Comment by carloscuesta** [comment]
Wow! That was fast. Really appreciate the work you put on this project. Thanks!

The issue should be closed then @timneutkens

**Comment by timneutkens** [comment]
We kept it open as there's a few other issues related to native-url.

**Comment by karl** [comment]
It looks like this bug is back in `9.2.2-canary.15`.

I've tested `9.17` and it displays the bug as expected, it is fixed in `9.2.1`, but has re-appeared in `9.2.2-canary.15`.

**Comment by karl** [comment]
Thanks @Timer !

**Comment by olpeh** [comment]
We upgraded to 9.3.3, but links don't work now on iOS 10 Safari.

Seems similar to #9782. Can't confirm right now as I did not see any errors, just that the links did not work – no navigation happened.

**Comment by tpreusse** [comment]
We also got reports about broken links again from old iOS and Android devices.

The problem seems to be that `native-url` returns a protocol on those devices even when it shouldn't. Probably a problem that only occurs in combination with the `url-polyfill` and maybe even then with certain browser engine version. 

@olpeh I used a ultima ratio solution for now and disabled `native-url` via `next.config.js`:
```js
module.exports = {
  webpack: config => {
    const alias = Object.assign({}, config.resolve.alias)
    delete alias.url // alias to native-url
    config.resolve = {
      ...config.resolve,
      alias
    }
    return config
  }
}
```
(by doing that you'll also loose the 7kb optimisation of `native-url` on all platforms)

Specifically broken were: iOS 9.3 (reproduced in Simulator), Android 6 (only reported, not reproduced)

@Timer would you like to see the root issue solved in `native-url`/`url-polyfill` or could you also imagine adapting the protocol check in the router?
https://github.com/zeit/next.js/blob/b274fe39d38111588e625342a89dc568ad38fff5/packages/next/next-server/lib/router/router.ts#L395-L404

(e.g. doing a string check on the unparsed url like `url.match(/^[a-z]+:/)`)

The «not returning a protocol» logic of `native-url` is quite convoluted 🙈 
https://github.com/GoogleChromeLabs/native-url/blob/19aacc0a82f7e36995bde6adc6876f6140d6d06a/src/parse.js#L95-L126
So wouldn't be surprised if more accidental protocol returns happen down the line.

**Comment by olpeh** [comment]
Thanks @tpreusse this workaround seems to work and we can go to prod with that. Of course it's not optimal as you mentioned about the 7kb optimization loss, but it's better than broken links :+1:

**Comment by majidzeno** [comment]
@tpreusse Thanks, this workaround is doing the job.

**Comment by chuyik** [comment]
Report: This still happens on Next.js 9.3.4, while old chromium browser(49.0.2623.221) could not redirect with router, but the workaround above works perfect.

**Comment by codeHatcher** [comment]
experiencing a similar issue here

**Comment by carloscuesta** [comment]
I can confirm with that with`next@9.3.3` the issue exists again. I don't know why this keeps getting removed, maybe next doesn't wants to support those browsers anymore ?

**Comment by phamhieu** [comment]
I can confirm that with next@9.3.4 the issue exists on iOs 12.1.4 Everytime clicks on a link, it goes to 404 page.

I have another device with iOs 12.4.3, it works properly.

**Comment by ztratar** [comment]
Is this just Safari 10?

I am also getting errors on iOS 13.3.1. Most times people click a link in iOS Safari, the site crashes. I have sentry installed and it's not throwing errors. Mobile safari appears to be the only affected browser, and this seems to happen due to "next/Link".

site: https://billionaireboard.com

**Comment by ztratar** [comment]
FYI - it appears that only iOS 13.3 so far has been verified to cause this issue. Newer versions (13.14.5) have confirmed to function properly.

**Comment by zhbhun** [comment]
@karl 

> Do we want to support Safari 10? This browser is end-of-life but seems to still have a decent number of active users.
> 
> We've had at least two issues crop up about it (I've seen more that I don't have on hand):
> Fixes #9782
> Fixes #9827
> 
> This is due to Safari 10 incorrectly implementing `URL`, so Next.js wont work even if users polyfill support back. As a result, client-side transitions try to happen via server-side and fail:
> 
> ![image](https://user-images.githubusercontent.com/616428/71531393-85161100-28bc-11ea-8b9d-ede2eb705c87.png)
> 
> Correct behavior (Safari 11+):
> ![image](https://user-images.githubusercontent.com/616428/71531417-93fcc380-28bc-11ea-9588-b58d280ee109.png)

@Timer It's not ios safari bug, ios safari 10 URL is valid. I found ios safari 10 would download next.js polyfill chunks, which have a module named `url-polyfills` —— https://github.com/zeit/next.js/blob/v9.3.6/packages/next-polyfill-nomodule/src/index.js#L50. As you've said, `new URL('/blog')` shoud throw error. In fact, ios safari 10 native URL throw error correctly, and `url-polyfills` doese not throw error.

**Comment by acifani** [comment]
Same thing happens for old Chrome versions (e.g. 49), as documented in https://github.com/zeit/next.js/issues/11702

**Comment by alexypdu** [comment]
Upgrading to `next@9.4.2` fixes the issue on `iOS 10.2.1`.

**Comment by carloscuesta** [comment]
I'm using the solution proposed by @tpreusse . Has this issue been fixed on Next `9.4` ? I upgraded to `9.4.4` and would be cool to have confirmation from the Next.js team 🙏 

Thanks!

**Comment by timneutkens** [comment]
@carloscuesta based on @alexypdu this issue has been fixed 👍

**Comment by borisdedejski** [comment]
It is not working again I have `next 9.4.4` and it is not working in safari :(

**Comment by timneutkens** [comment]
> It is not working again I have `next 9.4.4` and it is not working in safari :(

Try next@canary

**Comment by joaovbibiano** [comment]
Guys, I'm using next v10, and my website does not load on Safari.

Something that can I do?

**Comment by joaovbibiano** [comment]
> We also got reports about broken links again from users with old iOS and Android versions.
> 
> The problem seems to be that `native-url` returns a protocol on those devices even when it shouldn't. Probably a problem that only occurs in combination with the `url-polyfill` and maybe even then with certain browser engine version only.
> 
> @olpeh I used a ultima ratio solution for now and disabled `native-url` via `next.config.js`:
> 
> ```js
> module.exports = {
>   webpack: config => {
>     const alias = { ...config.resolve.alias }
>     delete alias.url // alias to native-url
>     config.resolve = {
>       ...config.resolve,
>       alias
>     }
>     return config
>   }
> }
> ```
> 
> (by doing that you'll also loose the 7kb optimisation of `native-url` on all platforms)
> 
> Specifically broken were: iOS 9.3 (reproduced in Simulator), Android 6 (only reported, not reproduced)
> 
> @Timer would you like to see the root issue solved in `native-url`/`url-polyfill` or could you also imagine adapting the protocol check in the router?
> https://github.com/zeit/next.js/blob/b274fe39d38111588e625342a89dc568ad38fff5/packages/next/next-server/lib/router/router.ts#L395-L404
> 
> (e.g. doing a string check on the unparsed url like `url.match(/^[a-z]+:/)`)
> 
> The «not returning a protocol» logic of `native-url` is quite convoluted 🙈
> https://github.com/GoogleChromeLabs/native-url/blob/19aacc0a82f7e36995bde6adc6876f6140d6d06a/src/parse.js#L95-L126
> So wouldn't be surprised if more accidental protocol returns happen down the line.

Using this I'm be able to render the website! But I lost the translations.... Can you help me?

**Comment by joaovbibiano** [comment]
> We also got reports about broken links again from users with old iOS and Android versions.
> 
> The problem seems to be that `native-url` returns a protocol on those devices even when it shouldn't. Probably a problem that only occurs in combination with the `url-polyfill` and maybe even then with certain browser engine version only.
> 
> @olpeh I used a ultima ratio solution for now and disabled `native-url` via `next.config.js`:
> 
> ```js
> module.exports = {
>   webpack: config => {
>     const alias = { ...config.resolve.alias }
>     delete alias.url // alias to native-url
>     config.resolve = {
>       ...config.resolve,
>       alias
>     }
>     return config
>   }
> }
> ```
> 
> (by doing that you'll also loose the 7kb optimisation of `native-url` on all platforms)
> 
> Specifically broken were: iOS 9.3 (reproduced in Simulator), Android 6 (only reported, not reproduced)
> 
> @Timer would you like to see the root issue solved in `native-url`/`url-polyfill` or could you also imagine adapting the protocol check in the router?
> https://github.com/zeit/next.js/blob/b274fe39d38111588e625342a89dc568ad38fff5/packages/next/next-server/lib/router/router.ts#L395-L404
> 
> (e.g. doing a string check on the unparsed url like `url.match(/^[a-z]+:/)`)
> 
> The «not returning a protocol» logic of `native-url` is quite convoluted see_no_evil
> https://github.com/GoogleChromeLabs/native-url/blob/19aacc0a82f7e36995bde6adc6876f6140d6d06a/src/parse.js#L95-L126
> So wouldn't be surprised if more accidental protocol returns happen down the line.

@tpreusse Do you have other alternative than that ? Because my translations "next v10" stopped working

**Comment by ICEPrey** [comment]
Hello i just wanted to say it doesn't work on iphone. Everytime i go on my website its just a blank page and it dosent matter what browser i am using. I tried all browsers, still white page. You can test it on the site animex.ninja

**Comment by joaovbibiano** [comment]
> Hello i just wanted to say it doesn't work on iphone. Everytime i go on my website its just a blank page and it dosent matter what browser i am using. I tried all browsers, still white page. You can test it on the site animex.ninja

Please check https://github.com/vinissimus/next-translate/issues/508#issuecomment-778663166

**Comment by ICEPrey** [comment]
Dosen't work

**Comment by ICEPrey** [comment]
> > Hello i just wanted to say it doesn't work on iphone. Everytime i go on my website its just a blank page and it dosent matter what browser i am using. I tried all browsers, still white page. You can test it on the site animex.ninja
> 
> Please check [vinissimus/next-translate#508 (comment)](https://github.com/vinissimus/next-translate/issues/508#issuecomment-778663166)

What do I do, there are no errors that show up, just white screen and that didn' t help me.

**Comment by SSylvain1989** [comment]
Hello. Same issue here..
Anyone solve it ? 
It's really very annoying to put together a whole project and see that it doesn't work !
Put this issue in the front page on nextJs... Waste of my time.

**Comment by machineghost** [comment]
Just one more vote to re-open.  I don't have any special fonts on my site, but I have users reporting it doesn't work, _only_ on Safari (but it works fine one every other browser).

**Comment by SSylvain1989** [comment]
Il you use any other font it will brake that was the case for me

**Comment by bayraak** [comment]
Issue continues

**Comment by renvieir** [comment]
Having the same issue

**Comment by lachlanjc** [comment]
Also had user reports of my site being unavailable on Safari 10.

@timneutkens This issue was re-introduced with Next 10—there's internals of Next using un-polyfilled methods Safari 10 doesn't have available

**Comment by machineghost** [comment]
Guys, the Next.js devs just don't believe you: they believe there is nothing wrong with the library, and it's our fault.  See https://github.com/vercel/next.js/issues/24202#issuecomment-822114997 ... I tried to get them to pay attention to this issue, and they literally said:

>we have tests covering Safari 10.1 here https://github.com/vercel/next.js/runs/2374476653 which are passing correctly. 

So until someone spoon-feeds things to them (eg. by providing a failing test case) it's simply going to go unaddressed, because they *don't believe* it's their fault.

**Comment by lachlanjc** [comment]
@machineghost The Next.js team is juggling literally thousands of issues/PRs/comments while trying to build & release new features—this issue didn't have a specific reproduction, so I don't blame them for not prioritizing it.

For me, the issue is with next/image's, specifically on `layout="responsive"`. The client bundle is ending up using `.matchAll`, which would need a polyfill.

![image](https://user-images.githubusercontent.com/5074763/118053180-e1a29080-b338-11eb-9c71-a326f5d5c971.png)
![image](https://user-images.githubusercontent.com/5074763/118053134-cd5e9380-b338-11eb-85e6-8a9be1471f50.png)

Source code causing the issue: https://github.com/vercel/next.js/blob/c76170e82929bcf960ae577280eb5cb81f9919bd/packages/next/client/image.tsx#L107

I tested this on Safari 10.1 on macOS Sierra on BrowserStack. Happy to provide any more details if needed.

**Comment by timneutkens** [comment]
> For me, the issue is with next/image's, specifically on layout="responsive". The client bundle is ending up using .matchAll, which would need a polyfill.

This has been fixed recently (currently on canary), also affected IE11.

> Guys, the Next.js devs just don't believe you: they believe there is nothing wrong with the library, and it's our fault. See #24202 (comment) ... I tried to get them to pay attention to this issue, and they literally said:

What JJ said is that there are tests covering that version of Safari and that they're currently passing, meaning that the issue that you're running into is not easily reproducible (which we tried) and because you did not provide a reproduction the issue is not actionable and can't be investigated further, which is clearly mentioned in the issue template.

If you're running into a particular issue please first check if there's an open issue similar/same to yours, if there is no open issue for it please open a **new** issue that follows the full issue template which includes providing a reproduction so that it can be looked at / advice can be provided. 

As @lachlanjc said we handle approximately 100 to 150 notifications every day and "same issue" on a closed issue that has tests is unfortunately not enough to be able to reproduce an issue in one particular app without knowing what customization, libraries, settings, etc. are used.

> So until someone spoon-feeds things to them (eg. by providing a failing test case) it's simply going to go unaddressed, because they don't believe it's their fault.

This has nothing to do with "whose fault it is" or not acknowledging something in your app is not working as you intended, it's about being able to investigate and fix a bug that you're reporting, we tried to investigate but could not find an issue because you did not provide a reproduction.

You don't have to provide a test case, only a repository that can be investigated. 
The reproduction also generally applies as a base for the integration tests we add.

Every bugfix/feature PR has tests added to the test suite, it's currently holding over 3400 integration tests which are expanded every day and run on every PR.

**Comment by machineghost** [comment]
To be clear, if you review my last comment I was in no way _blaming_ anyone; I was simply describing (in blunt terms) the current state.

Look, on _any_ OSS project, the team will take it upon themselves to fix some issues _without_ reproduction steps, because the problem is obvious: it's clearly it's "the library's fault". Other tickets have nothing to do with the library, and result from user confusion, so the team will (legitimately) keep blaming outside sources, demanding reproduction steps or other proof (which will never come).

... and _some_ issues seem to obviously be the library's fault to the user ... but don't seem to be to the maintainers.  This is one of those issues. Such issues have to be "spoon fed" with reproduction steps and other details, because the user thinks it's the first type of bug, and the team thinks it's the second.

As such, if we (users) want them (the Next.js team) to fix this problem, we have to "spoon-feed" them proof that it originates ub  Next.js code (ie. it is Next.js's "fault").  My comment (and it's blunt tone) was absolutely meant to try and encourage such "spoon feeding" from the users here, or _maybe_ draw some dev attention ... but again, I was in no way faulting anyone.

**Comment by lachlanjc** [comment]
Update: canary solved my issue! Thanks for your work there @timneutkens.

**Comment by timneutkens** [comment]
Just to be clear we tried to reproduce this issue in various ways but could not reproduce it. Here's 2 separate urls: one a basic page and one an enterprise-grade Next.js app with hundreds of pages / thousands of components, both on the latest version:

- https://my-app-testing-3lfhobyc5-timvercel.vercel.app/ (latest canary)
- https://vercel.com (10.2.0)

Both were tested in Browserstack on real devices:

- iPhone 7 with iOS 10, which uses Safari 10
- macOS Sierra which uses Safari 10.1

<img width="1676" alt="Screen Shot 2021-05-14 at 11 36 34" src="https://user-images.githubusercontent.com/6324199/118252239-d53d4580-b4a8-11eb-84fc-66833f7f8e65.png">
<img width="1675" alt="Screen Shot 2021-05-14 at 11 35 59" src="https://user-images.githubusercontent.com/6324199/118252254-d8d0cc80-b4a8-11eb-878e-4db0528405c1.png">
<img width="1682" alt="Screen Shot 2021-05-14 at 11 33 32" src="https://user-images.githubusercontent.com/6324199/118252259-da01f980-b4a8-11eb-8197-1bb28dceedc8.png">
<img width="1679" alt="Screen Shot 2021-05-14 at 11 32 33" src="https://user-images.githubusercontent.com/6324199/118252266-dbcbbd00-b4a8-11eb-8dc8-4317ec5dfade.png">

As you can see both run completely fine with Safari 10, so we can't investigate more than we already have without a reproduction.

> but again, I was in no way faulting anyone.

You literally said this:

> Guys, the Next.js devs just don't believe you

Which is not true, we asked for a reproduction as the issue that you're having in your particular app can't be reproduced on other applications. If you provide a reproduction we'd be happy to take a look and investigate. 

Your choice of words is not very helpful, especially after we spent multiple hours investigating your issue without a reproduction provided.

**Comment by machineghost** [comment]
Why not open this issue then?

A closed ticket ultimately says "we don't believe this is an issue".  An open ticket (with comments saying "we need reproduction steps to fix this") says "we believe this _is_an issue ... but we can't solve it without your help."

**Comment by timneutkens** [comment]
> Why not open this issue then?

Because this issue was fixed in 2019 and tests for this case were added. As said we'd be happy to take a look at any issue that follows the issue template which requires a reproduction to be provided.

**Comment by amirhosseinkh2515** [comment]
have the same problem on next 11.1.2 please reopen and fix this please .

**Comment by timneutkens** [comment]
Please open a new issue with a reproduction.
